### ISSUE TITLE
"Close after capture" should be removed

### ISSUE THREAD

**Issue by simonbcn** [flameshot-org/flameshot#1096]
```
Arch Linux
Flameshot v0.8.5
Compiled with Qt 5.15.1
```
I have activated `Close after capture`.
When I execute `flameshot config` and close the config window, `flameshot` remains in background. I think the option should be renamed something like "_Remain in the background_" or better not to put that option and let the options "_Show icon on taskbar_" and/or "_Launch at startup_" determine that behavior. What's the point of having "_Show icon on taskbar_" and/or "_Launch on startup_" and "_Close after capture_" activated?
And if I have only activated "_Close after capture_" (_and deactivated the other two_) but I open the program to configure something (`flameshot config`), when I close the config window, it remains then in the background, when I really don't want or make sense.

**Comment by borgmanJeremy** [comment]
I strongly am inclined to remove "close after capture". It was added before I took over the project and looking through the original thread Lupo seemed hesitant to add it.

It causes more issues than any other feature I can thinking of. 

1. New users post issues and are confused about why the program closed
1. Users are not aware they need a clipboard manager to store clipboard data 
1. The code itself is unsound for this feature and keeps manifesting strange issues. There are many race conditions that the devs (me and others) don't understand that require us to finish any clipboard function before sending notifications or the DE freezes. 

I strongly agree with Lupo's original argument that a small bit a RAM to leave this process running is meaningless. Currently Flameshot is using 44MB on my system.

I adjusted the title of this issue to reflect that I am planning to remove this feature as the permanent corrective solution for this bug.

**Comment by mmahmoudian** [comment]
@borgmanJeremy regarding points 1 & 3, I don't have strong feeling towards/against it, but to me it feels that the implementation is wrong. Personally what I would expect from such setting is that when the job is done (either save to disk, copy to clipboard, generating notification, uploading, etc.), the application terminate itself. Therefore, I don't see why process race should happen. I can see that this can be useful for scripting, although one can always run a `pkill flameshot` to clean up after the script. What I can see is that this option can be removed from config and get added as an argument to CLI. The positive side of having it as a CLI argument is that it is not like a config that you forget about it, as you should explicitly specify it in the argument every single time.

If you think it is hard to convert the functionality to a CLI argument, remove it; otherwise, just change it to CLI argument.


About your second point though, perhaps we can implement an initial check to see if all the dependencies are installed on the host machine.

**Comment by mmahmoudian** [comment]
@borgmanJeremy should this issue be closed considering the merged changes?

**Comment by borgmanJeremy** [comment]
@mmahmoudian Yeah probably, I want to back port it to a 0.8.x release but it's manual work so I'd rather bundle it with other bug fixes.
