### ISSUE TITLE
CTRL+A from selection screen 

### ISSUE THREAD

**Issue by astrosticks** [flameshot-org/flameshot#1099]
Usually, the fact that I want to take a screenshot is first in my mind, and then the scope of what the screenshot should contain comes second. So what ends up happening is that I'll hit PrtSc, realize that I want to include my entire screen, and then have to take my hands off the keyboard to grab my mouse. 

It would be nice if using the keyboard shortcut `ctrl+A` would create a selection that covers the entire screen (or moves an existing selection's anchors), for us "screenshot first, edit second" kinds of people. 

Lightshot already has this shortcut, if that's worth noting.

**Comment by borgmanJeremy** [comment]
This seems like a good idea, low effort, and low impact to the code base. I'll pencil it in for 0.9.

**Comment by mmahmoudian** [comment]
I assume this is different from pressing Enter and  capturing the whole screen as you would like to annotate it before copying to clipboard or saving it. The question is that considering the selection is always a rectangle, what happens when you Ctrl+A when you have more than one monitor and your monitors are not aligned (e.g one of them are landscape and the other one is portrait)? Do you only expand the selection to one monitor? if so, would you do it to primary monitor or the monitor that the mouse is on it or... ?

**Comment by borgmanJeremy** [comment]
CTRL + A would only expand the selection to the monitor that is actively being drawn on. In general the flameshot gui will be moving to only one monitor at a time. 

I think the only exception will be if you do a true full screen with no annotation.
