### ISSUE TITLE
Flameshot 无法在 Arch Linux 的 Gnome Wayland 会话下正确处理缩放

### ISSUE THREAD

**Issue by MarksonHon** [flameshot-org/flameshot#1173]
**Flameshot version**
v8.5 built Qt 5.15 Arch

**Describe the bug**
在默认的 Gnome 会话中，我的使用了 200% 的缩放（3840×2160的实际分辨率）。在此环境下如果使用 Xwayland 来运行 Flameshot，那么 Flameshot 能
正确识别整个屏幕的大小并进行区域截图。但是，使用 `QT_QPA_PLATFORM=wayland` 变量让它运行于 Wayland 之下之后，Flameshot 能够正常截取全屏，但是截取区域截图的时候，Flameshot 只显示了 1/4 的画面供我选取截取，
其它的画面无法查看与截取。

**To Reproduce**
1、Gnome Wayland 下启动：`QT_QPA_PLATFORM=wayland flameshot`
2、截图

**Expected behavior**
无特殊操作

**System Information**
Arch Linux Gnome 3.28

**附带截图：**
[![DgtOOA.png](https://s3.ax1x.com/2020/11/29/DgtOOA.png)](https://imgchr.com/i/DgtOOA)

PS：理论上 Xwayland 应用只能获取到被缩放后的假分辨率，即1080P，而Wayland应用能获取到实际分辨率与缩放（4K，缩放200%）。

**Comment by ZetaoYang** [comment]
#### Translated with Google Translate.
---

**Flameshot version**
v0.8.5 built Qt 5.15 Arch

**Describe the bug**
In the default Gnome session, I use 200% scaling (3840×2160 actual resolution). If you run Flameshot with Xwayland in this environment, then Flameshot correctly recognizes the entire screen size and takes area shots. However, after using the `QT_QPA_PLATFORM=wayland` variable to make it run under Wayland, Flameshot was able to capture the full screen, but when I took a region capture, Flameshot only showed 1/4 of the screen for me to select and capture, the rest of the screen was not viewable and captureable.

**To Reproduce**
1. Start under Gnome Wayland：`QT_QPA_PLATFORM=wayland flameshot`
2. Capture screenshots

**Expected behavior**
No special operation

**System Information**
Arch Linux Gnome 3.28

**With screenshots: **
[![DgtOOA.png](https://camo.githubusercontent.com/d55e6c52580f4a05c5e914a04cac783aaa8980efb834042275a29308ebdcae43/68747470733a2f2f73332e617831782e636f6d2f323032302f31312f32392f4467744f4f412e706e67)](https://imgchr.com/i/DgtOOA)

PS：Theoretically, the Xwayland application can only get the scaled dummy resolution, i.e. 1080p, while the Wayland application can get the actual resolution with scaling (4K, 200% scaling).

**Comment by ZetaoYang** [comment]
I think this's duplicated with #748 #564.

**Comment by borgmanJeremy** [comment]
@ZetaoYang Thanks, this is a duplicate so I will close this. I have actively been working on the scaling on X11, but haven't started fixing it for wayland yet.

**Comment by crifan** [comment]
For my here Settings->Display->**Scale: 150%**, finally fixed by change flameshot shortcut from:
`flameshot gui`
to
`env QT_AUTO_SCREEN_SCALE_FACTOR=1.5 flameshot gui`
