### ISSUE TITLE
Launch screenshot GUI from menu icon

### ISSUE THREAD

**Issue by locness3** [flameshot-org/flameshot#1189]
When starting flameshot from the default menu entry, it will run in the background in the system tray, and you have to click this tray icon to take a screenshot. launching flameshot again from the menu will launch another instance of flameshot, requiring you to keep this icon in the tray or use the "take a screenshot" shrotcut from your app dock (assuming you have one). I'd like to be able to just click on the flameshot menu icon to take a screenshot.

**Comment by mmahmoudian** [comment]
You have the following options:
- define your own shortcut key/deskto icon to execute `flameshot gui`
- put Flameshot among the startup applications

**Comment by locness3** [comment]
> define your own shortcut key/deskto icon to execute flameshot gui

Yep, but it would be nice if this was the default. Also, what's the point of the background app?

**Comment by mmahmoudian** [comment]
Most of users use the printscreen (<kbd>prntscrn</kbd>) button to take a screenshot and in most distros you would get the correct keybinding with Flameshot (and if not, fixing it would take 15 seconds). I myself have rarely used terminal to spawn Flameshot. I also suggest you to use the <kbd>prntscrn</kbd> as it is really straightforward.

But the reason Flameshot works this way is because of the design and the DBus system it uses.

-------

@borgmanJeremy @ZetaoYang @Martin-Eckleben @lupoDharkael @AlexP11223 
I wonder what do you think about this issue.

**Comment by locness3** [comment]
Sadly, I'm on a Mac keyboard, so not prtscrn.

**Comment by mmahmoudian** [comment]
Are you also using OSX? If so, #1193 might be related.

**Comment by locness3** [comment]
I don't use OSX anymore.

**Comment by locness3** [comment]
Couldn't it be possible to change the prntscrn shortcut from flameshot itself?

**Comment by locness3** [comment]
I know how to set a shortcut up on my distro and I did it.

**Comment by borgmanJeremy** [comment]
@mmahmoudian Sorry for the delay. This sounds like a pretty unique use case. I agree with you that most of our users use the print screen button. You could also map this to another key combo in your DE if the printscreen button is missing on the keyboard.
