### ISSUE TITLE
Critical issue when switching to another Virtual Desktop

### ISSUE THREAD

**Issue by madjoe** [flameshot-org/flameshot#1232]
**Flameshot version**
Flameshot v0.8.5
```
Compiled with Qt 5.15.1
Server protocol: x11
Monitors: 1
 0: +*DP-7 1920/160x1080/90+0+0  DP-7
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 32767 x 32767
DP-7 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 160mm x 90mm
   1920x1080     60.00*+  59.94    50.00    29.97    25.00    23.98    60.05    60.00    50.04  
   1680x1050     59.95  
   1600x1200     60.00  
   1440x900      74.98    59.89  
   1280x1024     75.02    60.02  
   1280x960      60.00  
   1280x800      59.81  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    70.07    60.00  
   800x600       75.00    72.19    60.32    56.25  
   720x576       50.00    50.00  
   720x480       59.94    59.94  
   640x480       75.00    72.81    59.94 

01:00.0 VGA compatible controller: NVIDIA Corporation GP106GL [Quadro P2000] (rev a1)
```
**Describe the bug**
By pressing a shortcut key to start Flameshot becomes a very critical issue in case you switch to another virtual desktop if you don't press `ESC` previously. 

**To Reproduce**
- in virtual desktop A you have a content A
- in virtual desktop B you have a content B
- you start a Flameshot in B, but you need an information from A in order to annotate your screenshot
- in the middle of process of annotating your screenshot, you move to A
- your Flameshot's fullscreen window **remains on ALL virtual desktops** and **your keyboard becomes unresponsive** (including ESC, Ctrl+C)

**Expected behavior**
We should be able to switch virtual desktops in order to consult the content from other places to be able to annotate our screenshots properly.

**System Information**
5.4.85-1-MANJARO

**Comment by mmahmoudian** [comment]
What is your Desktop Environment or Window Manager?

**Comment by madjoe** [comment]
> What is your Desktop Environment or Window Manager?

KDE Plasma version: 5.20.4
KDE Frameworks version: 5.77.0
Window manager: KWin

**Comment by mmahmoudian** [comment]
I just tested this with 0.8.3 and 0.8.5 and I see two separate issues here:

1. **A bug**: The <kbd>Esc</kbd> does not work when switching virtual desktop is attempted (the change does not happen, but <kbd>Esc</kbd> stops working to get the user out of Flameshot. High similarity to #133 and #1072.

2. **A feature request**: To have Flameshot only to stick to one virtual desktop so that the user can switch desktops easily. This would probably bring some discussion as then people would ask to be able to force Flameshot to stick to one monitor so that they can copy stuff from the other monitor and so on and so forth. Kind feels like a rabbit-hole imho. I'm not against changing desktops, but I'm against implementing it so granular that makes the whole process complicated for end user. Therefore I suggest to draw the line at virtual desktop and never implement in more granular level.



@borgmanJeremy what do you suggest for the first point? And any thoughts on the 2nd?

**Comment by madjoe** [comment]
Indeed, 1) is very similar, but not equal and 2) seems like a rabbit hole. Well, if you would give up from the idea, the I'd suggest to at least prevent the <key>Alt</key>+<key>Tab</key> (or similar) of <key>Meta</key>+<key>arrow keys</key> (or similar), since it leads to the system being unresponsive.

**Comment by mmahmoudian** [comment]
To be clear, what I meant was that I support the idea of being able to change virtual desktop (considering that all OSs and WMs I know including Win10 and OSX have implemented virtual desktops), but anything more granular than that would probably become too much for a screenshot tool.

**Comment by veracioux** [comment]
Does PR https://github.com/flameshot-org/flameshot/pull/1958 help with this?
