### ISSUE TITLE
Use the filename configuration for clipboard content too

### ISSUE THREAD

**Issue by LivingWithHippos** [flameshot-org/flameshot#1240]
**Is your feature request related to a problem?**
Yes, using wiki.js to upload images from the clipboard (ctrl+v) is a problem because the file always takes the name of `Image1.png` and I can't change it, if I accept it it overwrites the older one, I need to save it locally and upload it manually.

I tried it in libreoffice writer where the name gets a progressive number -> `Image2.png`, `Image3.png` which would be totally fine.

I'm on Manjaro Linux xfce with flameshot 0.8.5-1

**Comment by mmahmoudian** [comment]
I don't understand what exactly you want. Can you elaborate more?

**Comment by LivingWithHippos** [comment]
Of course, I'll try to explain it better:

1. Many web service accept images from the clipboard as upload: pressing ctrl+v will add it to the upload queue
2. The name of the uploaded file is automatically taken from  some image metadata taken from the clipboard (I think)
3. The problem is that the file name is always `Image1.png`
4. files with the same names can't be uploaded to the same folder

If the name changed to Image2.png, 3 ... or if it followed the naming convention you can set in flameshot for locally saved files it would fix this small (I just have to save the file locally, rename it and upload it again instead of pressing ctrl+v) issue

**Comment by kpcee** [comment]
This request cannot be implemented. QClipboard contains either the binary image data, which contains no file name information, or a URL. A URL in the format of "file://" is always a local file and not the image itself. When you copy an image in the file manager, you are not copying the image itself, but a URL. So to implement this wish flameshot would first have to save the file locally and copy this URL to the clipboard so that you could paste it somewhere else. But programs like GIMP can't do anything with such URLs and you can't insert such a "picture" with CTRL+V / CTRL+V anymore.

I don't think that would be an improvement. Especially since new problems arise how and when to delete these images and if not what happens with this ever growing cache. To change the behavior this "wiki.js" should be adapted instead.

**Comment by LivingWithHippos** [comment]
Thanks, no problem, I tought it was written by flameshot and read by wikijs
