### ISSUE TITLE
Serious bug if path not present

### ISSUE THREAD

**Issue by kpcee** [flameshot-org/flameshot#1364]
I have found an extremely unsightly bug that, in the worst case, can cause Flameshot to run amok and possibly cripple the system. The bug consists of 2 parts:

Part 1:
First, you have to set a path that doesn't exist or that Flameshot can't save to. Since the path ~/Pictures is set at startup, this is easy to do on systems with languages other than English. 

Now select Open Launcher and choose "Full Screen" and "Take new screenshot". Next a messagebox pops up saying that it is not possible to save. If you click on Ok, the message appears again → endless loop! 

Part 2:
If the user now tries to quit Flameshot via Exit from tray menu, the fun really starts and Flameshot runs amok. The message box opens and closes automatically in an endless loop and only closing it via the task manager can prevent worse.

Git version (commit 16fd3b2915829ccb550a023d7b829b7a46beebde)
Arch Linux

**Comment by borgmanJeremy** [comment]
What DE  was this on? I am not able to replicate it on KDE / Arch.

**Comment by kpcee** [comment]
Xfce with Arch Linux.

**Comment by borgmanJeremy** [comment]
Okay thanks. After some investigation the issue is not caused by the path specific in the config file not being present. It specifically is caused by ~/Pictures not being present. The reason is flameshot falls back to QStandardPaths::PicturesLocation when the specified path is not found. 

I agree we need to error handle the case where this path does not exist.

**Comment by kpcee** [comment]
That works, great!
