### ISSUE TITLE
Print screen the content of a dropdown in Firefox

### ISSUE THREAD

**Issue by flori4n** [flameshot-org/flameshot#1385]
**Flameshot version**
```
flameshot --version
Flameshot v0.8.5
Compiled with Qt 5.12.3
```

**Describe the bug**
When I press the "PRT SCR" on my keyboard it closes the drop down in firefox
![image](https://user-images.githubusercontent.com/5012269/108818667-0436d000-75ba-11eb-8968-4e2c9ef627c7.png)

**To Reproduce**
Using Firefox, go in https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select and open the drop down menu.
Use your shortcut key to capture the content of the drop down, the menu will close before you could get the content.

**Expected behavior**
See the content of the drop down as you have in chrome
![image](https://user-images.githubusercontent.com/5012269/108818730-19136380-75ba-11eb-9473-9d19211606da.png)

**System Information**
```
Ubuntu 20.04.2 LTS
Firefox 85.0.1 (64-bit)
```

**Comment by mmahmoudian** [comment]
This is not a bug. This is the standard behaviour that the menu or dropdown box will be closed when the window goes out of focus or and update to the page happens. That is the reason as a general practice, we have implemented a timer that user can specify how many seconds Flameshot should wait until the screen is captured. To activate this, you should either use terminal or use the launcher window (right click on Flameshot tray icon and click on launcher from the menu).

If you still believe this is a bug, please elaborate more and explain why, otherwise please close this issue. 👍🏼
