### ISSUE TITLE
flameshot-0.9.0.rc2-win64 on Win10 crashed when typing by hand filename format to save

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [flameshot-org/flameshot#1392]
filename format by my mistake
ss_%Y_%m_%j__%H_%M_%S
I want correct to "ss_%Y_%m_%d__%H_%M_%S"
when I try delete "j" (format = ss_%Y_%m_%__%H_%M_%S) flameshot crashed.

**Comment by hosiet** [comment]
I can reproduce this bug. Besides, editing the format line may randomly trigger crash as well.

This bug is also present of flameshot v0.8.4 (Windows 10).

I cannot reproduce this bug on Linux platform.

**Comment by borgmanJeremy** [comment]
I have a different issue on 0.9.RC2 where I cannot edit the field at all. I'll try to squeeze a fix in before 0.9

**Comment by borgmanJeremy** [comment]
I think this is a much deeper issue. The config page seems to be constantly being redrawn and I am not sure why yet.

**Comment by borgmanJeremy** [comment]
Okay, the config issue is a seperate problem so I will not address that here.

The reported issue with the input specific is pretty straightforward. Per the [MSVC Documentation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=msvc-160) if an ill formed input specifer is given, the CRT will crash:
>This function validates its parameters. If strDest, format, or timeptr is a null pointer, or if the tm data structure addressed by timeptr is invalid (for example, if it contains out of range values for the time or date), or if the format string contains an invalid formatting code, the **invalid parameter handler is invoked**, as described in Parameter Validation. If execution is allowed to continue, the function returns 0 and sets errno to EINVAL.

I do not want to write an "invalid parameter handler". Our options are to accept that if we allow raw input and the input is invalid it will crash. Or my preference would be to write an input validator function. 

This function would just need to ensure that the escape key '%', was only used to escape acceptable format codes. If an invalid one is returned we will just return an empty string.  I don't think this will make it into the 0.9 release because if we go down this route I really want to unit test the validator and this will take a bit of time. 

I decoupled the issue into a minimal working example: 
![image](https://user-images.githubusercontent.com/46930769/109242221-4d487900-77a0-11eb-8e56-5e95e97126fb.png)

**Comment by aleksandr-shevchenko** [comment]
Write "Error format" in Preview textbox so that the user understands that the format is wrong.

**Comment by mmahmoudian** [comment]
Imho if user don't understand that they have inserted a wrong input, they will assume there is a bug and ultimately we should spend time investigating the issues and telling them that the input is invalid because of ...

I think it would be a good idea to address this in such a way that it clearly tells the user what is wrong and even perhaps point them to a webpage with instructions.

**Comment by hosiet** [comment]
We definitely need to tell user that the format is invalid, that's for sure. Now the problem falls to which technical approach in detecting format error should we choose.

1. Do nothing and let the whole program crash (the current behavior). I really don't think this is a long-term solution.
2. Writing a Microsoft WIndows-specific "invalid parameter handler" (I guess it refers to [this one](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/set-invalid-parameter-handler-set-thread-local-invalid-parameter-handler?view=msvc-160)). Jeremy [said](https://github.com/flameshot-org/flameshot/issues/1392#issuecomment-786347604) to be not into writing this.
3. Write a custom input validator function. Well isn't it somehow reinventing the wheel? The function will have to reimplement the whole format logic of `std::strftime()`, which is costly and error-prone. Writing unit tests to eliminate error is also costly.

I have some unusual thoughts: what about spawning a minimal subprocess that only calls `std::strftime()` from MSVCRT each time and feed it with user-provided format string once we receive the string from the user? If the subprocess crashes, we know that the format is invalid, thus able to notify the user in the main process. If the subprocess returns `EXIT_SUCCESS`, we can go ahead and use that string in main process. In this way we do not need to reimplement anything from `strftime()`. The only problem might be spawning subprocesses on Windows could be too slow.

**Comment by borgmanJeremy** [comment]
@hosiet  Here is a minimal example of what I am thinking: https://godbolt.org/z/vvM9Pc 

Rather than write a validator function I do the following:

1. Create list of allowed specifiers
2. Search input string for format specifier starting with %
3. Create a new string that is simply the found allowed specifiers delimited by *
4. Pass to strftime
5. Find and replace "allowed specifiers" with results from strftime.

This should work on all platforms. All that would be left to do is list the rest of the specifiers and write tests. I want to add tests to flameshot anyway so I dont mind do this.

**Comment by hosiet** [comment]
I read the code and that is exactly what I meant by saying "reinventing the wheel". In that code _you_ will still be in charge of ensuring that user's input is valid through the custom list of allowed specifiers, not _MSVCRT_. Essentially there's still some logic of validation inside. This is definitely viable as long as we are to only support specifiers listed on the filename editor config page.

Just a little issue there: the asterisk symbol might needs some further handling. Even in current flameshot 0.9.0, users may type in asterisk in the config window, though file saving won't succeed on a system that disallow asterisk in filename. This is some very corner case.
