### ISSUE TITLE
Can the `-c` option be added to `gui`

### ISSUE THREAD

**Issue by thep0y** [flameshot-org/flameshot#1420]
**Is your feature request related to a problem?**

I often encounter screenshots of areas that only need to be copied to the clipboard.
Almost no need to copy to the clipboard after taking a full-screen screenshot.
能不能为gui增加复制到剪贴板的可选参数，因为在日常使用中，全屏截图后复制到剪贴板的需求很低。

**Comment by mmahmoudian** [comment]
The translation of
> 能不能为gui增加复制到剪贴板的可选参数，因为在日常使用中，全屏截图后复制到剪贴板的需求很低。

is (Google):
> Can you add optional parameters for copying to the clipboard for the gui, because in daily use, the demand for copying to the clipboard after a full-screen screenshot is very low. 

and is (Microsoft)
> Can you add optional parameters for gui to copy to the clipboard, because in daily use, the need to copy to the clipboard after a full-screen screenshot is very low.

**Comment by mmahmoudian** [comment]
@thep0y the `gui` is a mode, but the "copy to clipboard" is an action that finalize/terminates the mode. When you use `flameshot gui` and after selecting the region, you can press <kbd>Ctrl</kbd>+<kbd>c</kbd> or press the copy button to put the screenshot into clipboard. If a CLI argument is added to the mix, then:
1. I don't know how one would then finalize the screenshot
2. what happens when user clicks on the save button or upload to imgur or even press <kbd>Esc</kbd>

Can you explain your idea for these conditions and justify your feature request a bit more.

**Comment by thep0y** [comment]
Sorry, I did not express my meaning clearly. 
In daily use of screenshots, I often use the shortcut key `PrtSc` to take screenshots. Can I draw a rectangular display area for selection after pressing `PrtSc`, and copy the selected image to the clipboard immediately after the area is selected?

**Comment by mmahmoudian** [comment]
@thep0y yes you can already do that. After you selected the area, on your keyboard press <kbd>Crtl</kbd>+<kbd>c</kbd>. You can also change the keyboard shortcut to something else:

![image](https://user-images.githubusercontent.com/390889/109960316-4dd99600-7cf1-11eb-9ac3-2b776bbe650a.png)

**Comment by NikEyX** [comment]
Unfortunately it seems that the latest version took away the ability to copy to clipboard just by pressing "enter" and there is no way to configure this in the options since enter is not recognized as key. Any fix in sight for this?

**Comment by mmahmoudian** [comment]
@NikEyX you issue is duplicate of #1429 and the fix is in #1430

**Comment by mmahmoudian** [comment]
Closed due to inactivity.
