### ISSUE TITLE
Dark gtk theme

### ISSUE THREAD

**Issue by wsalmeida** [flameshot-org/flameshot#1436]
The dialog windows do not obey the standards of the dark system for gtk could add this function?
![2021-03-07_16-24](https://user-images.githubusercontent.com/38542279/110252090-74523800-7f62-11eb-80d8-851c6304d699.png)

**Comment by nullobsi** [comment]
Flameshot uses Qt, which is a different toolkit from GTK. You have two options:
- use GTK platform layer for Qt, which uses GTK2 (GTK4 is releasing soon) and is probably buggy
- use a Qt theme engine like Kvantum/qt5ct in combination with a script to change the Qt theme, which doesn't work dynamically

None of these options are particularly good, and adding a "dark theme" without importing a whole new style engine into Flameshot is impossible.

**Comment by borgmanJeremy** [comment]
Thanks for looking into it @nullobsi . Since it is not possible without a new style engine in flameshot we will not be adding this. For the record flameshot properly follows KDE plasma theming: 

![image](https://user-images.githubusercontent.com/46930769/110514249-ba2b0f80-80cc-11eb-86ee-29a0fe9d0a87.png)
