### ISSUE TITLE
Provide a man page

### ISSUE THREAD

**Issue by jsamr** [flameshot-org/flameshot#1445]
First of all, thanks for this wonderful tool!

I would really love to have access to in-terminal documentation via `man flameshot`, with synopsis, examples ... etc.

**Comment by borgmanJeremy** [comment]
Sure, just need someone to write the documentation :)

**Comment by gregoa** [comment]
There is one in the Debian package:
https://salsa.debian.org/debian/flameshot/-/blob/master/debian/flameshot.1 or https://sources.debian.org/src/flameshot/0.9.0+ds1-1/debian/flameshot.1/

**Comment by hosiet** [comment]
Since I wrote the man page at https://salsa.debian.org/debian/flameshot/-/blob/master/debian/flameshot.1 and released it under CC0-1.0 license, it's perfectly ok if it can be merged into flameshot upstream. Just note that the man page may not cover all current functionalities of flameshot and any further improvement would be welcome. I can prepare a pull request to have it merged into flameshot upstream as-is.
