### ISSUE TITLE
the option is missing [Close after capture]

### ISSUE THREAD

**Issue by grayich** [flameshot-org/flameshot#1452]
flameshot 0.9.0

The option disappeared - [Close after capture]

**Comment by borgmanJeremy** [comment]
Yes, this is intended since this feature caused my bugs. It was unmaintainable.

**Comment by grayich** [comment]
Unclear
But after all, the screenshot in the clipboard then remains after the closure of the flameshot !
Why can the link can not stay?

**Comment by mmahmoudian** [comment]
@grayich the "close after capture" was causing lots of bugs and many confusions for the  users, and removing it was to make the Flameshot easier to understand for the user and also get rid if bugs.

As far as I can remember, you are the only one that has a use case for it. Can you explain the use case and why do you want to kill Flameshot after capture? Also, I didn't understand what you said about the "link". I would be thankful if you can also elaborate on that.

**Comment by grayich** [comment]
@mmahmoudian
For example, I don't take screenshots often, maybe 1-5 a day. Therefore, the program does not need to work all the time. Developers often have good hardware and therefore do not pay attention to resources )  But for me like many users even these 40 megabytes are important )

**Comment by mmahmoudian** [comment]
@grayich & @trevarj if you think this is an important thing to have, all I can suggest is to create a new issue and discuss the importance of such feature. Considering that the "Close after capture" was removed because it created so many bugs, devs need some convincing to re-implement the feature (perhaps this time without those bugs). I'm not a C++ developer but in case you are, implementing it and creating a PR will go a long way.

**Comment by borgmanJeremy** [comment]
Actually please don't just submit a PR with this feature. I really don't want to add it back in without discussion of the design first. It's sort of a flawed concept with the way flameshot is currently designed to work (as a daemon)
