### ISSUE TITLE
Remember screenshot size and position

### ISSUE THREAD

**Issue by victordiaz** [flameshot-org/flameshot#1509]
Use case:
Quite often I have to do multiple screenshots of the same screen area. For example a certain area of an application / web I'm building.

Proposal:
It would be good that flameshoot remembers the last position and size of the screenshot rectangle, so all the subsequent screenshots are taken exactly in the same position and size without any pixel variation. Mac OS uses that technique and it becomes very convenient for repetitive screenshoting.

Btw: Amazing tool, thanks so much!

**Comment by mmahmoudian** [comment]
Can it be solved by #479?

**Comment by eamodio** [comment]
I would love this as well -- so each time you start taking a screenshot it would default to the last position.

**Comment by victordiaz** [comment]
I think an option in the settings such as follows could be very handy

![Frame 1](https://user-images.githubusercontent.com/422387/113565230-f3db3180-960a-11eb-99fb-0e79c4ef3803.png)

**Comment by mmahmoudian** [comment]
I think this is featured request is also related to #417

**Comment by veracioux** [comment]
I am against polluting the GUI with more buttons, or the config with another option. I have a few ideas:
1. Make the Move tool button display a popup with a short history of selections (on click or on hover). Each history entry would be a labeled button showing the geometry of the selection and it would be clickable. When clicked, the selected size would be applied to the selection. A good idea would be to provide a few keyboard shortcuts (Enter, Esc, etc. - not configurable)
2. Upon activating the move tool, if nothing is selected, automatically select the region from the last screenshot capture
3. While the move tool is selected, press a key (e.g. `Enter` or `Space`) to cycle through the selection size history
   - Maybe add a config option to set the max. history size
4. Turn the size indicator widget into an actual button and make it do what I described the move tool button should do above

Note: number 2 and 3 are fairly easy to implement, the others would take some work.

These suggestions can be cherry-picked or used in combination. I am personally rooting for the first three to be implemented. What do you think?

**Comment by borgmanJeremy** [comment]
Instead of remembering the location what if it it’s provided from the cli?Sent from ProtonMail for iOS On Mon, Sep 20, 2021 at 17:19, Haris Gušić ***@***.***> wrote:  
I am against polluting the GUI with more buttons, or the config with another option. I have a few ideas:

Make the Move tool button display a popup with a short history of selections (on click or on hover). Each history entry would be a labeled button showing the geometry of the selection and it would be clickable. When clicked, the selected size would be applied to the selection. A good idea would be to provide a few keyboard shortcuts (Enter, Esc, etc. - not configurable)
Upon activating the move tool, if nothing is selected, automatically select the region from the last screenshot capture
While the move tool is selected, press a key (e.g. Enter or Space) to cycle through the selection size history

Maybe add a config option to set the max. history size


Turn the size indicator widget into an actual button and make it do what I described the move tool button should do above

Note: number 2 and 3 are fairly easy to implement, the others would take some work.
These suggestions can be cherry-picked or used in combination. I am personally rooting for the first three to be implemented. What do you think?

**Comment by veracioux** [comment]
@borgmanJeremy Geometry provided via CLI should override everything of course.

Either the reply-via-email feature is broken, or you messed something up :)

**Comment by borgmanJeremy** [comment]
Haha thanks I fixed it

**Comment by veracioux** [comment]
There has been discussion about the feature. But as someone mentioned in another issue, it would be burdensome to have to use the CLI for that. I think the CLI option is definitely useful, but it can coincide with the other suggestions I made. We can make the CLI option override some things of course.

**Comment by mmahmoudian** [comment]
@veracioux regarding your second point, how would you activate the move tool without making a selection?

Considering the variety of our user base I believe some sort of GUI option should exist along with the CLI. I also very much liked the possibility of toggling between few past selections.

**Comment by veracioux** [comment]
> @veracioux regarding your second point, how would you activate the move tool without making a selection?

Using the keyboard shortcut. The whole purpose of the second point is that users should be able to reselect the last selection quickly. If you don't want to use shortcuts, you'll have to select something first and then click the move tool as point 1 describes.

Fair points about the size indicator.

**Comment by Adolio** [comment]
This one would be a big plus for me.

**Comment by mmahmoudian** [comment]
Thanks to the `--region` implemented in #2010 you can achieve this behavior. For example:

```sh
flameshot gui --region $(flameshot gui -g) --accept-on-select --pin
```

If you want to have sequential screenshot from the same area:

```sh
# select the area once
REGION=$(flameshot gui --print-geometry)

# iterate until user press Esc in the gui mode of flameshot
while true
do
    flameshot gui --region ${REGION} --raw > "/tmp/$(date +'%Y%m%d_%H%M%S').png"
    
    if [ $? == 1 ]; then
        break
    fi
done
```

And the `--accept-on-select` can be combined with `--region` to take screenshot almost without opening the gui:
```sh
# select the area once
REGION=$(flameshot gui --print-geometry)

# sequentially every 5 seconds until user press Ctrl+c:
while true
do
    sleep 5
    flameshot gui --region ${REGION} --accept-on-select --raw > "/tmp/$(date +'%Y%m%d_%H%M%S').png"
    
done
```

You can also set an environmental variable to store the coordinate of the region of interest and always call Flameshot to use that variable as input for `--region`.

**Comment by njminchin** [comment]
@mmahmoudian is this sequential screenshot functionality in the GUI via a shortcut?

**Comment by borgmanJeremy** [comment]
I'm considering adding it to the launcher

**Comment by mmahmoudian** [comment]
@njminchin First off, Flameshot was initially designed for Linux users and every functionality was accessible through command line, so I can safely assume that majority of users can utilise this feature through the `--region`. Second, when the commandline option is implemented, it means the functionality is implemented and the rest is more of less semantics and gui stuff can be easily added if it makes sense to devs.

Lastly, you can always create keyboard shortcut for commands regardless of being on Windows or Linux. It is quick, not complicated at all, and gives you the freedom of tweaking it ￼to your needs. Perhaps you should look into it.

**Comment by Adolio** [comment]
I honestly don't understand why there is so much friction for a key feature like this one. From an UX stand point it makes a lot of sense to keep track of the last used region (or at least having an options to do so, even disabled by default).

No one wants to use environmental variables or create a custom keyboard shortcuts to do a such basic thing.

BTW, Flameshot is a really great tool and this missing feature is truly a pain point at least for me.

**Comment by mmahmoudian** [comment]
@Adolio Perhaps if you follow the progress of the project you will see that your assumptions are unjustified:

![image](https://user-images.githubusercontent.com/390889/166704053-def52073-f402-4680-833f-0507055e0339.png)

![image](https://user-images.githubusercontent.com/390889/166704372-5541259a-065b-4d12-b9a9-dfabb8402485.png)

I provided a temporary, quick-'n-dirty solution for those who desperately need this feature. Instead of getting so critical and perhaps sarcastic, and downvoting things, you can start being more observant and potentially productive. Small effort can goes a long way in FOSS projects.

**Comment by borgmanJeremy** [comment]
Right now it only remembers the region if specified through the launcher, but it could be adjusted to remember the last region irrespective of how the region was specified.

**Comment by psyhlo** [comment]
This cli option is only available for linux, am i right? Is there any chance to make it available for other OS?
Via some config file settings or else?

**Comment by borgmanJeremy** [comment]
The cli is available on MacOS also.


I also just merged a PR that allows you to configure a setting to always remember the last region.

**Comment by psyhlo** [comment]
> The cli is available on MacOS also.
> 
> I also just merged a PR that allows you to configure a setting to always remember the last region.

thanks i cant wait for the new version

**Comment by Binly42** [comment]
Is it considerable to support remembering one more historys, i.e. not only the last one region ?

So that we could use a shortcut to switch between recent regions.

As for use case, supposing that some tasks break into the regular workflow, and therefore we have to deal with them first, during which we may take a temp snip/shot/capture ...
And honestly, it might be quite reasonable for some scenarios to repeatedly snip/shot/capture on one more regions, right?

**Comment by mmahmoudian** [comment]
@Binly42 why not binding two bindings to two slightly different version of the code snippet [I suggested before](https://github.com/flameshot-org/flameshot/issues/1509#issuecomment-1117332447)? Basically two environmental variable names to store the positions

**Comment by Binly42** [comment]
Sorry for I have not had a try on that code snippet ...
Actually, I currently have not yet switched to Flameshot. I was just compare-ing Snipaste and Flameshot ...

---

As for the "two (or, more practical, a list of) bindings" solution.

Yes it would be a fine workaround. Especially if this requirement were indeed too niche ... (sad XD


---

As for my opinion.

After all, Flameshot had already supported remembering the last region. Therefore I was thinking about that might not be too much trouble to enhance from "remember only the last one" to "remember the last some (and navigate between them)" ?

However, must note that there would still be many works to be done to support "use shortcut to switch between regions in snip/shot/capture mode", which is actually what I really want, and with which we can intuitively determine which region is the one we want to reuse.
In contrast, a list of saved region parameters would be much more harder to distinguish ...

And IMO this seems to be a environment-independent feature? If true, it would be better to be integrated into Flameshot (well, if only not too niche ...

Of course, I totally understand that there must be some higher priority or more cost-effective needs to be implemented haha

Jul 9, 2022 14:49:49 Mehrad Mahmoudian ***@***.***>:
