### ISSUE TITLE
Screen Goes Black

### ISSUE THREAD

**Issue by Pharoh-Ramses** [flameshot-org/flameshot#1589]
I'm on Pop-OS. Whenever I try to take a screenshot, the screen will go black and my monitor power led will begin blinking. I must press the ESC key for the screen to come back.

**Comment by mmahmoudian** [comment]
We cannot help you or investigate this unless and until you **completely** provide all the information requested in the bug report template.

This is what we have asked:
> ```
> 
> 
> **Flameshot version**
> 
> 
> **Describe the bug**
> 
> 
> **To Reproduce**
> 
> 
> **Expected behavior**
> 
> 
> **System Information**
> 
> 
> ```

**Comment by IgorMunizS** [comment]
This bug happens when I'm using monitor scaling on Ubuntu 20.04. I have a 2.5k monitor and I prefer to use a 125% scaling for work. If I turn off scaling or set it to 100%, flameshot works fine.

**Flameshot version**
(0.6.0+git20191001-2)

**Describe the bug**
When using monitor scaling on Ubuntu 20.04 I can't use flameshot to take a screenshot. When I try to do that, the monitor lose his signal and the screen goes black. It happens to all monitors. The screen starts to blinking like it's in a loop losing and getting a connection (similar to a cable issue). If not using scaling, flameshot works well.


**To Reproduce**
Set monitor scaling for something above 100% (Ubuntu - Settings-Monitors)  and try to take a screenshot using flameshot.

**Expected behavior**
Monitor should work normally and we should be able to take a screen shot.

**Comment by mmahmoudian** [comment]
@IgorMunizS your Flameshot version is very old. Try installing the new version (at the time of writing this 0.9.0). If your distro doesn't have the latest version, please try installing from either:
- Flatpak
- Snap
- AppImage
- download the .deb package from our GitHub and install it (`dpkg -i FLAMESHOT_FILE.dep`)
- compile it from source

If you don't know how to install from any of the one I listed, please visit https://flameshot.org/getting-started/

I'm closing this issue as the OP never replied back. If you have any issues after installing the new version, please create a new issue with the updated version number.
