### ISSUE TITLE
macOS Global Hotkey Docs

### ISSUE THREAD

**Issue by karlhorky** [flameshot-org/flameshot#1593]
**Is your feature request related to a problem?**

It would be nice to be able to use a global hotkey with macOS, just like the [Linux instructions for Ubuntu / Gnome / KDE](https://flameshot.org/key-bindings/#global).

I would take over writing a short section on this in the docs, but cannot figure out a nice (fast) way to achieve this :(  If the Flameshot screenshot doesn't launch fast, then it's not as much value as it could be.

I have tried the following:

1. Running `/Applications/flameshot.app/Contents/MacOS/flameshot gui` - this appears to do nothing
2. Trying an Automator Apple Script as follows - the script below worked, but it launched super slow - took like 5 seconds to launch

```applescript
tell application "System Events" to tell process "Flameshot"
    tell menu bar item 1 of menu bar 2
        click
        click menu item "Take Screenshot" of menu 1
    end tell
end tell
```

Credit for the Apple Script: https://stackoverflow.com/a/16497564/1268612

Anyone have any ideas how to do this?

**Comment by MatanRubin** [comment]
Regarding 1, seems like it's because of #1292.

My fingers aren't flexible enough to use the default Cmd-Alt-Shift-4 global hotkey for flameshot, so I used a separate tool (BetterTouchTool, not free) to map Cmd-4 to Cmd-Alt-Shift-4, it works really well. 
You can get similar results with any other free keyboard mapper.

**Comment by karlhorky** [comment]
> You can get similar results with any other free keyboard mapper

Nice! Can you elaborate on the settings that you used for this? Is it just mapping <kbd>cmd</kbd>-<kbd>4</kbd> to <kbd>cmd</kbd>-<kbd>alt</kbd>-<kbd>shift</kbd>-<kbd>4</kbd>?

**Comment by MatanRubin** [comment]
😄 
I got it from the configuration menu:
![image](https://user-images.githubusercontent.com/4488227/117463630-8ea39480-af58-11eb-82ad-42a16b175e69.png)

I see that README.md has the keyboard shortcuts for Linux but not macOS, you can probably contribute there

**Comment by Faetu** [comment]
Hi @karlhorky 
 
 The global shortcut, Is a mess.
 Because of this, I try to solve this the same way like you do, over automator.
 And yes, it takes ~5 sec to start the action. I play a little bit with the delay function and this Is my Solution:


```applescript
ignoring application responses
	tell application "System Events" to tell process "Flameshot"
		tell menu bar item 1 of menu bar 2
			click
		end tell
	end tell
end ignoring
delay 0.1
do shell script "killall System\\ Events"

tell application "System Events" to tell process "Flameshot"
	tell menu bar item 1 of menu bar 2
		click menu item "Take Screenshot" of menu 1
	end tell
end tell
```

It is way faster, but sometimes I need to hit the button twice or more then just twice. I don't know why, but it is the best solution at the moment.

best regards

**Comment by Faetu** [comment]
Hi @karlhorky 

I have now a solution for the problem, that the script doesn't work always.
The problem is the focus, if you focus an application that doesn't have the permission to execute applescripts, then the system will block the script and ask for permissions.
I add a second part of script in the automator, that part sets the focus to flameshot and runs the "take screenshot" script:

![image](https://user-images.githubusercontent.com/55803495/117712634-ddf5f900-b1d4-11eb-9e37-f49905d613f5.png)

:) I hope this works!


Focus-part:

```applescript
tell application "System Events"
	tell application "flameshot" to activate
	repeat while (value of attribute "AXfocused" of group 1 of scroll area of ¬
		process "Flameshot" is {false})
		keystroke "<" using command down
	end repeat
end tell
```

Take screenshot part:

```AppleScript
ignoring application responses
	tell application "System Events" to tell process "Flameshot"
		tell menu bar item 1 of menu bar 2
			click
		end tell
	end tell
end ignoring
delay 0.1
do shell script "killall System\\ Events"

tell application "System Events" to tell process "Flameshot"
	tell menu bar item 1 of menu bar 2
		click menu item "Take Screenshot" of menu 1
	end tell
end tell
```

**Comment by nippyin** [comment]
> Hi @karlhorky
> 
> I have now a solution for the problem, that the script doesn't work always.
> The problem is the focus, if you focus an application that doesn't have the permission to execute applescripts, then the system will block the script and ask for permissions.
> I add a second part of script in the automator, that part sets the focus to flameshot and runs the "take screenshot" script:
> 
> ![image](https://user-images.githubusercontent.com/55803495/117712634-ddf5f900-b1d4-11eb-9e37-f49905d613f5.png)
> 
> :) I hope this works!
> 
> Focus-part:
> 
> ```applescript
> tell application "System Events"
> 	tell application "flameshot" to activate
> 	repeat while (value of attribute "AXfocused" of group 1 of scroll area of ¬
> 		process "Flameshot" is {false})
> 		keystroke "<" using command down
> 	end repeat
> end tell
> ```
> 
> Take screenshot part:
> 
> ```applescript
> ignoring application responses
> 	tell application "System Events" to tell process "Flameshot"
> 		tell menu bar item 1 of menu bar 2
> 			click
> 		end tell
> 	end tell
> end ignoring
> delay 0.1
> do shell script "killall System\\ Events"
> 
> tell application "System Events" to tell process "Flameshot"
> 	tell menu bar item 1 of menu bar 2
> 		click menu item "Take Screenshot" of menu 1
> 	end tell
> end tell
> ```

Need some help to set Ctrl+` as a shortcut to capture screen shot. I tried keystroke using "Ctrl+`" surely doing something wrong.
