### ISSUE TITLE
Selection is extremely slow on i3

### ISSUE THREAD

**Issue by Ewael** [flameshot-org/flameshot#1619]
**Flameshot version**
Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**
I just use the `flameshot gui` command and the mouse starts being extremely slow. By slow I mean not usable anymore, it's like 1 fps. Sometimes it happens once I clicked to start the selection, sometimes it happens when I use the command.

**To Reproduce**
Just use `flameshot gui` I guess. I installed it using `pacman -S flameshot` on Manjoro i3 community edition.

**Expected behavior**
It should not be that laggy. I feel like nobody has experienced this before.

**System Information**
Linux 5.10.34-1-MANJARO #1 SMP Sun May 2 11:29:56 UTC 2021 x86_64 GNU/Linux
i3 version 4.19.1
X.Org X Server 1.20.11

**Comment by mmahmoudian** [comment]
@Ewael you didn't mention what graphics card and what graphics drivers you are using in addition to what is your system hardware spec and number of monitors.

As you also mentioned, this is the first time such thing is reported and I myself haven't ever experienced it on Manjaro Xorg on any graphics card (intel, Nvidia, AMD) and multiple desktop environments (Gnome, KDE, Xfce) and some window managers (dwm, AwesomeWM)

But it would be interesting to know if you still experience the same issue with `flameshot-git` from AUR. It will install a build from HEAD of Github master branch.

**Comment by Ewael** [comment]
Sure sorry, I have 3 monitors. I use an `NVIDIA GeForce GTX 770` with the `nouveau` driver. I also tried with `flameshot-git` but I have the exact same problem. As I said I'm using the Manjaro i3 community edition. I do not really know what other specs you need, tell me if you need anything else.

**Comment by Ewael** [comment]
This message may be an error from me because you could stop helping me, but I've just realized I also have problems using `maim` and `shutter`. I feel like this could be related too. Is there any way this could have something to do with `X.Org`?

**Comment by mmahmoudian** [comment]
Can it be an issue with your compositor? Try killing your compositor (e.g picom) and see if you still have this issue.

**Comment by Ewael** [comment]
You are right, without `picom` running it works like a charm. Any idea why et how I could fix it? Thank's a lot anyway.

**Comment by mmahmoudian** [comment]
So this is a hunch and you should test it, but I guess you have used some relatively heavy effects (translucency/transparency, shadows, etc.) in your picom compared to what your computer can handle. you can try commenting out different part of your picom config and reload picom and see if it improves your experience.

What I can suggest for your Flameshot experience though is actually simple: bind your keyboard shortcut to this:

```sh
pkill picom && flameshot gui ; sleep 1s ; picom &
```

This will kill picom, trigger Flameshot so that you can take screenshot without lag and then when Flameshot is done, it will restart picom. The sleep is because flameshot works with DBUS and therefore the `flameshot gui` does not pit the shell to wait and it will immediately jump to the next command, so the 1 second sleep would give flameshot enough time to fully load before the picom is re-activared.

**Comment by Ewael** [comment]
Alright, this is indeed a nice workaround, thank's a lot for your time. And what a great tool!
