### ISSUE TITLE
Add support for the H265 file extension to save space 

### ISSUE THREAD

**Issue by iMonZ** [flameshot-org/flameshot#1640]
Please add support for the HEIF/HEIC file extension to save space in screenshots
(This file extension is supported on the file Hoster IMGBB too)

**Comment by mmahmoudian** [comment]
Interesting suggestion. While searching I also stumbled upon this:

https://github.com/nokiatech/heif

**Comment by kpcee** [comment]
The next standard and jpg successor will be AVIF or JPEG XL and will certainly be natively supported by Qt. Hopefully something will happen this year. By the way, to bridge the time until then we can use WebP, which is already natively supported by Qt 5.x and can also be displayed by most browsers. The compression is also much better than JPG.

Here is some background info: https://cloudinary.com/blog/how_jpeg_xl_compares_to_other_image_codecs

P.S.
H.265 is the abbreviation for the video codec and not for images.

**Comment by dchakro** [comment]
@kpcee, Nice article about JPEG XL.

> By the way, to bridge the time until then we can use WebP, which is already natively supported by Qt 5.x and can also be displayed by most browsers. 

Btw, WebP is only [partially supported on [MacOS](https://apple.stackexchange.com/a/392466) & [Safari](https://caniuse.com/webp), vs HEIF which is very well supported on Mac.

**Comment by kpcee** [comment]
However, the same page indicates that no browser currently supports [HEIF images](https://caniuse.com/heif). Which makes sense, since HEIF is patented and the browser companies have to purchase an expensive license to use it.

Whereas many browsers support WebP. Also Qt natively supports WebP, whereas support for HEIF would have to be built in separately only to be replaced later by AVIF or JPEG XL. I strongly expect that Qt 6.x will later support at least one of these formats natively.

**Comment by iMonZ** [comment]
The point is about saving pictures as HEIF.

**Comment by borgmanJeremy** [comment]
As of #1680  we allow saving in any supported format.
