### ISSUE TITLE
'Print Selection' option

### ISSUE THREAD

**Issue by layolayo** [flameshot-org/flameshot#1643]
Great piece of software. - Ubuntu 21.04 v0.8.3-2(Debian)

One feature that would really speed up my workflow is being able to print directly to my printer, without having to open up in Image Viewer every time and print from there.

Fingers crossed it is already possible and I just haven't spotted it yet...

**Comment by mmahmoudian** [comment]
I don't think it is implemented. I also think it is a niche use case, and I don't think it becomes priority. What I suggest writing a short bash script to do this automatically. For example you can stitch together these:

```sh
flameshot gui -p ~/Pictures/ready_for_printing

lp -o landscape -o fit-to-page -o media=A4 filename.jpg
```

For more information about the `lp` abd other print commands take a look at these:

- https://www.networkworld.com/article/3373502/printing-from-the-linux-command-line.html
- https://www.cups.org/doc/options.html

**Comment by philus88** [comment]
Would also like to see this on Windows.
I know a similar tool which has the option to STRG+P and directly open the printer prompt.

Please consider this not a niche use case, as i know a lot of people haveing this as "killer" feature.
Coding wise, would this be a big effort ?

**Comment by mmahmoudian** [comment]
@philus88
> Please consider this not a niche use case, as i know a lot of people haveing this as "killer" feature.

The whole idea of keeping the issue open is allow users to vote for the features they feel are really lacking. As you can see so far during the past 8 months you and @layolayo have shown support for this feature.

But fear not, it has been actively discussed to bring in a plugin systems so that users can develop plugins for such post-capture tasks. When that is implemented, it is just a matter of few lines to create a plugin for such actions.

> Coding wise, would this be a big effort ?

I don't know how hard it is, but we tend to only add features that are possible to implement in a cross-platform way. So we should find a solution that works on Linux, Windows and MacOS.

**Comment by mmahmoudian** [comment]
@layolayo 
Shall we close this in favor of #768?

**Comment by layolayo** [comment]
Yeah, only need 1 request for this feature. I needed it again a few days ago...

**Comment by mmahmoudian** [comment]
Closing in favor of #768
