### ISSUE TITLE
screen brightness problem

### ISSUE THREAD

**Issue by Ryder17z** [flameshot-org/flameshot#1649]
the tool is almost useless since i can barely see anything.

This needs to be configurable.

**Comment by borgmanJeremy** [comment]
Can you please provide more details on what you mean? Which screen is too dark?

**Comment by mmahmoudian** [comment]
@Ryder17z from your text all I understand is that "you have a problem with seeing something" but you failed to express the issue clearly. Please provide more details, for example take a photo of your monitor to show us "what is blocking your vision", mention your operating system, Flameshot version. Something that we can figure out the issue and try to fix it.
Thank you for your patience.

**Comment by Ryder17z** [comment]
Whenever I run flameshot (I'll add version info soon) it darkens the screen too much.

**Comment by mmahmoudian** [comment]
Please right-click on the tray icon, go to "Configuration", in the "Interface" tab from middle of the window you can choose the opacity:
![image](https://user-images.githubusercontent.com/390889/120114569-62aab600-c188-11eb-9a05-c0b0dde800b5.png)

**Comment by Ryder17z** [comment]
nevermind. turns out i had an ancient version

**Comment by LinuxOnTheDesktop** [comment]
This issue perhaps needs reopening. Here is why.

> nevermind. turns out i had an ancient version

I have the latest release (which is 11.0.0).

> the higher you go, the more opaque (harder to see) it gets

No. The higher you go, the more _transparent_ it gets. That is: the UI, and the text that I have quoted just now, confounds one with another the respective meanings of 'transparent' and 'opaque'. 'Transparent' means see-through and thus harder to read. 'Opaque' means (in this context at least) solid and so easier to read.

I will create a new issue if you like. Certainly the UI's working needs fixing. For, the present, erroneous wording is very confusing - because it conveys the opposite of what it means to convey.

The fix is easy: in the string 'change opacity of area outside selection' change 'opacity' to 'transparency'.

**Comment by LinuxOnTheDesktop** [comment]
I can see the root or real problem now. It is that by 'opaque' the program means

1) 'blacked out', i.e. not at all visible,

whereas I was reading 'opaque' as meaning

2) not at all transparent, i.e. full visible.

(So 1 is a matter of opacity of background or overlay, whilst 2 is a matter of opacity of original content.)

I suspect that I will not be the only person to construe the opacity at issue in manner 2 rather than 1, i.e. wholly to grasp the wrong end of the stick. So I propose that some clarification be added to the GUI. How about (as against my previous suggestion) the following?  In the string 'change opacity of area outside selection', change 'opacity' to 'opacity (invisibility)'. It is not an elegant solution, but I cannot think of anything better, unless one inverts how the slider's value works.

**Comment by borgmanJeremy** [comment]
imo its clear as is, but I'd like feedback from @mmahmoudian and @veracioux

**Comment by mmahmoudian** [comment]
To me it has been clear since this feature was implemented. Especially because it reads "opacity of area outside selection". So my logic is: the higher the value, the more opaque the overlay outside of the selection should get. So imho the text is clear. Perhaps as a compromise, a tooltip can be added with different wording to further clarify the objective of the spider?

**Comment by LinuxOnTheDesktop** [comment]
> Especially because it reads "opacity of area outside selection"

That does not help. Here is why. That use of 'opacity' is ambiguous in the way that I mentioned. That is, it is ambiguous between (1) blacked out, i.e. not at all visible and (2) not at all transparent, i.e. full visible. (Or, in another formulation that I gave: what is unclear is whether the opacity at issue is that of an obscuring overlay or else that of the original content.)

The tooltip idea might meet the need. Yet, I cannot think of a form of words, for the tip, which would be more informative than 'opacity (invisibility)' but without being too long. Still, if no developer wants to change the displayed (non-tool-tip) text to 'opacity (invisibility)' then you could have that latter text as the tooltip.

**Comment by veracioux** [comment]
I myself have never been confused by the current terminology, but "Dimness of area around selection" is suitable if we decide to change it. A tooltip is also a good idea.

**Comment by LinuxOnTheDesktop** [comment]
I ran into this problem again today - 'this problem' being that I interpreted 'opacity of area outside selection' as referring to the solidity of that area. Consequently I was, again, baffled - until I remembered that what the program _actually_ means is 'opacity of filter outside selection' (see above) or, better (because that last phrase is itself confusing), 'dimness of area around selection'.

**Comment by mmahmoudian** [comment]
I'm not a native English speaker, so I always refer to dictionary:

https://www.merriam-webster.com/dictionary/opacity

The first two definitions are irrelevant to our context, but the 3rd one is:

> an opaque spot in a normally transparent structure (such as the lens of the eye)

So I still believe that the text is clear enough, but I have nothing against changing it to [what @veracioux suggested](https://github.com/flameshot-org/flameshot/issues/1649#issuecomment-1089443548), and use the current text as tooltip.

**Comment by LinuxOnTheDesktop** [comment]
By contrast I _am_ a native English speaker and I know a thing or two about how to write.

**Comment by borgmanJeremy** [comment]
I'm leaving it as is
