### ISSUE TITLE
Flameshot doesn´t start by clicking on launcher icon

### ISSUE THREAD

**Issue by cooperbang** [flameshot-org/flameshot#1695]
**Flameshot version**

Flameshot v0.9.0
Compiled with Qt 5.15.2

**Describe the bug**

Flameshot app doesn´t start if I click on launcher icon.

**To Reproduce**

Open GNOME Activities -> Search for Flameshot app -> click on Flameshot icon.
Result: Nothing happens.

**Expected behavior**

Flameshot app should start.

**System Information**

Fedora 34, GNOME 40.2, Wayland

**Comment by mmahmoudian** [comment]
@cooperbang This is super typical for Gnome users simply because they usually don't have systray enabled as Gnome removed it many years ago. Please read here for how to fix this gnome issue: https://flameshot.org/guide/troubleshooting/#in-gnome-the-flameshot-icon-does-not-appear-in-the-tray

Additionally, the way flameshot works is by opening the app (so that it shows the icon in the tray area), and then click on the tray icon (or alternatively use [the command line commands](https://flameshot.org/advanced/command-line-options/) such as `flameshot gui`)

If these information has solved your situation, please consider closing this issue, otherwise please provide us with the content of the terminal when you run `flameshot gui`.

**Comment by cooperbang** [comment]
Thanks for your answer. I understand but I´m not really happy with it.

I would suggest to adapt Flameshot for current Gnome versions (without using systray).
Installing an extension is not what I want to do... I prefer using Gnome as it is intended to be.

**Comment by mmahmoudian** [comment]
On the same note as you "prefer using Gnome as it is intended to be", Flameshot is currently intentionally designed to work this way.

That said, as far as I can remember, @borgmanJeremy has it in his plans to reduce such dependencies from Flameshot (e.g systray and notifications), but it needs some code refactoring. For the time being you can use Flameshot through CLI and keyboard shortcuts.

Needless to say, any contribution to the codebase is very welcome and any Pull Request is highly appreciated (in case you would like to contribute and sort out this dependency to systray). 🤗

**Comment by mmahmoudian** [comment]
Btw, I searched and couldn't find any feature requests regarding this. I suggest you create a new issue as a feature request and request getting rid of the dependency to systray.

This bug report imho should be closed as this is a "bug" from Gnome (literally every other DE and WM has systray or has a supported way to enable it and Gnome is the only "[ugly black duckling](https://en.wikipedia.org/wiki/The_Ugly_Duckling)" in the herd).
