### ISSUE TITLE
Fullscreen image with annotation

### ISSUE THREAD

**Issue by erlisdhima** [flameshot-org/flameshot#1736]
It would be great if there was a feature to capture fullscreen images and annotate them.

And even better, if you took a fullscreen image but did not annotate it, an option to open the local image and annotate it at a later time.

**Comment by mmahmoudian** [comment]
When you launch Flameshot, you can press <kbd>Ctrl</kbd>+<kbd>a</kbd> (similar in any other application for "select all") to select the whole screen and then you can annotate it.
Additionally we are moving towards a way to let users to save as SVG so that they can further annotate and modify the screenshot with tools such as Inkscape.

Does these address your concerns?

**Comment by erlisdhima** [comment]
Yes, thanks for sharing that! 

It would be very useful if there was a setting though, so you could do it with one shortcut, rather than with multiple actions.

Or maybe a CLI option where you could capture screenshot and select all in one go? 
If thats possible, then it would be easy to assign it to a shortcut.

Hope that makes sense!

**Comment by mmahmoudian** [comment]
@erlisdhima

>  CLI option where you could capture screenshot and select all in one go

That is already possible. I bet you will find this page interesting:
https://flameshot.org/advanced/command-line-options/

Alternatively, you can always use the `--help` in any command or subcommand of flameshot:

```sh
flameshot --help
```

would result in:

> ```
> Usage: flameshot [flameshot-options] [arguments]
> 
> Per default runs Flameshot in the background and adds a tray icon for configuration.
> 
> Options:
>   -h, --help     Displays this help
>   -v, --version  Displays version information
> 
> Arguments:
>   gui            Start a manual capture in GUI mode.
>   screen         Capture a single screen.
>   full           Capture the entire desktop.
>   launcher       Open the capture launcher.
>   config         Configure flameshot.
> ```

or

```sh
flameshot screen --help

```

Which will output:

> ```
> Usage: flameshot screen [screen-options]
> 
> Per default runs Flameshot in the background and adds a tray icon for configuration.
> 
> Options:
>   -n, --number <Screen number>  Define the screen to capture,
>                                 default: screen containing the cursor
>   -c, --clipboard               Save the capture to the clipboard
>   -p, --path <path>             Path where the capture will be saved
>   -d, --delay <milliseconds>    Delay time in milliseconds
>   -r, --raw                     Print raw PNG capture
>   -h, --help                    Displays this help
> ```

**Comment by mmahmoudian** [comment]
@erlisdhima shall we close this issue?

**Comment by erlisdhima** [comment]
@mmahmoudian , I have checked the help commands, however I dont this its possible (unless I'm missing something).

As far as my understanding goes, you need to use `flameshot gui` to be able to launch the gui and then you could `Ctrl+A` to select all and save the screenshot.

I was looking of doing both those actions in one go, but I dont seen an option in `flameshot gui --help` to select the entire screen.
```
Usage: flameshot gui [gui-options] 

Per default runs Flameshot in the background and adds a tray icon for configuration.

Options:
  -p, --path <path>           Path where the capture will be saved
  -d, --delay <milliseconds>  Delay time in milliseconds
  -r, --raw                   Print raw PNG capture
  -g, --print-geometry        Print geometry of the selection in the format W H X Y. Does nothing if raw is specified
  -h, --help                  Displays this help
```

**Comment by mmahmoudian** [comment]
@erlisdhima try `flameshot full` and `flameshot screen` 😉

**Comment by erlisdhima** [comment]
@mmahmoudian yes, but that does not launch the gui where I can annotate, right?
I just tried running `flameshot full --clipboard` but it just saved the image to the clipboard, without being able to annotate.

**Comment by erlisdhima** [comment]
Another workaround would be to try something like this:
```
flameshot gui && sleep 1 && xdotool key ctrl+a
```
But it still is not ideal.

**Comment by mmahmoudian** [comment]
> but that does not launch the gui where I can annotate, right?

You are right, it does not. I thought you don't need to annotate as that step was not mentioned in the order of actions you wrote:

"you need to use flameshot gui to be able to launch the gui and then you could Ctrl+A to select all and save the screenshot."

-------

> Another workaround would be to try something like this:
> 
> ```
> flameshot gui && sleep 0.1 && xdotool key ctrl+a
> ```

I still think that <kbd>Ctrl</kbd>+<kbd>a</kbd> is much safer and ideal to use than scripting it, simply because if for any reason what so ever the `flameshot gui` does not trigger the action in `flameshot` process or there is a bit of delay for any reason that cause Flameshot loading time to be more than 0.1 seconds, your script will push the wrong keystroke. 

I just remembered that there is already a Feature Request (#479) that, if implemented, would let the user to set the size and position of the selected area in `flameshot gui`. When that is implemented, you can then safely define it in arguments and set it to select the whole screen.

Would this satisfy also your need?

**Comment by erlisdhima** [comment]
Yes, if you can set those as parameters in the `flameshot gui` command, then it should be ok, as I can assign that to a shortcut.

Having it as a setting though and being able to change to a different shortcut under 'Shortcuts' tab, is more useful for non-technical people.

I think we can close this issue though, as using `Ctrl`+`a` is fine as well.
Unless you think it should stay open, and plan to do the change.

**Comment by mmahmoudian** [comment]
> Yes, if you can set those as parameters in the `flameshot gui` command, then it should be ok, as I can assign that to a shortcut.

Glad to hear that

> Having it as a setting though and being able to change to a different shortcut under 'Shortcuts' tab, is more useful for non-technical people.

For now the priority is not being user-friendly but rather having the code implemented. When that is done and most of the bugs about it are squished, we can then add a part in the Launcher window for it:

![image](https://user-images.githubusercontent.com/390889/126782308-ff0eee70-76a0-4025-83ba-af0aed1aa806.png)
