### ISSUE TITLE
can't upload to imgur, permission denied 

### ISSUE THREAD

**Issue by mohad12211** [flameshot-org/flameshot#1743]
Flameshot v0.10.0
Compiled with Qt 5.15.2
bug exists both on the stable release and on the latest commit

when I click upload to imgur, I get this error 
![image](https://user-images.githubusercontent.com/51754973/126724690-55ffb048-af27-443c-828d-8dbbc355bf9f.png)

archlinux

**Comment by mohad12211** [comment]
solved after restart (maybe it was a server issue?)

**Comment by mdxe** [comment]
I had the same issue for a couple of days and it also was fixed after a restart of Flameshot.

**Comment by mmahmoudian** [comment]
@mdxe & @mohad12211 hope have you installed Flameshot?

**Comment by mdxe** [comment]
@mmahmoudian I didn't need to re-install it to fix the issue. I just killed the background process and started the Flameshot program again.

**Comment by mmahmoudian** [comment]
@mdxe I understand that, but I wonder if for example snapd has somehow screwed up or AppImage mount got to some problems

**Comment by mdxe** [comment]
@mmahmoudian I use Arch Linux and I don't think that Flameshot is a snap or an appimage... I installed it using pacman, the package manager.

**Comment by mmahmoudian** [comment]
@borgmanJeremy I quickly checked the [imgur API documentation](https://apidocs.imgur.com/#7db0c13c-bf70-4e87-aecf-047abc65686d) and there is no where that we can use this format in out GET or POST requests:`https://api.imgur.com/3/image?title=flameshot_screenshot&description= 2021-09-10_11-43`. As far as I can understand we should use imageHash (`https://api.imgur.com/3/image/{{imageHash}}`) in the requests.

I'm sure I'm missing something here. Do you know what's going on? 

The only hypothesis I have is that this is not our API request but rather the response from the server, and the reason this has happened is because two users have tried to upload image to imgur in the same exact minute and because we use the same title and description and because the imageHash of the second person does not match the imageHash of the first person, imgur returns this error.

If my hypothesis is correct, the easy solution is to add second and millisecond to the description string.

**Comment by mdxe** [comment]
@mmahmoudian It doesn't help, same error, 2 days later

**Comment by mmahmoudian** [comment]
@mdxe do you still have this issue? If you are Arch, would you please try the AUR version (maintained by devs of Flameshot) and see if the issue persists.

**Comment by mdxe** [comment]
I've not seen this problem again... possibly an update fixed it.

**Comment by mmahmoudian** [comment]
@mdxe Thanks. I'll close this issue then.

**Comment by niruvt** [comment]
I faced this issue today. I am using MX GNU-Linux. Installed `flameshot` with `apt-get install`.

```
flameshot -v
Flameshot v0.9.0
Compiled with Qt 5.15.2
```

**Comment by mmahmoudian** [comment]
@niruvt install our latest version and then read the following link:

https://flameshot.org/docs/guide/imgur-help/
