### ISSUE TITLE
Prompt users before uploading to imgur

### ISSUE THREAD

**Issue by JKleinne** [flameshot-org/flameshot#1751]
There's a potential for privacy-related incidents such as hitting "Enter" when opening flameshot from the toolbar. This action captures the screen but subsequently uploads it to imgur, even if it was not the user's intention.

There should be a confirmation required from the user before _**any**_ upload takes place. For some reason, the upload stemming from this action (flameshot toolbar icon -> Hit "Enter") does not show up on the _Latest Uploads_ section, which further corroborate the issue of privacy leaks, as there would be no way to retrieve the `deleteHash` required to remove said image from imgur.

1.
![2021-07-24_11-57](https://user-images.githubusercontent.com/17832326/126874127-1d903a78-3c16-4c45-bd26-c6eda6f056bc.png)
2. "Select an area with the mouse [...] Press enter to capture screen"

**Comment by borgmanJeremy** [comment]
We are changing the upload hotkey this weekend. The delete hash should show up, if not that's a seperate issue

**Comment by mmahmoudian** [comment]
There can be a simple logical (not programming) fix for this: as per suggestion, we ask for confirmation before uploading. In the same confirmation window we can have a checkbox (disabled be default) for "Upload without confirmation". This checkbox's value should be configurable in 3 places:

- the confirmation window
- the gui config
- the `flameshot.ini`

I believe this would be the right way of doing it.

**Comment by borgmanJeremy** [comment]
@mmahmoudian yes I agree with all that.

I looked at getting this into the 10.1 release but it was a bit too complicated. In the interim I disabled hotkeys for uploading.

We can target the v11 release for this feature.

**Comment by mmahmoudian** [comment]
Let's put it for v0.11.0 if it is complicated. I initially thought that because we have all the parts ready in some shape or form, implementing it would be straightforward. But you know best as I'm too novice and rookie in C++ coding 😅

**Comment by vacri** [comment]
Not just a "potential" for incidents - I just doxxed myself to imgur right now due to this problem. I've been using flameshot for quite a while now, and took a screenshot of a purchase receipt page (print to pdf wasn't working). I accidentally clicked the small white blob icon with an up arrow (upload) instead of the small white blob icon with a down arrow (save to disk), saw a window pop up I've never seen before, and _possibly_ closed it before completion (but doubt it).

I didn't know how to get the imgur URL (or even that it was sent to imgur) until I tried it again on a 'safe' screenshot - at which point my copy buffer was replaced. I didn't find a log anywhere of imgur upload URLs for flameshot.

So now, somewhere on imgur, there's a very clear screenshot of my name, email address, phone number, and street address (including google map with a pin), plus what I purchased (I don't care about that bit), all because of clicking the wrong 'white blob' icon. I have no idea how to find that image URL again.

'upload to cloud' _definitely_ needs to be opt-in, either disabled by default, or prompted by default. It's way too easy for someone to dox themselves as it currently stands

**Comment by mmahmoudian** [comment]
@vacri simply right-click on the tray icon, then click on "Latest uploads" and if it is uploaded, you can find the link and even delete it.

![image](https://user-images.githubusercontent.com/390889/129173983-6fcdbf39-1edf-4a58-91d2-fa5be0a109da.png)
![image](https://user-images.githubusercontent.com/390889/129174133-2a557a00-3edc-4c4f-9b3f-64e9a69434fa.png)

**Comment by vacri** [comment]
@mmahmoudian Thanks for the support response - I did find the uploads list after poking around a bit more. I usually left-click on the tray icon so don't play much with the config or right menu button.

In my case, the image is not in the list for me to remove. When the upload popup happened, it took me a moment to realise what it was, then when I realised it wasn't going to offer a confirmation popup, I closed the window early, hoping to kill it before upload. Whether or not it did upload to imgur I don't know, but the image is not in the 'removal' list. Did I kill the window _after_ upload but _before_ the return delete URL from imgur was received? No idea. Hopefully it interrupted the upload and it didn't complete, but I don't know.

Mostly I wanted to mention a case for why this feature needs to be opt-in. Not everyone is going to realise what's going on, or know that they can delete it. Even if they can later delete it, the upload is still public until you remove it.

**Comment by mmahmoudian** [comment]
@vacri the reason I put that comment despite of your "update", to your previous comment was to help users to find the answer if Google brings them to this thread. I'm sorry that it was not direct answer to your concern.

About the upload and closing window, I'm not familiar with the codebase to the extent to tell you if closing that window will interrupt the upload or that window is just symbolic to show the user that something is going on. But in general when writing with API, if one times it very precisely they can break the connection exactly after the upload and before the confirmation arrives. But considering the precision in timing it, I believe it is highly unlikely that your computer has uploaded that image.

Nonetheless, having some sort of confirmation is good, but also it should be configurable as many users predominantly use the upload feature and confirmation dialogue would quickly become disturbing. I believe the confirmation dialogue should be enabled by default but user can disable them via config if they want to.
