### ISSUE TITLE
Portable Windows version?

### ISSUE THREAD

**Issue by vladislav805** [flameshot-org/flameshot#1759]
**Is your feature request related to a problem?**

Hi. Thanks a lot for Flameshot :)

Is it possible to run flameshot (or is it possible to build it) as portable program so that it does not write configs to %appdata%?

For example, so that you can use it on a flash drive on different devices without installing it and with my preferences

**Comment by borgmanJeremy** [comment]
Yea this is available in the release section as a zip file. I'll rename it to be more clear later.

**Comment by vladislav805** [comment]
A portable program, in theory, should not write to the system disk. Instead, it should write in its own directory. Now even the portable version writes the config in %appdata%/Roaming/flameshot/flameshot.ini. Because of this, the settings are not saved when transferring the program to a USB flash drive from one device to another.
![IMG_20210727_100604_308](https://user-images.githubusercontent.com/10882576/127112027-0765211d-d11c-4620-92f1-cd9eac34f55a.jpg)

**Comment by mmahmoudian** [comment]
@vladislav805 I haven't used Windows for years but I remembered this thing that I had on my flash drive back in the day:
https://portableapps.com/apps

I just couldn't find a place to suggest including new apps, but I know they have their way to package the portable software so that all stuff are written on the flash memory.

**Comment by mmahmoudian** [comment]
@borgmanJeremy I agree with @vladislav805 in one point: the path for the config file should be configurable via CLI. I propose adding `-c ,  --conf` to the "Options" so that user can define the [relative] path to the config file.

![image](https://user-images.githubusercontent.com/390889/127124710-26cb180e-86c7-42cb-a341-2aa5485329fd.png)


I also would like to raise concern that the absolute path would probably not work as the drive name will be different on different machines.

**Comment by crimsonduelist** [comment]
> @borgmanJeremy I agree with @vladislav805 in one point: the path for the config file should be configurable via CLI. I propose adding `-c , --conf` to the "Options" so that user can define the [relative] path to the config file.
> 
> ![image](https://user-images.githubusercontent.com/390889/127124710-26cb180e-86c7-42cb-a341-2aa5485329fd.png)
> 
> I also would like to raise concern that the absolute path would probably not work as the drive name will be different on different machines.
> 
> @vladislav805 Would this fulfill your usecase?

was this dropped?
Would this include the cache folder also? i.e. would it be smthing like `-data-dit "Path/to/DataFolder"` and in there
DataFolder/flameshot.ini
DataFolder/cache
