### ISSUE TITLE
Contrl+s to save clipboard to a file name error <2021-08-02_19-32Portable Network Graphic file (PNG) (*.png)>

### ISSUE THREAD

**Issue by zw963** [flameshot-org/flameshot#1796]
**Flameshot version**
Arch linux flameshot-git r1394.5d1a636e-1

**Describe the bug**
When pressing Ctrl + S to try to save to a file, it name like this:

2021-08-02_19-32Portable Network Graphic file (PNG) (*.png)

I consider this is not a vaild filename.

**Expected behavior**
a correct name as release version, like this: `2021-08-02_19-32.png`

**System Information**
Arch Linux latest.

**Comment by borgmanJeremy** [comment]
Thanks for reporting. I suspect this was introduced in #1790.

What DE are you using? I did not observe this on KDE.

**Comment by mmahmoudian** [comment]
I could confirm this on Manjaro KDE using `flameshot-git` AUR (installed few minutes ago):

> Flameshot v0.10.1 (b2ecb70e)
> Compiled with Qt 5.15.2
> linux: 5.10.52-1-MANJARO
> manjaro: unknown

![image](https://user-images.githubusercontent.com/390889/127985136-5dce6ebc-c1d4-4679-9335-bc6ce0e49b31.png)

**Comment by zw963** [comment]
I use Arch + GNOME Wayland on my laptop.

**Comment by veracioux** [comment]
I have identified the cause of the issue on my Arch Linux (i3wm) machine. I had
a `setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)` line in
my config. It was caused by this piece of code:
https://github.com/flameshot-org/flameshot/blob/dc1c53f1c337e46d3c19a38cadc2ba22561b6eaf/src/utils/screenshotsaver.cpp#L119

It was introduced by a commit well before the one that @borgmanJeremy suggested.
In fact, his commit fixed the issue, but if your config got messed up before,
his commit actually exploited that bug :)

Once I removed the line from my config all worked well. Please do the same and
let us know if it got fixed.

Fun fact: the only reason I discovered the bug is because I was testing 
earlier versions of flameshot to debug some issues on my system. Happy accidents :)

**Comment by zw963** [comment]
> setSaveAsFileExtension=Portable Network Graphic file (PNG) (*.png)

After remove above config from ~/.config/flameshot.ini, this issue fixed now.

**Comment by mmahmoudian** [comment]
@veracioux I think it is just the time to implement some sort of an error checker for the config file. If it has too much impact on the performance if ran every time we read the config, we can have it triggered manually by the user, something like `doom doctor` in Doom Emacs.

What do you think?

**Comment by veracioux** [comment]
@mmahmoudian I agree completely. It shouldn't be very difficult to implement. I will leave a more detailed comment on the issue you posted.
