### ISSUE TITLE
CLI flag to pin screenshot right after capture

### ISSUE THREAD

**Issue by dragonlayout** [flameshot-org/flameshot#1834]
**Is your feature request related to a problem?**
No. Just a use case

Before I use flameshot, I used Snipaste on windows(see the gif below) and Snappy on macos, both have a kind of shortcut for take a screenshot and automaticlly pin the image on the screen. 

The action is press down PrtSc, enter screenshot mode, after mouse press down and up choosing the area, the image automaticlly pin on the screen

![](https://i.v2ex.co/2q9kj4OQ.gif)

**Comment by mmahmoudian** [comment]
Such automated sequence of actions are typically done via command line in the software I use (as a keyboard shortcut can be configured to run a specific command). That said, no we don't have a command line flag to pin the selection.

World such command line flag (e.g `flameshot gui --pin`) be satisfactory?

**Comment by mmahmoudian** [comment]
If such cli flag is implemented, I believe #1531 would become even more important.

**Comment by dragonlayout** [comment]
Yes, conmand line flag could be a good option.

**Comment by veracioux** [comment]
Since #1970, you can use the `--pin` option to pin a screenshot after you press the "Accept" button or the `Enter` key. If you also add the `--accept-on-select` option, the action (pin or any other action you specify from the command line) will be applied as soon as you make a selection. Try it :smile:
