### ISSUE TITLE
Screenshots not saving to the directory specified by my config

### ISSUE THREAD

**Issue by Mango0x45** [flameshot-org/flameshot#1847]
**Flameshot version**
```
[thomas@mango-os ~ $] flameshot --version
Flameshot v0.10.1
Compiled with Qt 5.15.2
```

**Describe the bug**
I have my flameshot configuration (configured via the GUI) to save my screenshots to a screenshots directory I have. This has worked for most of the time using this tool but recently (not sure when) it stopped working entirely.

I attempted to create a new config but was confused when it spat out a `flameshot.conf` file instead of a `flameshot.ini` file as described by the README. So I now have both a `flameshot.conf` and `flameshot.ini` in my `~/.config/flameshot` folder.

I tried to dig in the code to see if I could find out what was going out but it appears to me that neither config ever even gets read?

```
[thomas@mango-os flameshot $] fgrep 'flameshot.conf' -r .
./src/config/generalconf.cpp:      this, tr("Save File"), QStringLiteral("flameshot.conf"));
[thomas@mango-os flameshot $] fgrep 'flameshot.ini' -r .
./README.md:You can also edit some of the settings (like overriding the default colors) in the configuration file located at `~/.config/flameshot/flameshot.ini`.
[thomas@mango-os flameshot $]
```

Here is the output of `head -n 11 .config/flameshot/flameshot.conf`
```
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x16\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\xe\0\0\0\f\0\0\0\x11\0\0\0\x14\0\0\0\x15)
checkForUpdates=false
contrastOpacity=188
disabledTrayIcon=true
drawColor=#ff0000
drawFontSize=10
drawThickness=4
filenamePattern=%F_%T
saveAfterCopy=true
savePath=/home/thomas/pictures/screenshots
```

**To Reproduce**
Create a flameshot config and try to set a screenshot save path

**Expected behavior**
I want screenshots to save to my `pictures/screenshots` folder

**System Information**
Arch Linux

**Comment by mmahmoudian** [comment]
@luisalvarado did you install it from Snap? Also please check if you can change the path to a path that does not have . in the name. For example `~/Pictures`

**Comment by luisalvarado** [comment]
> @luisalvarado did you install it from Snap? Also please check if you can change the path to a path that does not have . in the name. For example `~/Pictures`

My fault @mmahmoudian  for not adding that info in. So yes, I am using the snap one

flameshot                v0.10.1+git0.4e406ec  135    latest/stable    borgman-jeremy  -

The above is what snap list says about it. for the path, the issue is that it does not matter what folder I change it to. For example I tried to change it to ~/Pictures as suggested and ended up like this:

https://imgur.com/a/LW9JCa8

Note that on the image, the red area is actually inside ~/Pictures, not inside  the /run/user etc etc folder. So it changes only the 2 last folders. Here is another example of me changing it to ~/Documents:

https://imgur.com/a/Wm47aJx

The 6257 "folder" is made up (Does not exist) and the Software Engineer is not really a folder, but a file inside the ~/Documents folder called Software Engineer

So in a quick glance:

1. The Save Patch cant be changed at all to a correct place
2. It always stays inside the /run/user
3. Does not let me select a FOLDER. Instead I bound to select a file which makes no sense.
4. If I try to Select the ~/Documents folder for example and inside of it there are other folder, it will force me to select one of those folders. If that folder has another folder, it will force me to select that folder, until I get to a folder that does not have another folder, but also has a file. If the folder does NOT have a file, it does not let me select anything.
5. Trying to SAVE the image as a file fails.

**Comment by borgmanJeremy** [comment]
@luisalvarado Snaps have this issue....see #1144

**Comment by luisalvarado** [comment]
Thank you yes, that is what is happening. Let me mark this as duplicate.

**Comment by luisalvarado** [comment]
Okay I cant or dont have access to the duplicate option.

**Comment by mmahmoudian** [comment]
I wonder if the OP ( @Mango0x45 ) also agrees that this is a duplicate as as far as I can understand they compiled from source and didn't install via Snap.

**Comment by Mango0x45** [comment]
Sorry for the late reply, I wouldn't call this a duplicate. The issue here seems to be that @luisalvarado cant just specify a folder to save images in and it forces him to select a file. I was able to select a folder, my images just werent getting saved.

**Comment by luisalvarado** [comment]
> Sorry for the late reply, I wouldn't call this a duplicate. The issue here seems to be that @luisalvarado cant just specify a folder to save images in and it forces him to select a file. I was able to select a folder, my images just werent getting saved.

Thank you correct. And also it looks like it is bound to snap installations only. I tried the deb package and it is working as it should. Although I believe we have the same issue. I can't save the images. Like I can't save them nor copy them with ctrl c and paste them here with ctrl v. It works im other apps like telegram where I do all my work. It pastes correctly but not here nor it saves the file.

**Comment by mmahmoudian** [comment]
@Mango0x45 Thanks for your answer. I reverted my changed to the labels. Can you copy the image? for example by using <kbd>Ctrl</kbd>+<kbd>c</kbd> and then paste in Gimp. Also would you please check if `flameshot gui --raw > test.png` really save it to the `test.png`.

**Comment by mmahmoudian** [comment]
@luisalvarado I think your situation is very different. You **can ** copy, but you cannot paste in certain places. Make sure you have the this optioned disabled before taking the screenshot and copying it and put it in Github or Discord.

![image](https://user-images.githubusercontent.com/390889/131855432-4afc9e0a-58a7-4da5-a999-360911e2b344.png)

**Comment by borgmanJeremy** [comment]
This is solved in the latest snap release (at least during my testing).
