### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by dkasak** [flameshot-org/flameshot#1897]
**Flameshot version**

Flameshot v0.10.1
Compiled with Qt 5.15.2

**Describe the bug**

The keyboard shortcuts (e.g. <kbd>Enter</kbd> for capturing the image or <kbd>Esc</kbd> for exiting the capture are not working for me when I start `flameshot gui`.

**To Reproduce**
Not sure why this is the case, so not sure what the exact steps are to reproduce. However, when I press those keys, they do not perform their stated function. Instead, nothing happens.

**Expected behavior**
I expect the keyboard shortcuts to work.

**System Information**
Arch Linux, running xmonad as a window manager.

**Comment by borgmanJeremy** [comment]
Please post your config file.

**Comment by dkasak** [comment]
```
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x13\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\r\0\0\0\xe\0\0\0\f\0\0\0\x11)
contrastOpacity=188
contrastUiColor=#63121c
disabledTrayIcon=false
drawColor=#0000ff
drawFontSize=8
drawThickness=3
savePath=/home/dkasak/img
savePathFixed=false
showStartupLaunchMessage=true
startupLaunch=true
uiColor=#cf654a

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

Okay, so from this it appears the Enter and Escape or actually *not* the shortcuts I'm looking for. This is mildly surprising since I haven't customized anything apart from the colour of the icons using `flameshot config`.

However, further testing shows that keyboard shortcuts (as listed in the config file) only *sometimes* work: there are runs where they work as expected and runs where they don't work at all.

Given that, it appears it might be some kind of race condition?

**Comment by borgmanJeremy** [comment]
Can you describe a run where they work and do not work? 

IE are you launching from the system tray, cli, shortcut key...If cli what command, if shortcut how is it set up?

**Comment by dkasak** [comment]
I'm running it one of those ways:

1. Running `flameshot gui` from a shell.
2. From a keyboard shortcut (<kbd>Ctrl</kbd>+<kbd>PrtScr</kbd>) which is bound to `flameshot gui` in xmonad's config.

For case 1, I get it working sometimes, I'd say about 40% of the time, without a discernible difference between runs. For case 2, it seems to never work.

**Comment by veracioux** [comment]
Enter is not bound to anything, so the initial message is misleading. (see #1813)
Escape should close the capture, so I don't know what's wrong with that.

I also have an issue that could be related (I use i3 window manager).
- I start flameshot capture (via WM shortcut or CLI, both produce the same behavior)
- I press a WM shortcut that closes the active window
  Now, because flameshot capture overrides the WM, it won't get closed. Instead, the window that was active before flameshot capture was launched will be closed.
- After that, flameshot doesn't accept any shortcuts

After some tinkering, it appears that that happens whenever window focus changes while the capture gui is active.

Could it be that the active window changes between the moment you launch flameshot capture and the moment you press a flameshot shortcut?

So I'd like to ask you to launch flameshot capture and then press the xmonad shortcut you bound to close the active window. If you get the same issue I did consistently, then we may be onto something.

Note: Before doing that, make sure that the active window doesn't contain data that would get lost when it closes.

**Comment by veracioux** [comment]
May be related to #773 and #550 as well.

**Comment by dkasak** [comment]
@veracioux Hitting the keybinding for closing the active window doesn't close the underlying (last active window before launching Flameshot) for me. The xmonad-contrib issue you linked looks like it might be it, though. I'll try testing with the proposed fix there.

**Comment by dkasak** [comment]
Ah, actually, it *does* behave like you described. It just isn't apparent until I close the Flameshot overlay.

**Comment by dkasak** [comment]
And recompiling xmonad-contrib from latest master fixes the issue.

**Comment by veracioux** [comment]
Does PR https://github.com/flameshot-org/flameshot/pull/1958 help with this?

**Comment by DrjavaB** [comment]
I ran `strace flameshot gui` and everything goes well
