### ISSUE TITLE
Add color code in Tool Settings

### ISSUE THREAD

**Issue by loliconshik3** [flameshot-org/flameshot#1905]
In flameshot i can grab color, but can't see color code (like `#000000`) and can't copy him. Why?...

**Comment by mmahmoudian** [comment]
@loliconshik3 that is already implemented in #1869 and is available in the latest build. If you are on an Arch based Linux distro you can install the AUR, otherwise you have to build from source. This will be available in the next released version of Flameshot.

in case you are on Windows or Mac or Debian based Linux distro, let me know and I'll give you instructions on how to get a version with this feature.
