### ISSUE TITLE
Shortcuts do not work on Wayland

### ISSUE THREAD

**Issue by adamant-pwn** [flameshot-org/flameshot#1924]
**Flameshot version**
Flameshot v0.10.1 (7199fd39)
Compiled with Qt 5.15.2

**Describe the bug**
Keyboard shortcuts do not work on Wayland. Resembles #1072, but happens every time, even without alt-tab. Shortcuts work when I try to do it on Xorg session.

**To Reproduce**
`flameshot gui`, then try to use any shortcut (ESC, Enter, Ctrl-c after selection is done, etc).

**Expected behavior**
Working shortcuts.

**System Information**
* Arch Linux x86_64 5.15.0-rc2-1-mainline 
* GNOME 40.4 on Wayland
* NVIDIA GeForce RTX 3070 Mobile, GPU driver: 470.74

**Comment by mmahmoudian** [comment]
@adamant-pwn how do you execute the `flameshot gui`? Directly from terminal or using a keyboard shortcut or left-cluck in the tray icon?

**Comment by adamant-pwn** [comment]
Sorry, I tried it once again now, but couldn't reproduce this behavior. Perhaps is gone after some update? But I still have some problem -- after I run flameshot gui (no matter in which specific way, neither terminal nor shortcut nor tray icon worked) "Enter" shortcut doesn't work. On both Xorg and Wayland.

**Comment by mmahmoudian** [comment]
@adamant-pwn Since few versions ago we have implemented the feature that users can define their own shortcut. The <kbd>Enter</kbd> was also removed as the default shortcut and by default we have <kbd>Ctrl</kbd>+<kbd>c</kbd> to copy to clipboard, <kbd>Ctrl</kbd>+<kbd>s</kbd> to save. You can check all the shortcuts by right-clicking the Flameshot tray icon, select "Configuration", and going to the "Shortcuts" tab.

**Comment by adamant-pwn** [comment]
I tried once more and could reproduce it. So, it depends on what's going on in the background. When I launch some app and in the same time press PrtScr, it launches flameshot which is unresponsive to keyboard shortcuts. Specific examples:
* Launch steam and press PrtScr while it's loading;
* Switch tab in the browser (Opera in my case) and print PrtScr while it's loading.

About Enter -- I still have "Press Enter to capture the screen" shown in the middle of the screen right after I start the gui.

**Comment by mmahmoudian** [comment]
> When I launch some app and in the same time press PrtScr, it launches flameshot which is unresponsive to keyboard shortcuts. 

Yes, this is exactly what #1072 is about. In either case, another application become the one with focus but Flameshot stays in the top. So user would think that Flameshot is unresponsive whereas actually all input is directed to the other application (be it Steam or browser or anything else). I don't know if there is a perfect corss-platform solution here, but perhaps we can check if Flameshot goes out of focus and we get the focus back, or if that is not possible, alternatively, ask the OS to put the focus back to Flameshot few times a second (dirty but functional).

> I still have "Press Enter to capture the screen" shown in the middle of the screen right after I start the gui.

That is a known issue. That message is hard-coded and we are working to make it so that it reads the correct key binding from your config (see #1813).

**Comment by mmahmoudian** [comment]
Shall we close this in favor of #1072?
