### ISSUE TITLE
Get the enter key working like before

### ISSUE THREAD

**Issue by Xenfo** [flameshot-org/flameshot#1934]
Saw this [comment](https://github.com/flameshot-org/flameshot/issues/1924#issuecomment-927813510) and was wondering how I get the <kbd>Enter</kbd> key working like it did before. I have a script that takes the raw PNG from the capture but I can't get it anymore with the new shortcuts.

**Comment by mmahmoudian** [comment]
@Xenfo right click on the tray icon, click on "Configurations", go to the "Shortcuts" tab and see the shortcuts. If you want to change them, simply click on the shortcut. Alternatively you can change you config file which is in `~/.config/flameshot/flameshot.ini` and set whatever you want to "Return".


If this has answered your question, please close this issue, if not, please explain more and include the following information:
- your OS
- Flameshot version 
- your script 
- your Flameshot config file

**Comment by Xenfo** [comment]
I know how to change shortcuts, I was wondering what the <kbd>Enter</kbd> key did before the addition to customize shortcuts. 

- OS: Arch Linux
- Flameshot Version: 0.10.1
- Script: https://gist.github.com/Xenfo/a1ddc9667ce6013548577f66f887cffc
- Flameshot Config:
```ini
[General]
buttons=@Variant(\0\0\0\x7f\0\0\0\vQList<int>\0\0\0\0\x14\0\0\0\0\0\0\0\x1\0\0\0\x2\0\0\0\x3\0\0\0\x4\0\0\0\x5\0\0\0\x6\0\0\0\x12\0\0\0\xf\0\0\0\x13\0\0\0\a\0\0\0\b\0\0\0\t\0\0\0\x10\0\0\0\n\0\0\0\v\0\0\0\f\0\0\0\r\0\0\0\xe\0\0\0\x11)
contrastOpacity=191
contrastUiColor=#001bff
copyAndCloseAfterUpload=true
disabledTrayIcon=false
drawColor=#008000
drawThickness=2
filenamePattern=%a-%b-%d-%Y
saveAfterCopyPath=/home/xenfo/Pictures
savePath=/tmp/
savePathFixed=false
showDesktopNotification=false
showHelp=false
showStartupLaunchMessage=false
startupLaunch=true
uiColor=#008eff

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COMMIT_CURRENT_TOOL=Ctrl+Return
TYPE_COPY=Ctrl+C
TYPE_DELETE_CURRENT_TOOL=Del
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_SELECT_ALL=Ctrl+A
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z
```

**Comment by mmahmoudian** [comment]
@Xenfo The Enter key initially was bound to "save to file". We then later added a feature so that users can customise the shortcuts and to be similar to many other softwares, Ctrl-s was assigned to the "save to file" (and Ctrl-a to "select all screen" and Ctrl-c to "copy to clipboard"), but then Enter was by mistake added to upload to Imgur. We later on realized that this is a mistake and is also a possible security issue (accidentally uploading to Imgur), so we removed that shortcut altogether.


I believe this should answer the question in enough details. If you want to know more, feel free to search in closed issues, pull-requests and commits to get a more accurate picture.

I believe this issue can be closed. If you think there is more to discuss, feel free to reopen it.
