### ISSUE TITLE
Save path reset after reboot

### ISSUE THREAD

**Issue by MohamadKh75** [flameshot-org/flameshot#1985]
**Flameshot version**
Flameshot v0.10.1
Compiled with Qt 5.12.8

**Describe the bug**
I used `/home/mohamadkh75/Desktop` as my save path:
![x](https://user-images.githubusercontent.com/25561893/137620909-327e9301-0bf9-4a7f-842e-f40118476114.jpg)

It works but every time I reboot my machine, I will restore to `/home/mohamadkh75/Pictures/Screenshots`

**To Reproduce**
Just try to change the path and reboot.

**Expected behavior**
To save my path!

**System Information**

```
System:
  Host: ZenBook Kernel: 5.4.0-88-generic x86_64 bits: 64
  Desktop: KDE Plasma 5.18.5 Distro: Ubuntu 20.04.3 LTS (Focal Fossa)
Graphics:
  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel
  Device-2: NVIDIA GP108M [GeForce MX150] driver: nvidia v: 470.57.02
  Display: x11 server: X.Org 1.20.11 driver: modesetting,nvidia
  unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz
  OpenGL: renderer: NVIDIA GeForce MX150/PCIe/SSE2 v: 4.6.0 NVIDIA 470.57.02
```

**Comment by veracioux** [comment]
Can you post the contents of your configuration file (usually `~/.config/flameshot/flameshot.ini`) after you change the save path using the graphical menu?

**Comment by veracioux** [comment]
@MohamadKh75 Thanks.

What if you do the following?

- Run `pkill flameshot`
- Run `flameshot config`
- Change the save path
- Run `pkill flameshot` again
- Run `flameshot config` again

Is the save path correct?

You can also try installing a newer development version from [here](https://github.com/flameshot-org/flameshot/runs/3913212574) (click the "Artifacts" button in the top right corner) and see if the issue is resolved.

**Comment by borgmanJeremy** [comment]
My guess is you installed via snap?

**Comment by MohamadKh75** [comment]
> My guess is this is an issue with our snap. As a test you can download the latest stable release as a .deb from our release page,

Just tried the .deb version and it looks OK!

Thanks!
