### ISSUE TITLE
[Sway] Flameshot doesn't open nor create a screenshot with the console commands, no error shown

### ISSUE THREAD

**Issue by s-iso** [flameshot-org/flameshot#2002]
**Flameshot version**

```
$ flameshot -v
Flameshot v0.10.1
Compiled with Qt 5.15.2
```

**Describe the bug**

Running `flameshot`, `flameshot gui`, does nothing at all, no error messages thrown. Running `flameshot screen -c`, `flameshot screen -p [some_path]`, `flameshot full -p [some_path]` does not save any image anywhere.

**To Reproduce**

- Get the newest sway
- set everything as it says in [this wiki guide](https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md)

**Expected behavior**

Flameshot either opens or shows an error message somewhere in the console.

**System Information**

Arch, using sway git version due to necessary features (no other issues noticed).

**Comment by mmahmoudian** [comment]
@r79 I'm glad it was resolved. Thanks for using Flameshot.

But to put some records straight, I'll briefly explain the history of the project and the current roles:
Flameshot initially started and developed by @lupoDharkael (check the git history for exact dates). As of August 2020 he kindly agreed to form a Gihub organization (https://github.com/flameshot-org) where he shared administrative permissions and tasks with few people including me (full list on [people's page](https://github.com/orgs/flameshot-org/people) but not everyone made their visibility to "public" so you might not see them all). Since then, the main dev has been for over a year @borgmanJeremy, and based on valuable contributions and very good coding practices, @veracioux was also invited to join the dev team. At the moment these two are bearing the weight of coding the software. There are other contributors most of which are active members of [the Slack channel](https://flameshot.org/flameshotworkspace.slack.com/) as well. As for me, I have been doing triage, community management, and as far as I can, trying to guide users or try to narrow down the issue for the devs. I have also done some code contributions but I'm not a seasoned C++ dev and I therefore I have kept it easy and simple :)
