### ISSUE TITLE
Can windows and linux version have different release checks?

### ISSUE THREAD

**Issue by srihariash999** [flameshot-org/flameshot#2072]
**Is your feature request related to a problem?**
For example, the latest 0.10.2 version is only for linux and windows binaries are not updated. But the update checks i guess are still there in windows, meaning I get an alert that update 0.10.2 is released on windows whereas i can do nothing about it. 

So, can this update check be platform dependent ?

**Comment by srihariash999** [comment]
![Screenshot (232)](https://user-images.githubusercontent.com/30948010/141726265-fbda4592-d28f-4536-8249-133b59564774.png)

**Comment by mmahmoudian** [comment]
Thanks for bringing this up and sorry for the inconvenience. The reason for the v0.10.2 was to do a quick hotfix for linux Gnome users, and the reason we have not published any Windows or Mac binaries is simply because we are trying to wrap up for releasing v0.11.0 which brings tons of new features and fixes.

Regardless, having platform-specific might be a good idea but I'm not sure if it is possible or even feasible. I've marked this as Enhancement to see what other devs think.

**Comment by borgmanJeremy** [comment]
It would actually be much easier to just publish all the binaries. I can do that today or tomorrow.

**Comment by borgmanJeremy** [comment]
Okay its published.
