### ISSUE TITLE
Missing shortcuts for macOS

### ISSUE THREAD

**Issue by Idomo** [flameshot-org/flameshot#2138]
### Feature Description

Hi,
It seems like such an obvious thing, but there isn't a shortcut for upload the screenshot to imgur (pressing <kbd>return</kbd> should do that, but it do nothing), only to save it on the computer with <kbd>Cmd + S</kbd>.
Also, it seems like there isn't any way to open the app's settings if I disable the tray icon (it just way too bold and distracting with these colors, you really should make it black/white depends on the background).
It would be nice if even just clicking the app's icon from launchpad would do that.
*I know there is `flameshot config` for terminal config, but my mac doesn't recognize `flameshot` commands from some reason.

Thanks,
Ido.

**Comment by borgmanJeremy** [comment]
Okay lots of separate things here:

- No shortcut for upload
  - This will be fixed in the next release, it was disabled due to a security issue (see release notes for 10.1 for details)
 - No way to change settings without the tray icon
   - Correct at this time you must use the tray icon to change the settings easily
   - You can also manual edit the .ini file, but do so at your own risk
   - When the DBUS PR is merged you will be able to open the config via the cli
  - Icon is distracting
    - If you build from source (main branch) there is an option to compile with a monochrome icon . This will. be used when V11 is released for MacOS

**Comment by borgmanJeremy** [comment]
Sorry didnt directly address the CLI not working. There is another issue open with lots of details, but tldr is the CLI was using DBUS which is not supported on Mac. 

We have a PR with a MASSIVE refactor to solve this. It currently is seg faulting on MacOS so not ready for release yet. This is the main open item before releasing v11

**Comment by Idomo** [comment]
Thanks for the detailing!
So all I can say is that I’m waiting for V11 to be released ASAP (I would contribute, but I doesn’t familiar with C++ 🥲)

**Comment by borgmanJeremy** [comment]
One great way to help is beta test the pre release once it's ready. I can make sure to @ you once it's ready 😁
