### ISSUE TITLE
Having `--reload` argument for the `config` subcommand

### ISSUE THREAD

**Issue by mmahmoudian** [flameshot-org/flameshot#2146]
### Feature Description

At the moment Flameshot does not reload the config file upon change. For instance when I set the `disabledTrayIcon=false` the tray icons didn't reappear, but when I ran `flameshot config --trayicon true` in terminal it popped up. The functionality is there and I think it would be a good addition to the CLI to have something like `flameshot config --reload`.

**Comment by veracioux** [comment]
@mmahmoudian In #2003 the tray icon is affected when the config file changes. In any case, the `--reload` option is unnecessary since changes can be reliably detected using Qt's filesystem watcher. As for applying changes like button colors, thickness, shortcuts etc in the GUI, it's not trivial to implement and therefore not worth it IMO.
