### ISSUE TITLE
The configurator for buttons is disabled

### ISSUE THREAD

**Issue by shufflebits** [flameshot-org/flameshot#2243]
Version v0.10.2 (Qt 5.12.8)
Installed on Ubuntu Mate 20.04

It seems you can no longer configure the available buttons. The checkboxes are all grey.
![image](https://user-images.githubusercontent.com/5569252/149342651-8351e5f7-ff18-4b49-936a-236c50fe67be.png)

**Comment by mmahmoudian** [comment]
I would be thankful if you report potential bugs using the bug Report form. The reason is that you have not provided us the information we need to investigate this issue. Information like the method you have installed Flameshot is missing.

![image](https://user-images.githubusercontent.com/390889/149349991-0abc6398-09eb-4626-9c14-28fba9139dbd.png)

Also, it would be nice if you can provide us your Flameshot config file. You can use the following command to automatically copy your config file and paste it here:

```sh
xclip -selection clipboard ~/.config/flameshot/flameshot.ini
```

**Comment by veracioux** [comment]
@shufflebits Can you try the flameshot version 11 beta (you can download it from github releases)? We have introduced a large number of changes, v0.10.2 feels ancient :D The issue you experienced was probably fixed in the meantime.
