### ISSUE TITLE
Update to QT 5.15.8 to correctly identify Windows 11

### ISSUE THREAD

**Issue by krokofant** [flameshot-org/flameshot#2272]
### Flameshot Version

v11.0.0

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Windows 11 

### Description

Windows 11 can't be detected correctly, so issues might be labeled incorrectly if information is copied directly from the about window.
```
Flameshot v11.0.0 (4680dcd)
Compiled with Qt 5.15.2
winnt: 10.0.22000
windows: 10
```

Seems to be fixed in [QT 5.15.8](https://bugreports.qt.io/browse/QTBUG-99225)

Related Flameshot code: https://github.com/flameshot-org/flameshot/blob/v11.0.0/src/widgets/infowindow.cpp#L107

### Steps to reproduce

Open the About window when running on Windows 11

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/5908498/149758559-e90dea84-44e5-4ce4-a5bc-de5a4fc79894.png)

### System Information

Windows 11 Build 22000.376

**Comment by borgmanJeremy** [comment]
Thanks for reporting. Unfortunately appveyor does not support that version of Qt. In the next release I will complete the transitivity to QT6 which should also fix the issue:

We must use appveyor for the windows release because that's how we tie into the code signing service. 

![image](https://user-images.githubusercontent.com/46930769/149803901-a8a4e033-a454-478c-828c-bd76a6e6801f.png)

**Comment by ZetaoYang** [comment]
Qt 5.15.8 LTS is under commercial license. flameshot uses community license(LGPL), they are available on https://download.qt.io/official_releases/qt/5.15/.

- https://www.qt.io/blog/commercial-lts-qt-5.15.8-released

**Comment by borgmanJeremy** [comment]
Closing this as "wont fix". There is already a different issue for Qt6 which will resolve the problem.
