### ISSUE TITLE
[Mac] - Bug window sliding after capture

### ISSUE THREAD

**Issue by vclerissj** [flameshot-org/flameshot#2287]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
darwin: 21.2.0
osx: 12.1

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

MacOs 12.1

### Description

When I take a screenShot and copy to clipboard, there are a sliding windows

### Steps to reproduce

1. Run the application
2. Take a screen shot
3. copy to clipboard with shortcut (cmd+c)
4. window sliding bug

### Screenshots or screen recordings

https://user-images.githubusercontent.com/18285026/150169330-31984342-42b4-402c-8ff9-1a4abbaf8b0b.mov

### System Information

MacOS 12.1
Monitor : 1920x1080 27" 144Hz

**Comment by borgmanJeremy** [comment]
Im pretty sure this has always been the behavior and is just how MacOS works. Flameshot runs in full screen mode. Whenever your Mac switches off fullscreen mode it plays this animation.

**Comment by mmahmoudian** [comment]
I don't think this is a bug. In MacOS/OSX it has always been so that if you make an application fullscreen it will be automatically moved to a new and dedicated desktop on the right-hand side of the current active desktop. So when the application terminates or goes out of fullscreen, the user will be taken back to the desktop on the left-hand side.

I suggest closing this unless there a way in the API to tell MacOS to skip the animation.

**Comment by avevlad** [comment]
@borgmanJeremy  No! This it's definitely bug! Please, reopen!

**Comment by mmahmoudian** [comment]
@avevlad either we are talking about two different thing (which then you have to explain why this is a bug in your opinion), or this is not Flameshot bug. If you want the animation to go away, read:
https://apple.stackexchange.com/questions/128717/how-to-disable-full-screen-animation-on-os-x-10-9

**Comment by l4kr** [comment]
Can't we do something like windowed fullscreen?
