### ISSUE TITLE
Can't screenshot with Ctrl+Prtsc

### ISSUE THREAD

**Issue by The-Epic-Emerald** [flameshot-org/flameshot#2296]
I am trying to screenshot with Ctrl+Prtsc but it is not working. I am on Arch Linux and I don't want to run `flameshot gui` from the terminal everytime I want to screenshot. How can I fix this?

**Comment by mmahmoudian** [comment]
It doesn't matter on which distro you are, but it does matter on which DE (Desktop Environment) you are. You should create a keyboard shortcut for `flameshot gui` in your shortcut settings. 

Read here:
https://github.com/flameshot-org/flameshot#global

**Comment by The-Epic-Emerald** [comment]
I use i3wm. Is that the answer you are looking for? @mmahmoudian

**Comment by mmahmoudian** [comment]
@The-Epic-Emerald As you know, this github repo is not meant to support projects other than Flameshot, and your question is about i3 configuration rather than Flameshot.

Regardless, the following is the link you should read about your WM and how to define keybindings for various commands and applications:

https://i3wm.org/docs/userguide.html#keybindings

It has been years since I have touched i3, and also it [would be wrong to give fish rather than teach how to fish](https://en.wiktionary.org/wiki/give_a_man_a_fish_and_you_feed_him_for_a_day;_teach_a_man_to_fish_and_you_feed_him_for_a_lifetime), but for the sake of saving everyone's time, add this to your [i3 config file](https://i3wm.org/docs/userguide.html#configuring):

```
bindsym Control+Print exec "flameshot gui" 
```

**Comment by The-Epic-Emerald** [comment]
Thank you so much!
