### ISSUE TITLE
MAC - can't grant access for screen capture to Flameshot

### ISSUE THREAD

**Issue by graspalme** [flameshot-org/flameshot#2331]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)

### Installation Type

AppImage

### Operating System type and version

MacOS 10.15.7 (19H1615)

### Description

When I start Flameshot I get "missing rights to capture screen" - in MacOS preferences "security -> screencapture" the box w/ Flameshot is ticked.

### System Information

10.15.7 (19H1615)

**Comment by borgmanJeremy** [comment]
Remove the permission... reinstall flameshot... add the permission... reboot

**Comment by mmahmoudian** [comment]
@graspalme How did you manage to run AppImage on your Mac?!

**Comment by graspalme** [comment]
> Remove the permission... reinstall flameshot... add the permission... reboot

this worked - thank you

**Comment by dnz-bdeboer** [comment]
I suppose the reboot is critical? Definitely not working when I follow the steps up to reboot.

**Comment by borgmanJeremy** [comment]
Only one way to find out!

**Comment by dnz-bdeboer** [comment]
And yes, works after reboot.

**Comment by KevinsChilli** [comment]
> 

Any idea if this would work in case Flameshoot needs re-grant permissions for screen recording after reboot in order to trigger shortcut dor taking a screenshoot?

**Comment by mmahmoudian** [comment]
@KevinsChilli as far as I understand, you need to do this once for every new version. Which is about 3 times a year or so.

**Comment by KevinsChilli** [comment]
> @KevinsChilli as far as I understand, you need to do this once for every new version. Which is about 3 times a year or so.

Sorry, forgot to mention that I need to change those permissions after every mac reboot. Edited previous post accordingly.

**Comment by borgmanJeremy** [comment]
@KevinsChilli  that sounds like a different issue. Does your computer have management software like JAMF running on it that might reset the permissions?

**Comment by jjc224** [comment]
> Remove the permission... reinstall flameshot... add the permission... reboot

For what it's worth, I tried this several times on the latest version (v12.1.0) and it didn't work. The [docs](https://flameshot.org/docs/guide/troubleshooting/#macos) suggest the same solution. I reinstalled the previous version I was using (v12.0.0) and it worked out of the box without any restart. I'm not sure whether it is a bug in v12.1.0 or my configuration, but ultimately I could not get the permissions working. Flameshot appears to set the permissions on install anyway, so I think you shouldn't need to do anything except restart (if it isn't already working out of the box).

**Comment by mfasold** [comment]
Unfortunately, I was not able to get it to work on Mac Ventura 13.3.

I followed the suggested "IT Recipe" which in my case looked as follows:
1. Goto System Settings -> Privacy & Security -> Screen Recording and Remove permission from installed version of Flameshot
2. Removed installed flameshot `brew remove flameshot`
3. Reboot Mac
3. Install with `brew install --cask flameshot`
4. Start flameshot - get "Untrusted app warning"
5. Goto System Settings -> Privacy & Security. In the Security section it writes "Flameshot was blocked
   because it is not from an identified developer"
   Click "Open Anyway" and verify with password. Click Open.
6. The dialog "Flameshot would like to record computer screen and audio" opens. <img width="471" alt="Screenshot 2023-04-03 at 14 11 14" src="https://user-images.githubusercontent.com/726676/229512873-fd344b3c-c8b5-411c-94c3-9c4124a6e9fa.png"> 
  Click "Open System Settings".
7. In the opened settings, move the respective toggler to the right.
8. Dialog "flameshot” may not be able to record the contents of your screen until it is quit."
   Select "Quit and Reopen"
9. At this point we are back to 6, so the same dialog opens. So I just...
10. Reboot.
11. Start flameshot. Again back to 6.

However, I am not able to escape the loop.

**Comment by achernya** [comment]
I'm similarly in an infinite loop, but I'm using MacPorts to install flameshot, and launchd to start flameshot

```
$ cat ~/Library/LaunchAgents/flameshot.plist 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>org.flameshot.gui</string>
    <key>ProgramArguments</key>
    <array>
        <string>/opt/local/bin/flameshot</string>
    </array>
    <key>KeepAlive</key>
    <true/>
</dict>
```

I can't get the permissions to stick on Ventura, but they were fine in Monterey. If I launch flameshot directly from the terminal it works fine.

**Comment by jerryno6** [comment]
I'm also facing the same problem, **flameshot** keeps asking for permission even when I follow the steps from the document: Remove permission, Click + button to add flameshot to the screen record permission, restart the PC, open flameshot again and it does not work.
I'm using MacOS **Ventura 13.4 (22F66)**

![flameshot](https://github.com/flameshot-org/flameshot/assets/4426269/e8b0a857-4553-48d0-a398-f695d3f2615d)

**Comment by mmahmoudian** [comment]
@jerryno6 try:
1. removing
2. reboot
3. add
4. reboot
5. run Flameshot

**Comment by jerryno6** [comment]
> @jerryno6 try:
> 
> 1. removing
> 2. reboot
> 3. add
> 4. reboot
> 5. run Flameshot

Thanks I followed these steps and it works like a charm.
1. Close flameshot (click on the Flameshot icon in taskbar, and choose 'Quit' to close it completely).
2. In Screen Recording section of Settings, remove the **Screen Recording** permission for flameshot by clicking on the '-' Button
3. Restart the PC
4. Go to settings, Screen Recording permission, click '+' button and choose Flameshot to add permission for it.
5. Restart the PC
6. Run Flameshot
