### ISSUE TITLE
Zooming pin in and out does so at different rates

### ISSUE THREAD

**Issue by Semnodime** [flameshot-org/flameshot#2341]
### Flameshot Version

v0.10.2 (c4081c6)

### Installation Type

AppImage

### Operating System type and version

Linux Mint 20.1 Cinnamon

### Description

Scrolling in and out in a pin does so at different rates.
Scrolling to make it smaller is faster.

Only happens when the pin has been zoomed quite large already.

### Steps to reproduce

1. Take Screenshot
2. Pin it
3. Scroll to make it really big
4. Scroll to make it a bit smaller again
5. See error: Sudden jump to be way smaller

### Screenshots or screen recordings

None

### System Information

s.a.

**Comment by borgmanJeremy** [comment]
Ha! Good find.

**Comment by mmahmoudian** [comment]
While experimenting with this, I realized you don't need to make the pin very large to get the effect. any pin size would do. To make this extremely reproducible, I wrote the following bash to scroll up and down 5 steps at a time for 10 rounds:

```sh
#!/usr/bin/env bash

round = 1

sleep 3s

for i in {1..10}
do
    echo ${i}

    xdotool click --repeat 5 --delay 20 5
    xdotool click --repeat 5 --delay 20 4

    sleep 1s
done
```

In ideal world the size of the pin image should stay the same after scrolling up and down equal number of times and steps. So I created a large checkerboard pattern using https://eleif.net/checker.html and pinned one area and ran my code:


https://user-images.githubusercontent.com/390889/151700657-476a7479-fb1a-48d3-89bb-92c9fff0e120.mp4

**Comment by borgmanJeremy** [comment]
@mmahmoudian do you have any fractional scaling?

**Comment by mmahmoudian** [comment]
> @mmahmoudian do you have any fractional scaling?

No, all monitors are 100%

**Comment by borgmanJeremy** [comment]
So this is caused by rounding errors in the integer math. When the size is changed we add 15 to the width and the height. Then we ask Qt "please find resize the existing image to the new size while preserving the original aspect ratio". This is a destructive operation in the sense that it is nonlinear. So when you run it in reverse you end up with a different size even if you just increment once and decrement once. 

Once solution is to simply add or subtract by a multiple of the GCD, but i dont think this will be nice for very oblong images.

The other solution I can think of is to store the original pixmap and original size. Then each mouse event will increment and decrement a counter. The counter will apply to the original pixmap each time. This will keep the operation linear.

**Comment by Semnodime** [comment]
@borgmanJeremy I harmonize with the solution of storing a counter: incrementing and decrementing it can easily be made an exact and thus fully reversible operation.

----
As a second remark:
While not having looked into the code, the current difference appears to be quite large to be related to rounding errors only and thus reminds me of a common error when dealing with fractional units:
IMHO, it is not too unlikely, that reversing an zoom-in operation (like adding 15% to 100 --> 115) has been implemented simply by subtracting the previous fraction (remove 15% from 115 --> 97.75), irrespective of the new (and larger) reference.
Zooming in and out once will lead to an image that is actually 3.75% smaller than the original. Doing so repeatedly, and the image will obviously shrink approaching zero area.

**Comment by borgmanJeremy** [comment]
@Semnodime My first guess was that it was related to adding and removing percentages, but its actually not using percentages. https://github.com/flameshot-org/flameshot/blob/1cc5a2629246d3c5cbfe135cdb5f375403aeb0c9/src/tools/pin/pinwidget.cpp#L79

I'll get to this in a few days if no one else does. I want to leave it open for new contributors for a few days since it should be straightforward.

**Comment by AndreaMarangoni** [comment]
I'll take a look at this if you don't mind @borgmanJeremy

**Comment by borgmanJeremy** [comment]
@AndreaMarangoni sure, thanks!

**Comment by AndreaMarangoni** [comment]
PR #2378
@Semnodime if you could test my PR that would be great!
