### ISSUE TITLE
Get  config error when use new freshed config.

### ISSUE THREAD

**Issue by zw963** [flameshot-org/flameshot#2359]
### Flameshot Version

 ╰─ $ flameshot --version
Flameshot v11.0.0 ()
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch linux

### Description

This issue not upgrade issue, it can be reproduce on refresh flameshot version 11.

### Steps to reproduce

1. Start flameshot
2.  Goto config, change Preferred save file extension to png
3. save and quit flameshot
4. start flameshot again
5. goto config, change preferred save file extension to blank. (i want to select by flameshot automatically)
6. try do screenshot, get this error.

### Screenshots or screen recordings

![Uploading image.png…]()

### System Information

1. Arch linux
2. no
3. Gnome + Wayland

**Comment by borgmanJeremy** [comment]
Thanks for the step by step directions, I confirmed the issue.

**Comment by vozdeckyl** [comment]
Hi,
the issue seems to be caused be an empty string in `saveAsFileExtension` setting variable.

It seems to be solved by deleting this line:
https://github.com/flameshot-org/flameshot/blob/03af9d807cc85b94cb29644966cd9fa8d845281f/src/config/generalconf.cpp#L471
which prevents users from selecting the empty string.

Can I create a pull request for this?

**Comment by borgmanJeremy** [comment]
@vozdeckyl sure if you have tested that it resolves the issue please submit a PR.
