### ISSUE TITLE
Translation Update - tr - 04022022

### ISSUE THREAD

**Issue by bkrucarci** [flameshot-org/flameshot#2363]
### Feature Description

Hello,

I translated the missing Turkish strings in Flameshot v11.0.0
I used the old fashion way using Qt Linguist.
Please download the up-to-date Turkish file : https://mega.nz/file/VHBHWAib#P4_Z4xUNd5g4LjYmrj6KKq7qYNNXQ0tt1Jb2ZdvgwYk

Thanks for the software, I fond of in-app screenshot editing :) Keep up the good work.
Regards,

**Comment by borgmanJeremy** [comment]
Hello, Thanks for going through the work to translate it. However, we do not commit .qm files to the repo. We only commit the .ts files. Additionally it would be much easier for us if you submitted the translation through weblate otherwise I have to resolve nasty merge conflicts with files written in a language I dont speak or read :)

**Comment by mmahmoudian** [comment]
@bkrucarci If you are strongly against using Weblet, I can spend some time and do copy-pasting as I can read a bit of Turkish and Azeri. But it would be good if you yourself can do it to:
1. Get the credit for your efforts
2. There are some edge-cases and I don't know enough of Turkish to be able to make the correct choice there

**Comment by bkrucarci** [comment]
@mmahmoudian First of all, you should delete this guide or update it. https://github.com/flameshot-org/translation-instruction/blob/master/Traditional_Translation_Way.md
Actually I tried weblet first :) But it said "Closed for translations" or something like that. I will give Weblet a try. I have account on it, no problem.
