### ISSUE TITLE
Ctrl + s no longer works to save

### ISSUE THREAD

**Issue by agustaf9** [flameshot-org/flameshot#2365]
### Flameshot Version

Flameshot v11.0.0 (-)
Compiled with Qt 5.15.2

### Installation Type

User repository (AUR)

### Operating System type and version

LSB Version:	1.4 Distributor ID:	EndeavourOS Description:	EndeavourOS Linux Release:	rolling Codename:	rolling

### Description

In addition to Ctrl + c not working to copy the image to the clip board #2322, CTRL + s no longer saves and closes the capture.

### Steps to reproduce

1. flameshot gui -p ~/Pictures/Captures
2. Select a region
3. Press Ctrl + s
Expect it to save to file, close the capture interface, and send a system notification but nothing happens

### System Information

LSB Version:	1.4
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	rolling

Using Xorg and i3WM

**Comment by mmahmoudian** [comment]
I guess this is because you missed the release note about the final actions. You can read more about it in https://flameshot.org/docs/advanced/commandline-options/#final-actions

The gist of it is that you used `--path` and now in v11 this is among the final actions, therefore the faith of your screenshot is determined when you provided `--path` that you want to save the file, so you just need to press enter after selecting the area to save it.

Does this answer your question?

**Comment by agustaf9** [comment]
That fixes it, thanks!

**Comment by D3SK3R** [comment]
So that means that if I only run flameshot gui, I should be able to just use it like I used to, right? But even with this command, It shows me the ctrl + c button, when I press it, it exits flameshot like it should, but the capture isn't in my clipboard, it simply doesn't work. I also tested using the --clipboard option.
Tested on flameshot and flameshot-gui from the manjaro official repo, Linux 5.15.19

**Comment by mmahmoudian** [comment]
@D3SK3R 
I myself am on Manjaro KDE Xorg and I use the AUR (on 3 different computers) and don't have this issue. Of course there can be a bug on our side regarding sending to clipboard, or it can an issue on your side, or it can be an issue with Qt. Please open a bug report and fill the form completely.

What ever it is, your issue has nothing to do with this thread. This thread is about missing the copy and save and upload buttons **and** not being to use the shortcuts which is because of the final actions.

**Comment by joleeee** [comment]
This new feature is great when i both want to save and copy to clipboard. However, a lot of the time i only wanna copy it, without saving. Do i have to set up separate binds then? I currently have `M-S` bound to `flameshot gui -p $HOME/Pictures/Screenshots`, and was very comfortable pressing either `^c` or `^s` to copy or save my screenshot, respectively.

**Comment by borgmanJeremy** [comment]
If you bind it to flameshot gui without additional arguments you can choose

**Comment by mmahmoudian** [comment]
Basically what Jeremy mean is that put that path in the config file and only call `flameshot gui`. When you do that, pressing Ctrl+s would save in the path in the config and Ctrl+c would copy, but it doesn't do both. If you want a combination of final actions, you should specify them in the CLI
