### ISSUE TITLE
Quickly copying a screenshot after taking one results in capturing the fullscreen

### ISSUE THREAD

**Issue by aarav2you** [flameshot-org/flameshot#2394]
### Flameshot Version

Flameshot v0.10.2

### Installation Type

User repository (AUR)

### Operating System type and version

5.15.16-1-MANJARO

### Description

After taking a screenshot then quickly copying it with `^+C` may sometimes result it in copying the full screen

### System Information

kWin from kde
x11

**Comment by mmahmoudian** [comment]
Well, two points:
1. The latest Flameshot in AUR is `v11.0.0 (bcb4041e)`. Please consider updating
2. it is impossible to install from AUR and don't have the commit hash in the version (check the example above).

That said, i tried to reproduce it, but with that limited information you provided, it is impossible. Please fill the **steps to reproduce** detailed enough so that we can reproduce the issue.
