### ISSUE TITLE
Text alignment changes to right-aligned after finishing

### ISSUE THREAD

**Issue by j-tai** [flameshot-org/flameshot#2410]
### Flameshot Version

Flameshot v11.0.0 ()
Compiled with Qt 5.15.3
linux: 5.15.15-76051515-generic
org.kde.Platform: 5.15

### Installation Type

Flatpak from Flathub

### Operating System type and version

Pop!_OS 21.10

### Description

After finishing editing text, the text becomes right-aligned.

### Steps to reproduce

1. Start a screenshot and select a region
2. Write text with multiple lines
    → The text is left-aligned by default, as expected
3. Click outside the text box to finish editing
    → The text becomes right-aligned

### Screenshots or screen recordings

https://user-images.githubusercontent.com/45131430/153521050-a7c50cc5-d3fd-4cef-87cc-c41d09ee4b9f.mp4

### System Information

Pop!_OS 21.10

Reproducible with 1 or 2 monitors

GNOME 40.4.0, Xorg

**Comment by mmahmoudian** [comment]
confirmed!

**Comment by joekrukosky** [comment]
When will this be fix be released? I have version 11.0.0 and it's not fixed yet. Check for updates says it is latest.
Pop!_OS 22.04
Compiled with Qt 5.15.3
linux: 5.17.5-76051705-generic
ubuntu-core: 20

**Comment by mmahmoudian** [comment]
@joekrukosky Of course you could do this yourself and get to the answer pretty fast, but anyways, here is the answer:

Literally right above your comment we can see that the fix was merged on Feb 23rd 2022:

![image](https://user-images.githubusercontent.com/390889/170822233-b2793c57-8f91-452e-9765-e32289b8f847.png)

then we can go to [the release page](https://github.com/flameshot-org/flameshot/releases) and check when the latest version was released. As you can see, it was released on Jan 15th 2022: 

![image](https://user-images.githubusercontent.com/390889/170822319-79942ad3-a924-439c-9ea6-b7ab02039df8.png)
 
Therefore you should either wait for the next release whenever it may be, or install through [our nightly builds](https://flameshot.org/docs/installation/development-build/). Remember that the nightly builds are considered as Beta and are not stable. Therefore you might want to keep it updated to get the gradual fixes.

**Comment by joekrukosky** [comment]
Thanks @mmahmoudian for the clarification. I did realize the issue was fixed, I was just trying to find out when it would be put into a release.  I didn't know about the nightly builds though.  I will give that a try. Thanks again.
Joe
