### ISSUE TITLE
Tool size does not respond to change

### ISSUE THREAD

**Issue by funnym0nk3y** [flameshot-org/flameshot#2462]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

winnt: 10.0.19043

### Description

When chaning the tool size and trying to draw something the tool size is not the size I set it to. 

### System Information

OS version see above.

Monitor setup: One 1680*1050 on the right and one 3840*2160 on the left

**Comment by OverdueCEO** [comment]
I've got the very same issue on Arch repo installation. It definitely worked few months ago. No matter what I set it to be it's still the same size when trying to draw.

**Comment by borgmanJeremy** [comment]
I cannot replicate this in Arch

**Comment by OverdueCEO** [comment]
I just tried flameshot on VM with fresh Garuda-XFCE4 and popup slider is not working here as well. Wanted to try on VM with Alma on KDE (basically a centos) and also installed from repo, but it turns out there is no popup menu on that configuration and in `flameshot config` in buttons section the "+" or "-" **do not even exist**.

Everything done on my Arch which is also xfce4 if that matters. Using nvidia proprietary driver on 1050Ti. I also tried disabling / changing default DPI in "Appearance" settings (because it strongly affected flameshot about a year ago ) but it had no impact.

**Comment by OverdueCEO** [comment]
**Flameshot Version:** 
Flameshot v11.0.0-4 (-)
Compiled with Qt 5.15.2

**Installed using:** 
`pacman -Syu flameshot`

**xfce4-about:**
ver. 4.16

**OS:**
Arch Linux 5.16.15-arch1-1

**OS-2:**
Garuda Linux (xfce4) 5.15.31-1-lts, everything else the same


PS: turns out Alma "newest" version is Flameshot v0.6.0 so I consider it irrelevant.

**Comment by mohad12211** [comment]
can also confirm, both on arch (latest commit) and mint (v11.0.0)
using the slider on the left doesn't change it, using the mouse scroll wheel or '+' or '-' buttons work with no problems

**Comment by borgmanJeremy** [comment]
This should be fixed by #2530 . I misunderstood the issue at first.

**Comment by mohad12211** [comment]
Yeah fixed by #2530, can be closed, thank you

**Comment by borgmanJeremy** [comment]
#2533 Fixed another issue too.
