### ISSUE TITLE
Cannot mix incompatible Qt library (5.15.2) with this library (5.15.3)

### ISSUE THREAD

**Issue by se7en-x230** [flameshot-org/flameshot#2473]
### Flameshot Version

flameshot 11.0.0-4 

### Installation Type

User repository (AUR)

### Operating System type and version

arch dwm 

### Description

still worked yesterday 

### Steps to reproduce

run flameshot

### System Information

linux

**Comment by mmahmoudian** [comment]
Few points:
1. nothing has changed on our side since the last commit (a6144df) which was 12 days ago, According to [the Arch repo](https://archlinux.org/packages/extra/x86_64/qt5-base/) the `qt5-base` was updated today to version `qt5-base 5.15.3+kde+r133-1`
2. the AUR's version number is always accompanied with the git commit hash. The one you provided is just the latest release number and hence invalid for AUR
3. regarding the "System Information": "linux" is almost your "operating system" type and is clearly invalid answer for this section.


All these said, based on [this](https://github.com/qutebrowser/qutebrowser/discussions/6447), [this](https://discuss.getsol.us/d/7015-cannot-mix-incompatible-qt-library-5152-with-this-library-5153/21), and [this](https://github.com/ros-visualization/rviz/issues/1646) my guess is that you have multiple Qt versions on your system or you have partially updates your OS.


This issue, as clearly explained in the error message, is not something that we can solve on our side. my suggestion is to remove `flameshot-git` with you AUR helper, clean the cache and install it again. For instance if you are using `paru` try

```sh
paru --remove flameshot-git
paru --sync --clean --clean
paru flameshot-git
```

**Comment by se7en-x230** [comment]
> Few points:
> 
> 1. nothing has changed on our side since the last commit ([a6144df](https://github.com/flameshot-org/flameshot/commit/a6144df367bbb7ba6174d45e00164ac79080f9c7)) which was 12 days ago, According to [the Arch repo](https://archlinux.org/packages/extra/x86_64/qt5-base/) the `qt5-base` was updated today to version `qt5-base 5.15.3+kde+r133-1`
> 2. the AUR's version number is always accompanied with the git commit hash. The one you provided is just the latest release number and hence invalid for AUR
> 3. regarding the "System Information": "linux" is almost your "operating system" type and is clearly invalid answer for this section.
> 
> All these said, based on [this](https://github.com/qutebrowser/qutebrowser/discussions/6447), [this](https://discuss.getsol.us/d/7015-cannot-mix-incompatible-qt-library-5152-with-this-library-5153/21), and [this](https://github.com/ros-visualization/rviz/issues/1646) my guess is that you have multiple Qt versions on your system or you have partially updates your OS.
> 
> This issue, as clearly explained in the error message, is not something that we can solve on our side. my suggestion is to remove `flameshot-git` with you AUR helper, clean the cache and install it again. For instance if you are using `paru` try
> 
> ```shell
> paru --remove flameshot-git
> paru --sync --clean --clean
> paru flameshot-git
> ```

Thanks for your fast reply.

System is multiple Arch/DWM windows manager system while my arch/KDE system is working as expected.

I don\t have multiple qt5-base packages installed. Only the 5.15.3
I did reinstall/removed flameshot and using the official arch package.
And I downgraded qt-base to 15.2 
Without result.

I assume it has something to do with the windows manager (DWM) side of things.
My setup was working for many month and I have not changed anything in my flameshot setup.

I am out of ideas and thankful for any idea how to solve this problem

**Comment by se7en-x230** [comment]
Looks like a problem with qt5-base as I get the message with other qt based apps as well.
And I found other forum entries on arch based distros having the same problems across multiple apps.

**Comment by se7en-x230** [comment]
Reinstalling `qt5-styleplugins` fixes the problem here

**Comment by mmahmoudian** [comment]
That's odd. Thanks for reporting the solution 👍🏼

**Comment by kohane27** [comment]
I have the same problem with just the later version of qt lib.

`pacman -Rns qt5-styleplugins` then `yay -S qt5-styleplugins` solved it for me.
