### ISSUE TITLE
Copy to clipboard not working Windows 11

### ISSUE THREAD

**Issue by jayjr1105** [flameshot-org/flameshot#2480]
### Flameshot Version

Flameshot v11.0.0 (ad1bf28)
Compiled with Qt 5.15.2
winnt: 10.0.22000
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Windows 11 21H2

### Description

Worked fine yesterday, today at work the Ctrl + C or Copy to clipboard button does not in fact copy the screenshot to clipboard.

### Steps to reproduce

Take screenshot with PrtSc and hit Copy button

### System Information

Windows 11 21H2 (OS Build 22000.556)

**Comment by jayjr1105** [comment]
Okay I apologize for creating the issue but I did resolve it.  Windows apparently doesn't like the "Use JPG format for clipboard (PNG default)" setting.  Maybe still issue worthy?

**Comment by jayjr1105** [comment]
Also, when adding a text box in Windows it appears to always right align the text after saving the screenshot where it is left aligned while typing it.

**Comment by mmahmoudian** [comment]
Thank you for putting time into reporting these, but both issues (JPEG and alignment) are duplicated, plus the alignment is already resolved. I'm going to close this issue.

**Comment by philipjanbaxta** [comment]
copy is not working because of that settings, reinstalled for many times. how about to remove that options.

**Comment by mmahmoudian** [comment]
@philipjanbaxta Thank you for your comment but:
1. you commented in a closed issue (it will not be checked actively by devs)
2. you commented in a duplicated issue (it reduces the chance of getting checked for obvious reasons)
3. removing a feature just because it has a bug is not a correct way to go.
4. follow the development in #2322 but please do not comment if you don't have anything new information to add. Thanks.
