### ISSUE TITLE
No editing window in Ubuntu 22.04

### ISSUE THREAD

**Issue by thomas2045** [flameshot-org/flameshot#2572]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2
linux: 5.15.0-27-generic
ubuntu: 22.04

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 22.04

### Description

I could perfectly use Flameshot in Ubuntu 21.10. Usage:
I clicked on the tray icon and "Take Screenshot". Then I could select the area and edit in it, and safe the edited screenshot.

After the update to Ubuntu 22.04 there is a problem:
I click on the tray icon and "Take Screenshot" - A scrrenshot of the FULL screen is taken immediately (I did not want to do this). After that a window with the screenshot and a "settings" button opens. Via this settings button I can select to take a screenshot only of a selected area. BUT: Also no editing possibility like in the past, it just takes a screenshot of this area and saves it.

I did not find any way in settings, help... to configure it like I want to use it. I need to take screensots of an area as default (never of the full screen) and I need to edit the screenshot. 

Is there any way to use it like this in Ubuntu 22.04? Should I install another version or so?

### System Information

Ubuntu 22.04
Wayland
Gnome

**Comment by borgmanJeremy** [comment]
When the prompt from gnome comes up you should be able to hit "share" to share with flameshot. This is an intentional change from gnome.

**Comment by thomas2045** [comment]
Ok thats a very unlogical process. So I need to make a full screen screenshot which I DO NOT WANT to make, then press "share" (which I do not want to do), and THEN I can get the original function of Flameshot back.

Any better idea how to use it? Cause this is so complicated, that I can almost draw the arrows quicker when I use GIMP to draw in screenshots made with the built-in screenshot tool.

**Comment by borgmanJeremy** [comment]
No, complain to gnome. We had no involvement in this

**Comment by mmahmoudian** [comment]
@thomas2045 we have very clearly explained this on our website. Please read it carefully and if you want to complain, we have provided links to the correct places in there too:

https://flameshot.org/docs/guide/wayland-help/#gnome

**Comment by thomas2045** [comment]
@mmahmoudian 
thanks for the more helpful explanation. I am just a regular user, and did not expect this to happen when updating Ubuntu. I did not even know, that Gnome can block a screenshot tool. 

I looked a bit to find a very simple photo editing software, which could draw the arrows etc. I normally draw with flameshot. I did not find one so far. So I wonder if I could open a file (screenshot taken by the system tool or so) and open it in flameshot, to edit it there? Maybe even some "auto opening a file" could be nice (new file appears in the screenshot folder - automatically opens in flameshot to edit?
Because the most important feature of flameshot is in my opinion the easy editing, and copying to the clipboard - not so much the process of taking the screenshot.

**Comment by mmahmoudian** [comment]
@thomas2045 
> I wonder if I could open a file (screenshot taken by the system tool or so) and open it in flameshot

There is already an open issue for that. It might also get addressed via our upcoming plugin system.

> I did not even know, that Gnome can block a screenshot tool.

Gnome has not blocked Flameshot, they have blocked all screenshot applications out there. There are discussions to add a checkbox to the window so that users can tell gnome to always allow that particular software. Until then, you have the following choices:
1. Tolerate the current behaviour
2. Install something else instead of Gnome (e.g [KDE](https://www.linuxcapable.com/install-kde-plasma-desktop-on-ubuntu-22-04-lts/) or [Xfce](https://www.linuxcapable.com/how-to-install-xfce-desktop-ubuntu-22-04-lts/))
3. Install another OS (e.g [kubuntu](https://kubuntu.org/), [ElementaryOS](https://elementary.io/), or [Pop!_OS](https://pop.system76.com/))

Remember, Gnome is just a software, like any other software you can install another Desktop Environment and then remove Gnome. You don't need to change your life because Gnome dictates that to you.

**Comment by thomas2045** [comment]
@mmahmoudian
thanks for the explanations.

I just installed KDE on my old testing laptop (replacing Gnome - Ubuntu 22.04 was there installed already), and well - Flameshot works again as before ;)

But my main work computer has to stay longer on Ubuntu 20.04, I need a lot more testing to feel comfortable with a change like this (I don't care about the looks, but it must run absolutely stable).
