### ISSUE TITLE
Flameshot is broken on the latest version of Manjaro Cinnamon

### ISSUE THREAD

**Issue by pempek** [flameshot-org/flameshot#2724]
### Flameshot Version

Flameshot 11.0.0-5

### Installation Type

User repository (AUR)

### Operating System type and version

Manjaro Cinnamon 

### Description

When activating flameshot, the screen first turns off, then turns on and off continuously.

### Steps to reproduce

1. run flameshot
2. problem occurs

### Screenshots or screen recordings

I'm so sorry in advance for my dirty screen lol

https://user-images.githubusercontent.com/36126710/175823828-71841088-6e46-454f-baec-841802a7bb74.mp4

### System Information

System:
  Kernel: 5.15.49-1-MANJARO arch: x86_64 bits: 64 compiler: gcc v: 12.1.0 
Desktop: Cinnamon  v: 5.4.2 tk: GTK v: 3.24.34 dm: LightDM 
Distro: Manjaro Linux base: Arch Linux

**Comment by ruiztulio** [comment]
Hi,

I'm having the same issue

**Flameshot Version**
Flameshot 11.0.0-5

**Installation Type**
User repository (AUR)

**Operating System type and version**

Kernel: 5.10.124-1-MANJARO x86_64 GNU/Linux
Distro: Manjaro
Desktop: Cinammon-Desktop 5.4.0
Graphics card: NVIDIA Corporation GP104 [GeForce GTX 1070]
Nvidia driver: 515.48.07
lightdm 1.3.0


Unlike the OP I cannot even open it because all the screens goes black (2 monitors)

If there is anything else to add or test, please let me know.

Regards.

**Comment by mmahmoudian** [comment]
Well, both of you are definitely not installing it from AUR. Update your flameshot to the most recent AUR which is in version 12.0.0.

Please make sure you provide us with correct information as they are necessary for us to try to replicate and resolve the issue. I'm closing this issue as the information provided is definitely wrong.

**Comment by pempek** [comment]
My bad. You're correct, it's actually from the official repository.
