### ISSUE TITLE
When clicking Take screenshot or using flameshot -screen command nothing happens.

### ISSUE THREAD

**Issue by squarerootoftwo** [flameshot-org/flameshot#2835]
Ubuntu 22.04
https://bin.snopyta.org/?65a5d3e23af18d45#4Pd9LjdGJ2npSQUgeU4rAP24tJP1XXZ4rqV6gWCpcXqy

**Comment by mmahmoudian** [comment]
I would be thankful if you can properly fill a bug report issue and provide all the requested information in enough details. With this current format we don' t have enough information.

**Comment by squarerootoftwo** [comment]
I don't understand what you mean. What information should I provide sir ? I am very new to this thing. When I run flameshot on terminal by typing flameshot the terminal says "Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QLayout: Attempting to add QLayout "" to HistoryWidget "", which already has a layout
" 
And when I click on the Top bar where there the icon for flameshot is present. Then I click on take screenshot nothing happens. When I check on screenshot folder it is saying "Screenshots history is empty"

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         36 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz

I don't know what else should I tell you about ?
Please help.

**Comment by mmahmoudian** [comment]
> I don't know what else should I tell you about ?

we need many things to follow up an issue including:
- your Desktop Environment
- your Display Server
- the method you have installed Flameshot with
- The Flameshot version
- Your monitor setup if you have more than one monitor

So far all we know is that you are on Ubuntu 22.04, you have installed Flameshot, and you have an issue.

> If you want any other info tell me what info should i tell you and how to get that ?

It would be my pleasure to assist 🙂  . To report a bug you should follow these steps:
1. go to the [Flameshot repository](https://github.com/flameshot-org/flameshot/)
2. navigate to [the Issue tab](https://github.com/flameshot-org/flameshot/issues)
3. search if others have had the same issue (make sure to check also closed issues, maybe the this issue is resolved and the issue is closed)
4. if your issue was not reported before, you can [create a new issue](https://github.com/flameshot-org/flameshot/issues/new/choose)
5. select the type of issue (in your case perhaps "bug report" fits
6. fill [the form](https://github.com/flameshot-org/flameshot/issues/new?assignees=&labels=Unconfirmed+Bug&template=bug-report.yaml) (there are instructions on how to obtain information on a Linux machine) and submit

![image](https://user-images.githubusercontent.com/390889/181719439-89594fed-e738-4c10-863b-cbe34458f1ab.png)
![image](https://user-images.githubusercontent.com/390889/181719764-9852d7c2-3feb-47aa-8e2d-48f5c34ea359.png)
![image](https://user-images.githubusercontent.com/390889/181719861-7041ec42-9bd5-4f69-bdb5-f78b1924a2fe.png)
