### ISSUE TITLE
Arrow tool only wil only start from edge or from tip or previous arrow

### ISSUE THREAD

**Issue by tinkerbits** [flameshot-org/flameshot#2845]
### Flameshot Version

Flameshote 0.6.0+git20191001-2(Debian)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Ubuntu 20.04

### Description

Suddenly today Flameshot's arrow functions changed the way it behaves. No matter where in the screenshot I start drawing the arrow, it will pick a start point from somewhere on the edge of the screen or sometimes from the arrow button.

Then for next arrows; they'll pick as start point the tip of the previous arrow I drew.

I tried resetting the Flameshot config settings but that made no difference.

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/36033491/181484416-0522d4bb-1772-4ccd-8f57-3555f107a7f0.png)
![image](https://user-images.githubusercontent.com/36033491/181486991-79cee9ce-36f3-44f6-a67d-7870333bb533.png)

### System Information

Added screenshot of monitor configuration

OS: Ubuntu 20.04
Window Manager: Mutter
Display Server: X11 (xorg)

**Comment by mmahmoudian** [comment]
Thanks for reporting this issue. There are two points to consider here:
1. this is something that no one else has ever reported in the past 4 years, so most likely it is an issue with something about your own setup
2. Your Flameshot version is from 4 years ago. The current Flameshot version is 12.1.0. We do not follow bug reports for version that are that old as the code has changed along during all these years. I would suggest you to use our Snap, Flatpak, or AppImage. More information here: https://flameshot.org/docs/installation/installation-linux/#distro-agnostic

I will close this issue now, but please re-open this issue if the problem persisted on the most recent version. Thank you.

**Comment by mrjones-plip** [comment]
This issue should not be re-opened, but for those who have this issue, the fix is just what @mmahmoudian  says, upgrade! Ubuntu 20.04's `apt` repos install this hella old version (0.6.0) and I had the same problem (see video below). I can also confirm this fixes it:

1. remove the current version: `sudo apt remove flameshot`
2. install snap (or another if you're a snap hater): `sudo snap install flameshot`

All fixed!   Thanks for all the awesome work Flameshot devs, y'all are awesome!!

https://user-images.githubusercontent.com/8253488/211059665-65d7f132-e867-46bd-b691-f14cc8c99540.mp4
