### ISSUE TITLE
flameshot on m1 mac?

### ISSUE THREAD

**Issue by DeveloperKev** [flameshot-org/flameshot#2891]
### Feature Description

Hi,
i used to use flameshot on parrot. it was a massive boost. recenlty, i switched to mac, and there's no native build for apple silicon.
i mean, lot of people should be able to contribute in every way. everyone is porting their builds, maybe it should re-considered.
regards.

**Comment by mmahmoudian** [comment]
> people should be able to contribute in every way.

I can't agree more: As always, PRs are welcome

**Comment by KerimG** [comment]
I think porting it to Apple Silicon would be a great idea, considering that Apple is making a full switch to their own chips. Apparently, qt supports it too: https://doc.qt.io/qt-6/macos.html

**Comment by borgmanJeremy** [comment]
Theres really not a reason to stop using Rosetta. The performance is great.  I am not opposed to this, but the main blocker is there is no way to build an ARM version for Mac using Github Actions. Until there is a way past that there is no use discussing this further.

**Comment by jagibson** [comment]
Looks like it's on github's roadmap at least - https://github.com/github/roadmap/issues/528

**Comment by jagibson** [comment]
@borgmanJeremy forgive me for being entirely ignorant of github actions - I see there are several other projects out there that build "universal" binaries that support both apple silicon and intel.  Is this an option instead of making architecture-specific builds?

**Comment by sapslaj** [comment]
There's been some progress on the GitHub Actions side. Newer versions of the `macos` runner are all ARM-based and getting CMake to build universal binaries is very easy by setting `CMAKE_OSX_ARCHITECTURES=arm64;x86_64`. However, the Qt 5 libs that Homebrew provides are not Universal and are system-architecture-specific (e.g. x86_64 on an Intel Mac and arm64 on an Apple Silicon Mac) so trying to do a build with `CMAKE_OSX_ARCHITECTURES=arm64;x86_64` fails.

```
$ cmake -S . -B build -DQt5_DIR=$(brew --prefix qt@5)/lib/cmake/Qt5 -D"CMAKE_OSX_ARCHITECTURES=arm64;x86_64"
<snip>
$ cmake --build build
<snip>
[ 98%] Linking CXX executable flameshot.app/Contents/MacOS/flameshot
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtSvg.framework/Versions/5/QtSvg': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtDBus.framework/Versions/5/QtDBus': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtNetwork.framework/Versions/5/QtNetwork': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtNetwork.framework/Versions/5/QtNetwork': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Versions/5/QtWidgets': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Versions/5/QtCore': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Versions/5/QtGui': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Versions/5/QtGui': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Versions/5/QtGui': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Versions/5/QtCore': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtGui.framework/Versions/5/QtGui': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Versions/5/QtWidgets': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Versions/5/QtWidgets': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Versions/5/QtCore': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtWidgets.framework/Versions/5/QtWidgets': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file '/opt/homebrew/Cellar/qt@5/5.15.16/lib/QtCore.framework/Versions/5/QtCore': found architecture 'arm64', required architecture 'x86_64'
Undefined symbols for architecture x86_64:
  "qEnvironmentVariable(char const*)", referenced from:
      SingleApplicationPrivate::getUsername() in libSingleApplication.a[x86_64][4](singleapplication_p.cpp.o)
...
<snip>
...
ld: symbol(s) not found for architecture x86_64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/flameshot.app/Contents/MacOS/flameshot] Error 1
make[1]: *** [src/CMakeFiles/flameshot.dir/all] Error 2
make: *** [all] Error 2
```

I can think of a few options:

- Provide separate x86_64 and arm64 DMGs.
  - This is the easiest since it would just mean adding another build job using a newer macos runner to the existing macOS GitHub Actions workflow.
  - Downside: not a Universal binary; users have to chose the appropriate build for their system.
- Do two builds with separate runners on separate architectures and then use [the `lipo` tool](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary#Update-the-Architecture-List-of-Custom-Makefiles) to merge the two together into a Universal binary
  - This is arguably the "most correct" way to do this, but is a fair amount of extra complexity in the build system.
- Build or acquire a build of Qt built with `QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64"` since the ones from Homebrew don't set this.
  - I have no idea if this would even work correctly and I haven't been able to get a working Qt build with that set on my local machine (M4 Pro with Sequoia 15.1.1)
  - Note: this is not Qt 5 specific. Newer versions of both 5 and 6 are _supposed_ to support Universal binaries but the builds from Homebrew don't seem to have that capability enabled as far as I can tell.

I'm not a Flameshot maintainer, but I can try hacking together some GitHub Actions stuff if there are any feelings about the potential direction to take this.

**Comment by jagibson** [comment]
From what I can tell from the Homebrew discussions [1](https://github.com/orgs/Homebrew/discussions/412) [2](https://github.com/orgs/Homebrew/discussions/4985) - it's better to just have two separate installers if you want to maintain homebrew compatibility.
