### ISSUE TITLE
【Bug】flamshot gui is full screen but  not area

### ISSUE THREAD

**Issue by laglangyue** [flameshot-org/flameshot#2898]
### Flameshot Version

![image](https://user-images.githubusercontent.com/35491928/188081927-2c80b805-d9d3-47bb-9d7e-dbc400af00a2.png)

### Installation Type

Snap from

### Operating System type and version

ubuntu 22

### Description

flamshot gui is full screen but  not area

### System Information

Ubuntu SMP Fri Aug 19 08:01:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mmahmoudian** [comment]
This is an invalid bug report. You didn't provide enough information. But I think your issue is with Gnome Wayland, so read this:

https://flameshot.org/docs/guide/wayland-help/#i-am-asked-to-share-my-screen-every-time

If this does not solve your issue, fill all the sections of the bug report. They are important. You can also record a video to show us what the problem is.
