### ISSUE TITLE
Terminates when uploading capture on KDE Wayland

### ISSUE THREAD

**Issue by porcupinecoder** [flameshot-org/flameshot#2953]
### Flameshot Version

Flameshot v12.1.0 (-)

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

openSUSE Tumbleweed x86_64 

### Description

After capturing, selecting "upload" and clicking yes to confirm, flameshot terminates with error message:

`Job 1, 'flameshot' terminated by signal SIGSEGV (Address boundary error)`

I had no issues with it about a day or so ago. Saving the capture works fine

### Steps to reproduce

1. Run flameshot (launch app or `flameshot` in cli)
2. Select region
3. Click upload and confirm

### System Information

openSUSE Tumbleweed x86_64 

singlescreen laptop with nvidia optimus graphics

KDE plasma wayland

**Comment by mmahmoudian** [comment]
I tried to replicate this in a clean VM 

![image](https://user-images.githubusercontent.com/390889/197195936-aa413b93-f510-41ce-af9d-e4802a443f53.png)

![image](https://user-images.githubusercontent.com/390889/197196146-6dd15003-b940-411f-adea-43ee82a2f07f.png)

and this is the link to the uploaded screenshot: https://i.imgur.com/xyjia5v.png

And this is Wayland:

![image](https://user-images.githubusercontent.com/390889/197197625-ad329e4e-faeb-4452-b8d9-2f17047ef4a1.png)

and this is the uploaded screenshot: https://i.imgur.com/LyoW2YC.png

Also we have not released any new version since July 3rd 2022. Therefore, since I couldn't manage to reproduce this, to me it seems the issue is on your side. Perhaps a firewall or some sort of process control software on your machine.

@borgmanJeremy What do you think about this?

**Comment by porcupinecoder** [comment]
I think you are correct that this issue is on my end, as it seems to now have "magically" fixed it self. Apologies!

**Comment by mmahmoudian** [comment]
No need for apology. I'm happy that the issue is resolved. I'm not happy that we don't know the cause, but there is nothing much I can do.

Thanks for putting time into filing a bug report. I highly appreciate that.
