### ISSUE TITLE
"copy" doesn't work.

### ISSUE THREAD

**Issue by Shituation** [flameshot-org/flameshot#3015]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.19044
windows: 10

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

windows 10

### Description

Copy button closes the screenshot overlay and doesn't copy to clipboard.

### Steps to reproduce

Make a screenshot, instead of saving, use the copy button.

### Screenshots or screen recordings

TO WATCH, DOWNLOAD FIRST (USING H265 CODECS FOR LOWER SIZE)
https://user-images.githubusercontent.com/43975882/206907531-1bbfecfa-5a66-4788-a269-6a7012a918f6.mp4

### System Information

-

**Comment by serhumanos** [comment]
Installed as snap package (KDE Neon OS ubuntu based) when I copy, the app closes (as spected, no deamon) but no content in clipboard

**Comment by Shituation** [comment]
I'll have to switch to other app saddly, as this is crucial in a screenshot app.

**Comment by mmahmoudian** [comment]
@Shituation  I'm sorry to hear this, but it seems the issue is on your end. I cannot reproduce this, plus we have many Win10 and Win11 users and such behavior have not been ever reported, which suggests that this is a one-off case specific to your setup. Also, if we cannot reproduce it, we cannot investigate it either. You can see if you can reproduce this in a clean and newly-installed VM.

**Comment by mmahmoudian** [comment]
@serhumanos this comment is off-topic. I have to hide it. Also, if you search among the open and closed issues you will find your answer.

**Comment by Shituation** [comment]
Moved to "Freeshooter" which seems to do the job without problems.
