### ISSUE TITLE
Using alternative Website (like ShareX ?)

### ISSUE THREAD

**Issue by Oneloutre** [flameshot-org/flameshot#3029]
### Feature Description

Okay, First of all, maybe I'm gonna ask sth which has already been asked before, and I'm sorry. Even looking for it, I couldn't find any information. So I apologize if it has already be done.

If not, let's go. :)

I was wondering if it was possible to add the support of external websites (personal website, I mean) like it's possible with ShareX, and since a picture is worth a thousand words, here is a screenshot : 

![Capture d’écran 2022-12-20 à 00 00 06](https://user-images.githubusercontent.com/54822802/208543457-e111765e-78ca-4cd9-8cfc-e540874e7126.png)

To be more precise, I'd like to upload my screenshots to my own server. 
And to be even more precise, I'm talking about a GUI option ;)

Thanks for reading 👍

**Comment by mmahmoudian** [comment]
> maybe I'm gonna ask sth which has already been asked before

Of course it have been asked numerous times 😉

> Even looking for it, I couldn't find any information

Check this query:
https://github.com/flameshot-org/flameshot/issues?q=sharex

-------
But to save you some time: we have decided to only have this as a plugin, because there are are many many different places that people want to upload to, from Google Drive and Dropbox, to OwnCloud, Telegram and even Wordpress.

Please follow the plugin RFC thread for the progress
