### ISSUE TITLE
--path not respecting filenamePattern

### ISSUE THREAD

**Issue by jp-costa** [flameshot-org/flameshot#3051]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-1)
Compiled with Qt 5.15.4

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

debian based

### Description

I have set a filenamePattern in my config:
```
$ cat ~/.config/flameshot/flameshot.ini                         
[General]
checkForUpdates=true
contrastOpacity=188
filenamePattern=%F_%T
saveAfterCopy=true
saveAsFileExtension=png
savePath=/home/user/Pictures/Screenshots
savePathFixed=false
showStartupLaunchMessage=false
startupLaunch=true
uploadClientSecret=

```

and then am calling flameshot from cmdline. I expected the file name would follow the filenamePattern but instead the screenshots are saved with a number counter. 

```
$ flameshot screen -c -p /home/user/Pictures/Screenshot 
flameshot: info: Capture saved as /home/user/Pictures/Screenshot_3.png
```

Is there a way to specify a filenamePattern in CLI or force using the one from config?

### System Information

Linux kali 6.0.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.10-2kali1 (2022-12-06) x86_64 GNU/Linux

**Comment by mmahmoudian** [comment]
Thank you for filing the bug report (although not as complete as the form asked you 😉).

Now, about your issue, you have got it all wrong. The `savePath` should be a folder. So `flameshot screen` should follow your config. But when you add the `--path` you are not giving it a folder, you are suppose to give it "file path". So because the `/home/user/Pictures/Screenshots/` exists (although it is a folder not a file), so it starts using a number at the end to create a file you ordered it to.
