### ISSUE TITLE
flameshot cannot be woken up for screenshots using the PrtSc keyboard button when the right-click menu exists on the desktop

### ISSUE THREAD

**Issue by yangcheng1203** [flameshot-org/flameshot#3108]
### Flameshot Version

Flameshot v0.10.0

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

debian 10

### Description

When I opened flameshot and minimized it to the system tray, the single right mouse button in an empty space on the desktop brought up the menu. At this point, I tried the screenshot with the PrtSc button on the keyboard, but flameshot did not respond

### Steps to reproduce

1.open flameshot and minimize it to the system tray
2.Right-click the single mouse in a blank area on the desktop to evoke the menu
3.Press the PrtSc button on the keyboard to try the screenshot

Expected effect:
flameshot can take screenshots normally

Actual effect:
The flameshot have no reaction

### System Information

system:
debian 10

**Comment by Creteil** [comment]
To circumvent this trouble use the « launcher » with a delay that leave you the time to right click wherever you want...

**Comment by yangcheng1203** [comment]
> To circumvent this trouble use the « launcher » with a delay that leave you the time to right click wherever you want...

But it's a BUG, isn't it, that my flameshot is not immediately available when there is a right-click menu on the desktop?

**Comment by JustinMBrown** [comment]
I also have this issue

**Comment by mmahmoudian** [comment]
@yangcheng1203 @JustinMBrown 

> But it's a BUG, isn't it

No it is not a bug. It is expected behavior of your window manager. It will closes menus when the window looses focus. Flameshot cannot change this the same way as we cannot (and should not) alter your grub order.

As @Creteil kindly explained, the only way is to add some delay. You can either use CLI's `--delay` or use the launcher.

Also, v0.10.0 is very old. We are now at v12.1.0. Please consider updating.
