### ISSUE TITLE
Flameshot icon does not appear in the Debian menu bar

### ISSUE THREAD

**Issue by iDreem09** [flameshot-org/flameshot#3112]
### Flameshot Version

Flameshot version : flameshot:amd64/bullseye 0.90+ds1-2 uptodate

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Debian 11

### Description

Hello, I just want to point out that, under Debian 11, the icon in the menu bar at the top does not appear, I looked in the configuration of flameshot, it is well activated, but it does not appear, I do not know if it is a bug or a defect of Debian, but here it is.

### Steps to reproduce

1; Run flameshot by launchpad
2, no icons

### Screenshots or screen recordings

![2023-02-27_20h29_42](https://user-images.githubusercontent.com/126514173/221663824-f823e79f-f97d-4f59-8b23-5eb3f9958628.png)

### System Information

Linux debian 11 using GNOME 3.38 On a desktop computer

**Comment by mmahmoudian** [comment]
Debian is your distro and your desktop environment is Gnome. Showing tray icon what Gnome should do. Please read our documentation:

https://flameshot.org/docs/guide/troubleshooting/#in-gnome-the-flameshot-icon-does-not-appear-in-the-tray

Also your Flameshot version is pretty old (due to using Debian Stable), but we do not accept bug reports for such old versions. Please consider installing the newest version. The current latest version is v12.1.0
