### ISSUE TITLE
flameshot cannot detect desktop's windows or UI elements automatically.

### ISSUE THREAD

**Issue by lykiao** [flameshot-org/flameshot#3117]
### Feature Description

like this：
![无标题4](https://user-images.githubusercontent.com/54703532/222882751-b6066605-156e-43ef-acd4-eabc6a1acb78.png)

**Comment by mmahmoudian** [comment]
Please always write good text, write what you want, and be descriptive, BUT before that, always search among open and closed issues. This is duplicate.

**Comment by lykiao** [comment]
@mmahmoudian I searched but not found, if already exists, that's ok, sorry to wasted your time~

**Comment by mmahmoudian** [comment]
For example:
- #5
- #1816 
- #1814

It is not about wasting my time, but rather you opening an issue instead of supporting an existing one that has already some discussion and material in it. Basically you wasted you own time.

Also as the other part of my comment reflected, you have to explain the idea in details. Just copy-pasting one single photo without any relevant info is not going to be enough to convey the idea.
