### ISSUE TITLE
Attempting to capture main screen appears completely black every time

### ISSUE THREAD

**Issue by Funtimes909** [flameshot-org/flameshot#3122]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-2)

### Installation Type

Flatpak from Flathub

### Operating System type and version

Debian 12

### Description

When trying to capture a screenshot on my main screen (1440P 144 refresh rate) the entire screenshot will appear black, capturing them on my second screen (1440P 75 refresh rate) works perfectly fine

### Steps to reproduce

May not be reproducible 

### Screenshots or screen recordings

![image](https://user-images.githubusercontent.com/68979259/223352663-c5a4de80-3e48-4f56-8a4d-f9587ca812f9.png)
Screenshot from the second screen

![image](https://user-images.githubusercontent.com/68979259/223352726-d4675d18-8833-498c-b637-8291f41220ad.png)
attempted screenshot from main screen

### System Information

OS: Debian 12
CPU: i7-12700k
GPU: Intel UHD 770
RAM: 32GB (2X16) dual channel corsair vengeance 3600MHz kit
Display Server: Xorg (Also occurs on wayland)
Mesa Driver Version: 23.0.0-1
X Server Version: 1:7.7+23
Desktop Environment: KDE Plasma 5.27

Main monitor (one with black screen issue) https://www.harveynorman.co.nz/computers/monitors/konic-32-qhd-2k-curved-gaming-monitor.html
Don't know where I got second monitor from

**Comment by mmahmoudian** [comment]
How are you trying to take screenshot? For example are you using `flameshot screen -n 1` or are you using `flameshot gui`?

**Comment by Funtimes909** [comment]
I use a custom script I found in /bin to save the screenshots to sub directories based on the current date
here is that script

#!/bin/bash

year=$(date +"%Y")
month=$(date +"%m")
day=$(date +"%d")

filepath=(~/Pictures/Screenshots/funtimes909-$year-$month/$day)

mkdir -p $filepath

if [ "$1" == "full" ]
then
        flameshot full -c -p  $filepath
elif [ "$1" == "gui" ]
then
        flameshot gui -c -p  $filepath
elif [ "$1" == "screen" ]
then
        flameshot screen -c -p  $filepath
fi

I use KDES global custom shortcuts setup to run this script to take screenshots

**Comment by mmahmoudian** [comment]
@Funtimes909 I personally don't like this script as there are many things that can be improved, but that is besides the point and it in principal works. But you still didn't specify which one of them you are running (i.e "gui", "full", or "screen")

**Comment by Funtimes909** [comment]
It only happens when I am running screen

**Comment by Funtimes909** [comment]
Any update? I still have this issue

**Comment by mmahmoudian** [comment]
Sorry, I've missed your reply.

To me it seems the issue stems from the flatpak permissions. I suggest you try installing flatseal (can be installed also from Flathub), and see if you have permissions issues for Flameshot Flatpak.

As an alternative approach, you can test if AppImage (can be downloaded from [our release page](https://github.com/flameshot-org/flameshot/releases/latest)) and see if the issue persists.

I also worth pointing out that you are running `flameshot` and not via `flatpak run org.flameshot.Flameshot`. Therefore if you yourself have not set to somehow bind `flameshot` to run the flatpak, there is a chance that you are using Debian's Flameshot and not the Flatpak.

Also for quick testing you can do this instead of writing to file every time and check it:

```sh
flameshot screen --raw | imv -
#or
flameshot screen --raw | display
```

**Comment by Funtimes909** [comment]
I am going to try building from source, I'll let you know if that works

**Comment by mmahmoudian** [comment]
The following is quick and dirty instructions on how to build from source

1. Clone the repo

```sh
git clone --depth 1 https://github.com/flameshot-org/flameshot.git

cd flameshot
```

2. Compile:

```sh
#!/bin/env bash

# remove possible existing build folder
rm -rf build

clang-format -i $(git ls-files "*.cpp" "*.h")

mkdir build
cd build
cmake ../  #<--------------------------------------- here add other build flags if needed
make -j$(nproc --ignore 1)
```

3. Then you can run Flameshot:

```sh
# kill existing processes
pkill --full flameshot
sleep 1
# run the one you just compiled
./src/flameshot
```

**Comment by Funtimes909** [comment]
Built from source, still has the exact same issue

**Comment by Funtimes909** [comment]
still waiting for an update

**Comment by mmahmoudian** [comment]
@Funtimes909 Do you have fractional scaling on your monitor? Also does it happen on both of your monitors or only one of them?

**Comment by Funtimes909** [comment]
Remind me how I can check if fractional scaling is enabled?

**Comment by mmahmoudian** [comment]
Since you are using KDE:

![image](https://user-images.githubusercontent.com/390889/234588084-c0df640a-db2e-458c-980f-6ed1488b196c.png)

**Comment by Funtimes909** [comment]
thank you, no that is not enabled, its set at the default 100%

**Comment by Funtimes909** [comment]
![image](https://user-images.githubusercontent.com/68979259/234768837-4970fcda-b783-4bdb-b003-0d39e7195df7.png)

**Comment by skarndev** [comment]
> Since you are using KDE:
> 
> ![image](https://user-images.githubusercontent.com/390889/234588084-c0df640a-db2e-458c-980f-6ed1488b196c.png)

KDE does not yet have this feature available. Their scaling is shared across two displays. In gnome/cinnamon you can set individual scale per screen, maybe that is what causes the issue.

**Comment by Funtimes909** [comment]
still have this issue

**Comment by Funtimes909** [comment]
Hello?

**Comment by mmahmoudian** [comment]
@Funtimes909 Please avoid adding non-constructive comments (such as all those that I hid in this thread). The longer a thread gets, the less likely someone would find the stamina to go through it. Also, please note that everyone who work in this project are volunteers. No one owes anyone premium support. We are doing our best to juggle our personal lives, work lives, and FLOSS projects. If you want extra hand on the deck, consider putting bounty on the issues to attract freelance devs to help out. It is clearly explained [here](https://flameshot.org/donate/).

About your issue, I cannot reproduce this in X11 nor in Wayland in Manjaro, Arch, or Ubuntu. I have tried it on KDE Plasma, Gnome, Sway, Hyprland, ...

I went through the trouble of installing Debian 11 (12 is not stable release and I rather not even bother with something that is not stable by it's devs). It is ridiculously buggy and Grub fails to properly install if Gnome is not installed (installing only KDE makes the boot to consume one core CPU indefinitely. Anyways, this is the result:

[Peek 2023-05-14 14-28.webm](https://github.com/flameshot-org/flameshot/assets/390889/a6cbe356-5ced-43af-9f36-466e412f8e92)


Therefore this could **not** be reproduced in any of the clean-installed VMs I have:
- Debian 11 Plasma
- Manjaro Plasma and Gnome
- Ubuntu
- Fedora 37 (Plasma and Gnome)
- PopOS 22.04 (Pop shell)
- CentOS 7 (Gnome)
- OpenSuse Tumbleweed (Plasma)
- Ubuntu 20.04, 22.04 (Gnome)


All these bring me to the conclusion that the issue is most probably due to your setup (graphics driver, software misconfiguration, and etc.

**Comment by mmahmoudian** [comment]
Please re-open this if you managed to get the same effect in a clean-install VM (preferably Qemu's `qcow2` format)

**Comment by mmahmoudian** [comment]
I have tried it on multi-screen (3 monitors) setup on two laptops and two desktops, three Manjaro (KDE Plasma wayland and x11, AwesmeWM, and Hyprland). and one Windows 10. All these computers are either intel, AMD, or Nvidia (mesa driver).

How many monitors do you have, which Flameahot version, what was your installation method?

**Comment by kazmath** [comment]
I am having the same problem on a Pop_OS! installation using KDE plasma 5.24.7 and flameshot v12.1.0 (latest from ubuntu jammy) with two monitors with the same resolution, but I think I pin-pointed the issue on my part. For reference, this is my current monitor setup (yes, the right one is in the very corner):
![image](https://github.com/flameshot-org/flameshot/assets/66137568/cbb9375a-3776-4ffb-b8e2-d46d646a0d6f)

A `flameshot full` screenshot turns out like this:
![image](https://github.com/flameshot-org/flameshot/assets/66137568/de209213-c243-4e0a-948d-b0c049853066)

But when I do `flameshot screen` on either of those monitors, the image is just black. Thing is, I think I found the cause.

When I rearrange the position of my monitors like so:
![image](https://github.com/flameshot-org/flameshot/assets/66137568/29f4df63-daad-48f0-958f-46d4b974fce8)
A `flameshot screen` screenshot ends up like this (both monitors):
![image](https://github.com/flameshot-org/flameshot/assets/66137568/d08004ff-d933-45be-a4ca-05a987c04339)

![image](https://github.com/flameshot-org/flameshot/assets/66137568/5550f561-f13e-4c56-8cc1-00d8a5c87dcf)

So I think flameshot is somehow not properly adjusting the region when taking screenshots of monitors positioned in weird locations. Though I cannot test this theory, because passing  `--region 1920x1080+0+1080` as documented in `flameshot screen --help` does not work for some reason, giving me this line twice:
```QSettings::value: Empty key passed```

**Comment by aminst** [comment]
Hi,
Is there any update on this issue?
I also see black parts in my screenshot on Mac.

**Comment by ChristianF88** [comment]
Hi, 
same here, I am using Debian 12 with 2 external monitors (via a thunderbolt docking station). But even if I unplug from the docking station the issue stays the same.

I install via the Debian repo (`apt install flameshot`).

When running `flameshot gui` as root I get:
![Screenshot from 2024-09-12 13-24-29](https://github.com/user-attachments/assets/2da020be-9bc0-41d3-9e8a-d41c69327187)

Cheers,

**Comment by maviv** [comment]
resolved similar issues with a restart of my compositor (alt+shift+F12)

**Comment by quan-murphy** [comment]
Resolved issue by turning  Adaptive Sync to `Never` in Display Configuration Settings.  

<img width="665" height="409" alt="Image" src="https://github.com/user-attachments/assets/d2eda6e3-fa99-488b-8358-bd07a140cef1" />

**Comment by JavierDebian** [comment]
> Resolved issue by turning Adaptive Sync to `Never` in Display Configuration Settings.

THREE YEARS looking for a solution to leave X11!!!

Linux xxx 6.12.57+deb13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.57-1 (2025-11-05) x86_64 GNU/Linux

It works!!!!!

Thanks a lot!

Tags: debian trixie KDE Wayland flameshot black screen
