### ISSUE TITLE
execv error: No such file or directory 

### ISSUE THREAD

**Issue by sany98215** [flameshot-org/flameshot#3139]
### Flameshot Version

Flameshot-12.1.0.x86_64.AppImage 

### Installation Type

AppImage

### Operating System type and version

 6.1.19-1-MANJARO #1 SMP PREEMPT_DYNAMIC

### Description

when run in terminal,got this error
#./Flameshot-12.1.0.x86_64.AppImage 
execv error: No such file or directory 

### Steps to reproduce

1. `cd [file dir]`
2. `./Flameshot-12.1.0.x86_64.AppImage `
3. observe the error: `execv error: No such file or directory `

### Screenshots or screen recordings

```console
$ ./Flameshot-12.1.0.x86_64.AppImage 
execv error: No such file or directory
```

### System Information

kde: 5.103.0
qt:5.15.8
core:6.1.19-1-MANJARO
X11

**Comment by mmahmoudian** [comment]
I modified your post to have proper formatting. You can check the changes by clicking in these places in this order:

![image](https://user-images.githubusercontent.com/390889/226887052-3a5cd6f9-6421-4d75-af1f-c39ded7ce030.png)


About your issue, that is because of a software that is by default shipped with Manjaro named AppImageLauncher. [I have complained to Manjaro devs](https://forum.manjaro.org/t/trouble-running-appimages-after-removing-appimagelauncher/100297) to not ship it by default without telling users, but they are still doing it. 🤦🏼‍♂️ 

This is the problem with AppImageLauncher and has nothing to do with Flameshot. Read these:

- https://github.com/TheAssassin/AppImageLauncher/issues/518
- https://github.com/TheAssassin/AppImageLauncher/issues/559
