### ISSUE TITLE
not working on sway

### ISSUE THREAD

**Issue by fuzunspm** [flameshot-org/flameshot#3173]
### Flameshot Version

Flameshot v12.1.0 ()
Compiled with Qt 5.11.3

### Installation Type

Using the ready-made package from Github Releases

### Operating System type and version

Ubuntu 22.04

### Description

It won't work with an error message of:

Screenshot Aborted
Unable to capture screen
Unable to capture screen
Hit: try setting the XDG_CURRENT_DESKTOP environment variable
Unable to detect desktop environment (GNOME? KDE? Sway? ...)

### Steps to reproduce

1. run `flameshot gui`

### System Information

```
swaymsg -t get_outputs                                                                                                                          130 ↵
Output DP-1 'ViewSonic Corporation VX3418-2KPC WFJ212100657' (focused)
  Current mode: 3440x1440 @ 144.000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
```

**.zshrc**
```
# WAYLAND
export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME=qt5ct
export CLUTTER_BACKEND=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export SDL_VIDEODRIVER=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export _JAVA_AWT_WM_NONREPARENTING=1
```

```
╰─$ sudo apt search xdg-desktop | grep "installed"
xdg-desktop-portal/jammy-updates,jammy-updates,now 1.14.4-1ubuntu2~22.04.1 amd64 [installed]
xdg-desktop-portal-gnome/jammy-updates,jammy-updates,now 42.1-0ubuntu1 amd64 [installed]
xdg-desktop-portal-gtk/jammy,jammy,now 1.14.0-1build1 amd64 [installed]
xdg-desktop-portal-wlr/jammy,jammy,now 0.5.0-3 amd64 [installed]
xdg-utils/jammy-updates,jammy-updates,jammy-updates,jammy-updates,now 1.1.3-4.1ubuntu3~22.04.1 all [installed]
```

```
╰─$ sudo apt search grim | grep "installed"                                                                                                           1 ↵
grim/jammy,jammy,now 1.4.0+ds-1 amd64 [installed]
grimshot/jammy,jammy,jammy,jammy,now 1.7-1 all [installed]
```

**Comment by mmahmoudian** [comment]
Please search before opening any new issues. That said, make sure you have followed the instructions:

https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md

Apart from all these, please recognize that you are using a point-release distro that ships old versions of everything, from Flameshot to Sway and xdg-desktop-portals. This means that what you are reporting is from over a year ago and most probably has been already solved!

If the instructions above was followed to the tee and yet the issue persisted, try using Flatpak or AppImage. That might address some of the package incompatibilities.

I close this issue because:
1. we know that Flameshot works just fine on Sway in Ach
2. Since v12.1.0 flameshot have proved wayland compatibility
3. xdg-desktop-portal-wlr has also improved since
