### ISSUE TITLE
Next Stable Release?

### ISSUE THREAD

**Issue by Arkanyus** [flameshot-org/flameshot#3240]
### Feature Description

Looks like there hasn't been an official release in almost a year, any reason why?
Can see the PR and Issues pages are active

**Comment by mmahmoudian** [comment]
Yes, the reason is we are not there yet. Need to finalized some more issues. We are heavily under-staffed and code reviews take time. If you badly want a feature that is already merged, used the nightly builds:

https://flameshot.org/docs/installation/development-build/

If you are willing to help, we can use some extra eyes on code reviews and some Wayland bugs.

I will close this issue as this is more of a question than anything else. I reiterate, any positive contribution is very welcome.
