### ISSUE TITLE
Read out/Get last used region

### ISSUE THREAD

**Issue by anamyk** [flameshot-org/flameshot#3253]
### Feature Description

Hello,
thank you for this amazing tool!

I use flameshot 12.0.1.
If I used the "last region" feature via gui, but now want to read out what flameshot saved internally for this last region - how can I do that? 

CLI or terminal is fine.

I would appreciate any help!

**Comment by anamyk** [comment]
Okay, sorry for the issue. i just found out.

To obtain the last region captured by Flameshot you can follow these steps:

-     Open a terminal.
-     Enter the following command:` flameshot gui --print-geometry`
-     This command will display the geometry (coordinates and size) of the last captured region in Flameshot.
-     Instead of pressing "Esc" to exit the Flameshot GUI, you need to copy the screenshot to the clipboard.
-     After copying the screenshot, Flameshot will print the coordinates and size of the last captured region to the terminal.

**Comment by anamyk** [comment]
Okay, sorry for the issue. I just found out.

To obtain the last region captured by Flameshot you can follow these steps:

- Open a terminal.
- Enter the following command:` flameshot gui --print-geometry`
- This command will display the geometry (coordinates and size) of the last captured region in Flameshot.
- Instead of pressing "Esc" to exit the Flameshot GUI, you need to copy the screenshot to the clipboard.
- After copying the screenshot, Flameshot will print the coordinates and size of the last captured region to the terminal.

**Comment by mmahmoudian** [comment]
Thanks for providing the answer for others. I can make your answer even shorter:

```sh
flameshot gui --print-geometry --accept-on-select
```

basically what it does is it loads the previous coordinates, select that region then automatically "accept" your selection, but because you have not asked it to copy `--clipboard` or save to file `--path image.png`, it just prints out the coordinates as requested.

Another way is to see this info in the launcher (right-click on the tray icon, then click on "Open Launcher"):

![image](https://github.com/flameshot-org/flameshot/assets/390889/970e39a3-a4fc-4024-8a4b-863853bb5342)


-------

Now, to answer your original question: **read out what flameshot saved internally for this last region**
I wish it was super easy to tell you how to do it, but there is a catch. But first things first: Where the data is stored on your machine. On Linux the data is stored in `~/.cache/flameshot/flameshot/region.txt`. Now the catch: It is in binary form and is not human readable, so `cat ~/.cache/flameshot/flameshot/region.txt` does not show you the numbers.

I'm not sure if it worth the efforts of making Flameshot to write this as plain-text considering that there are easy ways to obtain this information via Flameshot.

**Comment by anamyk** [comment]
Thank you for the insights. It's actually really helpful and easier than my way. I prefer the terminal way, but the GUI way is good too. Somehow, I just didn't notice the "Open Launcher" button. I always went for "Configuration" and didn't find the info there.

I agree, it is not worth to make the effort to obtain the last region data as plain text from a file. The way it is now is fine :)
