### ISSUE TITLE
Prebuilt packages page does not provide any prebuilt packages

### ISSUE THREAD

**Issue by bgoodr** [flameshot-org/flameshot#3257]
### Flameshot Version

Flameshot v11.0.0 (11.0.0-2 Debian)
Compiled with Qt 5.15.2

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Xubuntu 22.04

### Description

https://github.com/flameshot-org/flameshot#prebuilt-packages

Shows some versions and useful information, but does not provide any links to downloading packages. If you are using the word "prebuilt" in this context, that is incorrect because it implies we can directly download an installer and install directly from that prebuilt page.  

How I got here: What I was looking for was a more recent version of flameshot, on my Xubuntu 22.04 box, but it only has version 11 not the v12 I need to fix a bug that is already fixed. But I came up short. Now it appears I will either have to upgrade my entire Xubuntu 22.04 to 22.10 and then reinstall flameshot, or have to build flameshot from source (which would not be the end of the world, of course, but still hence this gripe about nomenclature in the readme).

Can someone either stop using "prebuilt" in the readme, or clarify it's meaning therein?

It also appears that there is no Ubuntu PPA that I could use to get the more recent version, or am I just missing something?

### Steps to reproduce

Navigate to https://github.com/flameshot-org/flameshot#prebuilt-packages and see the word "prebuilt"

### System Information

Xubuntu 22.04 using X.org

**Comment by mmahmoudian** [comment]
> If you are using the word "prebuilt" in this context, that is incorrect because it implies we can directly download an installer and install directly from that prebuilt page.

You literally can, open the assets of each release and download the binary for any operating system. It is illustrated here:

https://flameshot.org/docs/installation/installation-windows/#manual-installation

> Now it appears I will either have to upgrade my entire Xubuntu 22.04 to 22.10 and then reinstall flameshot, or have to build flameshot from source

You can also download the development builds which contains changes from last stable release till today. They should be considered as unstable though:

https://flameshot.org/docs/installation/development-build/

> Can someone either stop using "prebuilt" in the readme, or clarify it's meaning therein?

No we can't. Because we are literally providing prebuilt (i.e already compiled) versions for all major operating systems that run on x86 CPU architecture.

> It also appears that there is no Ubuntu PPA that I could use to get the more recent version, 

We do not provide PPA and considering the dependencies we do not want to support such user-managed repo for point-release Linux distros. If you want to maintain it though, we will happily do our best to help you.

> am I just missing something?

Well, quite a bit actually. Apart from the assets in Github release page and also the development builds, you can also use a distro-agnostic method to install Flameshot stable (e.g Flatpak, Snap, AppImage). These are fully explained here:

https://flameshot.org/docs/installation/installation-linux/#distro-agnostic

**Comment by bgoodr** [comment]
Thanks for your writeup. I'm all sorted now. :)

Had there not been a large amount of "What's changed" and "Contributors" lists in front of the .deb links (or .zip files, or .rpm files etc.), underneath the **Assets** section, I would have seen those links and considered them for clicking.  I was just trying to find out if flameshot would work, but I got tripped up over irrelevant information just in my search for something to download and try.
