### ISSUE TITLE
Flameshot not working while system panel are open

### ISSUE THREAD

**Issue by ajay-ca** [flameshot-org/flameshot#3391]
### Flameshot Version

Flameshot v12.1.0 (Debian 12.1.0-2)
Compiled with Qt 5.15.8

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...), Snap from

### Operating System type and version

Operating System: Ubuntu 23.10

### Description

I have recently updated my **Ubuntu** from `23.04` to `23.10`. I was trying to take a screenshot using the **Flameshot** software (which has been my default screenshot software for a year) while my top panel was open but it is not taking any screenshots. The top panel I meant is the calendar and notification section and the quick menu in the top right corner. There is no issue with taking screenshots with all that closed.

I found none of the configurations and settings that might help the flameshot software. The native screenshot application in Ubuntu works fine but I need to use some marking and selection tools that are not available.

### Steps to reproduce

1. open the notification panel or quick setting panel on top.
2. press `printscrn` key or the key that trigger flameshot.

### Screenshots or screen recordings

[Screencast from 2023-10-26 14-07-57.webm](https://github.com/flameshot-org/flameshot/assets/87013178/b0c7623b-aae4-40a1-9c04-b0201d4b2cca)

In the above video, you will be able to know that the flameshot is able to screenshot and I have aborted it. But when I open the system panel, it is not working.

### System Information

         Chassis: laptop 💻
      Machine ID: 46e3968479bb47c2a33820cf7ed343b7
         Boot ID: e2b85d2127814b9495d7e1d3583345b2
Operating System: Ubuntu 23.10                    
          Kernel: Linux 6.5.0-10-generic
    Architecture: x86-64
 Hardware Vendor: Dell Inc.
  Hardware Model: Inspiron 15 3511
Firmware Version: 1.24.0

**Comment by mmahmoudian** [comment]
This is expected behavior in all softwares in all operating systems. When you have a menu open, the keys you press will be sent to that application. if you want to take a screenshot of a window you have one option: set timer. For setting timer you have multiple ways:
1. graphical way: rightclick on flameshot icon in the tray area, and open launcher (unfortunately you are using Gnome, so no icon for you unless your Ubuntu is shipped with the Gnome extension that enables that)
2. almost graphical way: open launcher from terminal: `flameshot launcher`
3. CLI way with Flameshot: `flameshot gui --delay 3000` for 3 seconds delay
4. old-school CLI way: `sleep 3s && flameshot gui`

You can read more about our CLI (CommandLine Interface) here;
https://flameshot.org/docs/advanced/commandline-options/
