### ISSUE TITLE
Disable flash and shutter sound effect in settings

### ISSUE THREAD

**Issue by hendrychjan** [flameshot-org/flameshot#3426]
### Feature Description

Hi,
first, let me say that I am really happy with Flameshot, I think the devs did a great job, it is the best screenshot tool I ever used. I am really thankful. 
However, there is just one thing, that is really annoying me, and I couldn't find a way to turn it off. It is the flash effect, and the shutter sound. Seeing a bright flash while I am sitting in a dark room, using dark mode on windows, is quite unpleasant, and the loud shutter sound when I forget to check if my speakers are muted while I'm working in a library, makes for a great amount of really awkward moments. And I really just don't need to hear it even when I have headphones on. If it was possible to add an option into settings that would turn this off, that would be great.
Thank you so much :relaxed:

**Comment by mmahmoudian** [comment]
We are happy that you are enjoying Flameshot and have find it useful.

Here is a bit of explanation to clarify things:
In Flameshot when you ask for a screenshot we as your operating system to take a screenshot and pass it to us. We then create a fullscreen window and show you that image and allow you to annotate it. In other words, what happens during the capturing of the actual screenshot is out of our control. Any visual/sound effect if produced by your operating system. This is usually to give the user some notion of safety so that they know if some program is requesting screenshots. You most probably can find a setting in your Windows to turn this off. I found this article by a quick search:


https://www.addictivetips.com/windows-tips/enable-disable-screenshot-flash/


If you found the correct option, please post here along with your windows version so that other users can also benefit. Thanks.

I will keep this issue open just in case there is actually a way to ask Windows to be quiet about this, although I highly doubt that.

**Comment by hendrychjan** [comment]
Hi,
thanks for the response. I am sorry that I didn't clarify this earlier, but I am using linux (OpenSUSE Tumbleweed, Gnome).
Per your explanation, I understand that the effect is an OS thing. The default Gnome screenshot tool doesn't produce any sound, nor visual effects, just shows the screenshot overlay. So I suppose it isn't caused by Gnome, but directly by the OS OpenSUSE somehow? I have no idea how to disable it, so I will try to ask on some OpenSUSE forum and I will let you know.

**Comment by alexdevos** [comment]
@hendrychjan same problem here, after some searches, flash and shutter sound effect are hard coded in `gnome-screenshot` : see this link to disable with recompiling `gnome-screenshot` of https://askubuntu.com/questions/854350/disable-gnome-screenshots-camera-flash-animation and this issue on GNOME GitLab : https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3866.
(I did not try to recompile `gnome-screenshot`, I think I'll wait for a setting to appear...)

**Comment by hendrychjan** [comment]
@alexdevos thank you! I tried recompiling and it worked. I also looked at the gitlab thread, and I think it is sad that it seems to be dead..

**Comment by kimjongbing** [comment]
ive recompiled gnome-screenshot but flameshot still flashes, any thoughts as to why?

**Comment by mmahmoudian** [comment]
@hendrychjan @kimjongbing this is Gnome issue and not Flameshot. Gnome is using a private API for their own software and force others to use a public API. One of the perks of this public API is that it will produce those effects qhen a screenshot is take (I think they naively think of this as a privacy "feature").

There is nothing we at Flameshot can do about this. Please take your complaints right to Gnome devs as they are forcing this upon you.

Personal suggestion: If you want some level of customization in your desktop environment, try avoiding Gnome. My suggestion: try KDE Plasma or Mate

**Comment by gonzalez-cy** [comment]
To disable the camera sound when taking screenshots in Ubuntu, you can change the filename of the sound file that Ubuntu uses in these cases:
```
sudo mv /usr/share/sounds/freedesktop/stereo/camera-shutter.oga /usr/share/sounds/freedesktop/stereo/camera-shutter-disabled.oga
```

**Comment by natema** [comment]
> To disable the camera sound when taking screenshots in Ubuntu, you can change the filename of the sound file that Ubuntu uses in these cases:
> 
> ```
> sudo mv /usr/share/sounds/freedesktop/stereo/camera-shutter.oga /usr/share/sounds/freedesktop/stereo/camera-shutter-disabled.oga
> ```

This works on Fedora as well, thanks!

**Comment by iiaiiappa** [comment]
There is a gnome extension written by MadddinTribleD, and I finally can disable the flash that really hurts when doing screenshots on ubuntu in a patch dark room.
https://extensions.gnome.org/extension/10009/disable-screenshot-flash-and-sound/

Further reading materials,
https://gitlab.gnome.org/GNOME/gnome-shell/-/work_items/3866
