### ISSUE TITLE
While taking a screenshot, all the tools buttons are out of sight

### ISSUE THREAD

**Issue by noomly** [flameshot-org/flameshot#3483]
### Flameshot Version

Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

Arch Linux, Sway 1.8.1

### Description

As you can see on the provided screenshot, the tools buttons doesn't appear around the selected area. Only one seems to appear at the top left corner of the screen, while all the others are simply absent. The "side panel" is also absent, and pressing `<space>` doesn't make it appear anywhere.

I can still use the tools via the keybindings, and Flameshot can still successfully take the screenshot.

### Steps to reproduce

1. run `flameshot gui --path "here.png"
2. select an area
3. notice how the tools are not located around the selected area

### Screenshots or screen recordings

![2024_01_30-13_20_05_265406336](https://github.com/flameshot-org/flameshot/assets/9301991/d2e6c22d-4480-4875-b387-eb4ed62d30a3)

### System Information

This happens on my laptop, without any monitor plugged. My screen is 1920x1080.

I'm running Arch Linux with Wayland using Sway. I have followed the instructions at <https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md>. With the exception of adding `for_window [app_id="flameshot"] border pixel 0, floating enable, fullscreen disable, move absolute position 0 0` to my sway config, as with this line the whole screenshot interface doesn't appear at all.

**Comment by noomly** [comment]
I just realized that my screen wasn't located at position 0,0. Configuring it with `wdisplays` to 0,0 seems to resolve the issue.
I'm not sure if this should be considered as a workaround to a bug though? So I'll leave the issue open.

**Comment by poplawskidaniel** [comment]
This is also happening when I have multimple monitors but some of them are actualy disabled. My  =sway condifuraton contains `for_window [title="flameshot" app_id="flameshot"] fullscreen enable global` instead.

Maybe my usecase is not standard: I have multiple monitors connected all the time. However I am using shortcuts configured in sway to change between few monitor configurations. Why ? Because one monitor is TV and two others are on my desk. So wehn I am using my PC on TV to watch something etc I am just switching that my TV is only one enabled and two other monitors are disabled (and actually they are to the left of TV). Other cases depends on my need and sometimes I am using only one monitor, sometimes only 2, sometimes all 3 (inlcuding TV) I want to use.

Flameshot show buttons correctly only when all 3 monitors are visible.

In addition I've problem that my screenshots are cut. They just show top part of the image, rest is black.

Flameshot Version
Flameshot v12.1.0 (-)
Compiled with Qt 5.15.10

Installation Type
using pacman

Operating System type and version
Arch Linux, Sway 1.8.1

**Comment by noomly** [comment]
I realized there was already an issue for this bug (#2941) so I'm going to close this one.
