### ISSUE TITLE
PrintScreen button on Windows 11

### ISSUE THREAD

**Issue by guttizin** [flameshot-org/flameshot#3485]
### Flameshot Version

Flameshot v12.1.0 (96c2c82e)
Compiled with Qt 5.15.2
winnt: 10.0.22631
windows: 10

### Installation Type

Linux, MacOS, or Windows Package manager (apt, pacman, eopkg, choco, brew, ...)

### Operating System type and version

I'm using windows 11 and reinstaled it using `winget install flameshot` 

### Description

After press PrtScr it was expected to open Flameshot hud, but it opens Windows Snipping Tools hud
On flameshot there's a Shortcut menu, but can't change the Screenshot shortcut button.

### Steps to reproduce

1. Run flameshot
2. Press PrtScr button  on keyboard

### Expected Result

1. Press PrtScr button
2. Use Flameshot hud as i always used it.

### System Information

1. Windows 11 Pro 23H2
2. Compilation SO 22631.3085

**Comment by Zwixx** [comment]
Same Problem with Windows 11 Pro 23H2.

**Comment by mmahmoudian** [comment]
This issue is duplicate. Searching among open and closed issues or reading our documentation could ave you lots of time and trouble.


This issue you are facing is because of your operating system (i e Microsoft Windows) and is not at all Flameshot's fault. We have explanation on our website on how to fix this:

https://flameshot.org/docs/guide/windows-help/#how-to-disable-windows-snipping-tool-when-i-press-printscreen

Microsoft keeps pushing users to use Microsoft products. Perhaps you can give better operating systems a try that cares about user rather than pushing products.

**Comment by sasoriza** [comment]
Why not provide a setting that lets you assign a custom key? Or is that against your policy of not supporting operation systems that "don't care about users"?

**Comment by borgmanJeremy** [comment]
The main issue is I don't have a windows development machine (and I dont want one). So its largely community support for windows.
