### ISSUE TITLE
[Feature Request] Persist tool size & color individually at tool level

### ISSUE THREAD

**Issue by ronjouch** [flameshot-org/flameshot#356]
Currently, if I change via mouse wheel the size of, for example, the text tool, to something big like 40px, then the size for the other tools (e.g. the rectangle) is modified too.

That means, unless I manually change size each time I switch tools, I'll get results like (20px):

![screenshot_2018-09-26_07-52-14](https://user-images.githubusercontent.com/522085/46078177-6a0c9c80-c161-11e8-8eee-6fc61e4b902a.png)

Instead, it would be neat if tool {size, color} were persisted individually in each tool. Anecdotally, that's what my former favorite screenshot tool Shutter does. It would feel like:

- Click Text → Flameshot remember last choice of [20px, red]
- Click Shallow Rectangle  → Flameshot remembers last choice of [3px, red]

Leading faster to the proper expected result:

![screenshot_2018-09-26_07-58-55](https://user-images.githubusercontent.com/522085/46078402-0c2c8480-c162-11e8-8a97-98fc65c1828b.png)

Thanks for Flameshot! 🙂

**Comment by mmahmoudian** [comment]
@ronjouch I know your feature request existed before #782 , but that one has now more momentum, therefore I mark this as Duplicate of #782 and close this one in favor of the other one. Please feel free to post here and re-open this if you think the #782 is not a good representative of this one.

**Comment by heldergg** [comment]
This issue was closed as a duplicate of #782, but #782 only addresses persisting the size/thickness of each tool independently. The size-per-tool behavior described there has since been implemented (it now works correctly), but the color half of this original request is still outstanding: switching between tools (e.g. arrow → text → arrow) does not restore each tool's last-used color, only its size.

Could this be reopened, or should a new issue be filed specifically for per-tool color persistence?

**Comment by mmahmoudian** [comment]
@heldergg 
> but the color half of this original request is still outstanding: switching between tools (e.g. arrow → text → arrow) does not restore each tool's last-used color, only its size.
> 
> Could this be reopened, or should a new issue be filed specifically for per-tool color persistence?

Good catch and thank you for bringing this to out attention. I believe it would be easier and cleaner to open a new feature request and also reference this one in the text.

This issue is a good example for why we prefer to have one idea per feature request, although I understand that sometimes features are so tied to each other that separating them reduce clarity.

If you would like to invest time and do it let me know, otherwise I can do it on your behalf. :)

**Comment by heldergg** [comment]
~~I will gladly do it, in a few hours.~~

It's done #4957.
