### ISSUE TITLE
Flameshot doesn't place upload to imgur window centered on (Xfce)

### ISSUE THREAD

**Issue by orschiro** [flameshot-org/flameshot#372]
Hi all, 

Initially I thought this was a bug with Xfce but the [developers](https://bugzilla.xfce.org/show_bug.cgi?id=14742) advised me to report this against Flameshot. 

I have recorded this video for you to demonstrate the issue with the window placement:

https://drive.google.com/file/d/1__J6PTL8vAJDvFjFkK9KHDRlhvZP2ZNB/view

In Xfce, I have chosen the following setting:

Window Manager Tweaks > Placement > Large 100% at the centre of the screen

However, this rule is not being respected for the upload window and I am not properly seeing the buttons, like "Copy image URL to clipboard".

Could someone please try to reproduce my problem? Maybe also on different DEs and WMs?

Thank you!

Yours

Robert

**Comment by luzpaz** [comment]
Can confirm on: 
XFCE 4.13  
FlameShot 0.6.0

**Comment by mmahmoudian** [comment]
@orschiro and @luzpaz considering that the issue you raised is from 3 years ago and flameshot has to high extent changed and improved since then, would you please check if the newest version (v0.9.0) still have this issue.

**Comment by luzpaz** [comment]
Not using flameshot anymore, using the Spectacle now.

**Comment by mmahmoudian** [comment]
Do you mind giving it a second shot? 😅

**Comment by luzpaz** [comment]
I'm not on XFCE anymore though, on KDE Plasma. Tried to recreate the bug but couldn't because I encountered a hanging bug trying to upload to imgur. Flameshot just hangs. I need to kill it via the CLI

Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.12.9-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-6560U CPU @ 2.20GHz

Flameshot v0.9.0

**Comment by mmahmoudian** [comment]
@luzpaz Thanks for trying. That imgur animation freeze is a known issue in Manjaro KDE (#1503).

**Comment by mmahmoudian** [comment]
I'm closing this as it has been stale for over a month and it is about an old version. Please consider opening a new issue of you face any problems with the newest version of Flameshot.

**Comment by luzpaz** [comment]
Ok updated flameshot, my observation is that flameshot skips the confirmation dialog and just uploads the screenshot directly to imgur. Not sure if this really solved the issue, lol. It just removes the buggy dialog altogether. I don't think this is the ideal solution since it's nice to be asked if the screenshot I just made (and shown) should be uploaded to imgur. 

```
v0.10.1
Qt 5.15.2
```

**Comment by mmahmoudian** [comment]
@luzpaz we are working on it to make few changed to the upload process, one of which is this confirmation dialogue: #1751
