### ISSUE TITLE
Shortcut for restart flameshot

### ISSUE THREAD

**Issue by amandus99** [flameshot-org/flameshot#3739]
### Feature Description

as I am connected to different displays flameshot is not detecting the available screens properly. If i manually quit flameshot and restart again, it works as expected. So a shortcut for a restart would be nice. For sure even better. That all displays are properly detected with the correct resolution all the time. I am working on a mac.

**Comment by mmahmoudian** [comment]
That's not a correct solution. The correct solution is to make Flameshot "detect" display changes, although this is not an easy task due to different operating systems have very different hooks. Or if we want to check the resolution and displays every n seconds there is a chance that someone takes a screenshot before the refresh, and also it adds to the load of that machine.

Since you are ok wth having a shortcut, for now you can create a shortcut for yourself and bubd it to:

```sh
pkill flameshot && sleep 1s && flameshot &
```

This will kill existing Flameshot process, wait for 1 second (just in case your computer is under heavy load, and then starts a new Flameshot process.

Let me know if you have issues with this small shell command.

This have been discussed in another issue in details. I close this issue in favor of that one.
