### ISSUE TITLE
Add JPEG XL (JXL), AVIF support for 

### ISSUE THREAD

**Issue by Mk007V2** [flameshot-org/flameshot#3740]
### Feature Description

Currently, the most efficient format to save screenshot is WEBP. Which is ok, but inferior in quality to new formats like AVIF and JPEG XL. Most of the time users copy the screenshot into clipboard and do not save it, so the people who do store screenshot would benefit from more efficient formats.
![image](https://github.com/user-attachments/assets/5417be2a-0226-4b96-bc8c-eecc9f827d9f)

AVIF is widely supported and likely to be more popular, because it is supported by Google and AOMedia. It would also be great to have JPEG XL as an option. It is a new format, currently supported by ONLY Apple products such as iOS and Safari. However, there are a lot of people using this format to store because of its superior quality for mid-filesized images.
 
Both of them are superior to existing image formats in flameshot, as well as royalty-free; meaning, there should be no trouble using this format for the purpose of this program. 

Personally, I have done some testing on comparing those formats and both AVIF and WEBP bend colors on low-filesized screenshots, albeit AVIF is more efficient than WEBP. On the contrary, JPEG XL does not suffer from the same problem, but is less wide-spread. I would love to see both of them in flameshot, to have more choice.

Thanks for making flameshot! I enjoy using this program and it is useful.

**Comment by novomesk** [comment]
Using AVIF and JXL is possible if you add plugins:

https://github.com/flameshot-org/flameshot/issues/3062

**Comment by Mk007V2** [comment]
Excellent. It works !

**Comment by Lonniebiz** [comment]
I wish AVIF was included without the need for a plug-in. The quality-to-file-size ratio of AVIF is significantly superior to PNG and JPG. That's why I think it deserves to be a first class citizen in Flameshot.

**Comment by risako11** [comment]
I have no idea how to install this plugin in Windows...
I cant figure out this part:
<img width="887" height="190" alt="Image" src="https://github.com/user-attachments/assets/f68caa08-901b-481d-8c03-a69524c354f1" />

I downloaded that "shared-mime-info" package, but the only file i found inside was "freedesktop.org.xml.in" and copying this file (or renaming it to "freedesktop.org.xml") didnt work...
I am clueless how this works... I guess i have to somehow install the shared-mime-info into my windows and not just copy the file... the installation process is however above my skill

**Comment by novomesk** [comment]
The situation changed meanwhile since the time of Qt 5.

Now flameshot on Windows uses Qt 6.9.3 and the MIME types are already bundled in.

It is enough to add the DLL plug-ins only, but must make sure **that they were built for the same Qt version**. Anti-virus scan is always recommended.

So if you download these:

https://github.com/flameshot-org/flameshot/releases/download/v14.0.0/flameshot-14.0.0-win64.zip

https://github.com/novomesk/qt-avif-image-plugin/releases/download/v0.10.3/qavif6.dll

https://github.com/novomesk/qt-jpegxl-image-plugin/releases/download/v0.8.3/qjpegxl6.dll

All you need is to put **qavif6.dll** and **qjpegxl6.dll** inside `flameshot-14.0.0-win64\bin\imageformats` folder and restart flameshot.
