### ISSUE TITLE
[Feature Request] Add magnifying frame for corner selection

### ISSUE THREAD

**Issue by steelstrings** [flameshot-org/flameshot#390]
I propose a magnifier frame for pixel-perfect screenshots, which appears when you drag-resize one of the corners w/ your cursor. Activate either in a setting, on keypress, or both.

`spectacle` for example has got support for this

![snapshot_2018-10-30_22 56 41](https://user-images.githubusercontent.com/24418003/47753321-71aaee00-dc97-11e8-98e3-9038106d3794.png)

However instead of a crosshair which determines the corner pixel of the screenshot being taken, I would suggest to keep everything inside the corner and cut off everything which is overlaid.

![snapshot_2018-10-30_22 57 28_2](https://user-images.githubusercontent.com/24418003/47754446-38747d00-dc9b-11e8-916b-55b159c20767.png)

**Comment by k1nghat** [comment]
im not sure how it would be implemented but i love that you can arrow over px by px to get that precision but without some sort of magnifier its not really that useable.

**Comment by sfire** [comment]
@steelstrings I totally agree with you that a magnifier while **placing the cursor** and **adjusting the border** will help a lot. 
I've been using a screen-capture program([Snipaste](https://github.com/Snipaste/feedback)) under Windows which has this feature, and shows **coordinates** and **pixel color value**.

![image](https://user-images.githubusercontent.com/5409756/53693867-58e74c00-3de1-11e9-88df-7f155c8b1b55.png)
Hope this will help @lupoDharkael add this feature.

**Comment by densha** [comment]
Any update on this feature request? I came across flameshot after looking for a replacement for Shutter on Linux. This feature would make flameshot on par with other screenshot tools that have this feature (Shutter, Snagit, ShareX).

**Comment by borgmanJeremy** [comment]
I'll take a look at it, it would be pretty useful.

**Comment by cacarr-pdxweb** [comment]
> Any update on this feature request? I came across flameshot after looking for a replacement for Shutter on Linux. This feature would make flameshot on par with other screenshot tools that have this feature (Shutter, Snagit, ShareX)

I expect many people are looking for a replacement for Greenshot, which does not have a Linux version. Flameshot is very similar and a good replacement, except for the lack of this feature. 

If this could be added at some point, that would be great.

**Comment by borgmanJeremy** [comment]
I started looking into it and it wasn't a quick add. I still would like to add it but right now its in the backlog as we focus on some other improvements.

One way to help contribute to this feature would be to open an RFC so the community and developers can start discussion the requirements and how the feature will integrate into Flameshot. This RFC will help us answer things like:

* Can you enable the magnifying glass inside the selection in GUI mode or just corners?
* How should the magnifying glass interact with the resize tool?
* How magnified should it be?
* What happens if you are right up against a screen edge? Should it wrap inside the screen or do nothing?

There are just some questions but I bet the community will have other great ideas and feedback for making this the best feature.

**Comment by antaxiom** [comment]
Any more updates on this? I heard someone talk about it and it seems very useful. I'd like to see more work on this.

**Comment by mmahmoudian** [comment]
I think this is now fully implemented via #2219
