### ISSUE TITLE
Capture an active window

### ISSUE THREAD

**Issue by d4n3sh** [flameshot-org/flameshot#395]
Sorry but I could not find the option to capture an active window/app in help.  Is it possible?

**Comment by icf20** [comment]
@d4n3sh afaik that option dont exist

**Comment by DanitiKain** [comment]
This would be very useful to have is it a planned addition. Like right now I a copying a large amount of files and a screen is popping giving me errors because of some file names being to long for USB. So I need to a quick way to capture which files so I can go back in and edit them later. So like on windows I could hit alt print screen to get the active window.  Please add this feature :)

**Comment by daiaji** [comment]
I also need this feature very much.😃

**Comment by azhi** [comment]
Leaving a reference to related issues #5 and #334 - seems like this feature is already planned for next release.

**Comment by derek-shnosh** [comment]
This is a great suggestion; or something similar to windows ShareX region selection (`ctrl+prnt`) that _best guess_ attempts to selection windows/regions as you mouse over them. But I'm sure that's a whole other challenge.

**Comment by AlexWayfer** [comment]
Can this issue be closed as duplicate of #334?

**Comment by Vladimir-csp** [comment]
yes, it seems

**Comment by mmahmoudian** [comment]
I will close this as to me it seems like duplicate of  #334
