### ISSUE TITLE
Name configs after application name

### ISSUE THREAD

**Issue by abba23** [flameshot-org/flameshot#4]
Having the config files/folders named after the application and not after the developers username would be a lot more meaningful I think.
As far as I can tell this includes
~/.config/Dharkael.conf
~/.config/Dharkael/flameshot.conf
/etc/xdg/Dharkael.conf
/etc/xdg/Dharkael/flameshot.conf

**Comment by lupoDharkael** [comment]
This is handled automatically by QT when you define organizationName() and applicationName() in the program. Actually what you see as "Dharkael" is the string defined as organization name. Changing this would discard the configuration of the actual users using the software but I'll keep this open because I could contemplate a change before the 1.0 release in the future. Maybe changing the organization as Flameshot (?)

**Comment by richarddewit** [comment]
Or perhaps clarify in the README that the config can be found in `~/.config/Dharkael/flameshot.ini`

**Comment by borgmanJeremy** [comment]
This is fixed in 0.8
