### ISSUE TITLE
No screenshot is taken if the context menu is open

### ISSUE THREAD

**Issue by vokamut** [flameshot-org/flameshot#457]
**Flameshot version**
Flameshot v0.6.0
Compiled with Qt 5.11.1

**Describe the bug**
No screenshot is taken if the any context menu is open.

**To Reproduce**
Call the context menu and try to take a screenshot

**Expected behavior**
Take a screenshot

**System Information**
OS: openSUSE Tumbleweed 20190115
KDE Plasma: 5.14.5
Qt: 5.12.0
KDE Frameworks: 5.53.0
Kernel: 4.20.0-1-default
Architecture: x64
CPU: 4 × Intel® Core™ i3-3220 CPU @ 3.30GHz
RAM: 7,7 GiB

**Comment by farseerfc** [comment]
I think you should be able to take a screenshot of a context menu using delayed option like this:

1. run `flameshot gui --delay 5000` , this will delay 5 seconds before taking the screenshot
2. do whatever to open the context menu during those 5 seconds
3. wait for the flameshot to take the screenshot

As for the normal command without delay, I think this is due to the limitation of X11 protocol, that the context menu grabs X11 session level keyboard events thus prevents other things to open, those other things include screenshot apps, screen lockers, etc.

**Comment by mmahmoudian** [comment]
@vokamut If I have correctly understood your point, this is the way window management works as the focus is taken away the context menu is closed upon unfocus event.

I don't think this is a bug as @farseerfc also kindly pointed out.

I close this issue but feel free to comment and suggest re-opening it.

**Comment by vokamut** [comment]
@mmahmoudian Thanks. Yes, now I use the hotkey `Ctrl+Prt Sc` with a delay of 3 seconds
