### ISSUE TITLE
[Feature Request] Allow changing of paint tool colors during screenshot

### ISSUE THREAD

**Issue by douglasg14b** [flameshot-org/flameshot#472]
As the title puts it, the ability to change colors during screenshot time. Often different colors are used for different things (ie. black for boxing things out, red for arrows....etc)

**Comment by hosiet** [comment]
I thought we already have this feature from the very beginning. You may change the picked color at any time using the sidebar or color palette that pops up when you hold the right mouse button.

**Comment by douglasg14b** [comment]
Ah, right clicking does it. I was looking for a palette or color picker button in the controls that I can't seem to locate.

**Comment by hosiet** [comment]
The hint about how to use the palette will show up **every time** you enters the screenshot.

However, it seems that everyone is ignoring that little purple textbox :-/

**Comment by douglasg14b** [comment]
Oh I see.

I do some UX work here and there, here are my thoughts:

From a UI perspective anything in between the user and where they want to be (taking the screenshot) will be ignored or passed by, especially if it's something that's in their face all the time (tuned out). To compound the problem it's unstructured text, which is something users will also pass by even if it's not in their way.

I would recommend having a help button that shows the dialog next to it, with structured text (bulleted, or with icons) to break up the items.

_______________________________________

Side note on this topic: I would recommend highlighting button "groups" differently to break up visual clutter. A new user probably has to scan through each icon to figure out what they do (for the most part), this can be reduced by categorizing them in some way, or using different color schemes or shapes for those groups. A single color and shape for 17 different buttons makes for hard-to-distinguish clutter ( as far as at-a-glance goes).

**Comment by luzpaz** [comment]
I'm on a laptop and don't understand how to change color picker during screenshot

**Comment by douglasg14b** [comment]
Similarly, can we get a color palette for the color changer? There isn't a black/grey in there :/

@luzpaz  Right click. If your laptop doens't have dedicated buttons.... idk

**Comment by luzpaz** [comment]
Oh wow.. had no idea.
That's great. Only little snag is on my dual monitor setup, the color picker opens up in the other monitor, not the one I was wanting to make a screenshot in.

**Comment by elpddev** [comment]
Is there a way to change the color from a color picker/ rgb bar instead of the 9 hardcoded colors?

**Comment by dfredell** [comment]
@elpddev 
Are you talking when you are in a screenshot? Have you tried hitting the Space Bar while in a screenshot. Then you get the full color picker wheel/ triangle thing. 

Or you asking to modify the default 9 colors that are in the right click/ pop up circle of circles picker? I found in the code where they are defined, and it looks like you can override them but I don't know cpp well enough to see where the config file is defined.
https://github.com/lupoDharkael/flameshot/blob/cbb4727786a612d986f1830530f9b8028f08a205/src/utils/confighandler.cpp#L79

**Comment by elpddev** [comment]
@dfredell Thank for the answer. `Space bar` does not do anything while in screen capturing mode. Maybe I'm missing something.

**Comment by elpddev** [comment]
Ok, found out I had an older version where the `Spacebar` feature was not implemented yet. Installing version 0.6 solved my problem. @dfredell Thank you.

https://github.com/lupoDharkael/flameshot/issues/406

**Comment by NicolasGoeddel** [comment]
Wow. Thanks to this issue I also learned new things I had already known if I would read the small text box at the beginning of a screenshot.
I guess this issue can be closed, am I right?

**Comment by FSund** [comment]
Just found this issue when searching how to change the color. Perhaps an additional button around the selection could be added, that brings up the color picker (either the right-click version or the space-version) when clicked? It could perhaps look like a smaller version of the color wheel.

**Comment by mmahmoudian** [comment]
@FSund We are already getting some comments that the UI is too busy and cluttered. I don't think adding yet another button to the mix helps. Perhaps implementation of #887 can help us introduce the UI to user better.

**Comment by roynico** [comment]
Wow... glad to have found this thread: I used to use flameshot (that I like very much), and I had the impression that in the past it was possible to choose the color... and at some point I was not able anymore to find how ! :D right-click ... yes ... why didnt I think about it !

**Comment by FSund** [comment]
> @FSund We are already getting some comments that the UI is too busy and cluttered. I don't think adding yet another button to the mix helps. Perhaps implementation of #887 can help us introduce the UI to user better.

In my experience few users read a welcome screen, they usually want to get straight to using the app. Questions about more complex operations will typically arise after using an app for a while, at which point the welcome screen is long forgotten.

I do agree the UI has a lot of elements already, so I am not sure if a perfect solution exists.

**Comment by mmahmoudian** [comment]
@roynico as @FSund kindly pointed out, it is very common that our users skip reading the following message that appears every single time in the middle of the screen on which on the 3rd line explains the color picker 😃 :

![image](https://user-images.githubusercontent.com/390889/133242836-e41c404e-4cff-4253-a562-05907ae020aa.png)

There is perhaps a need for some UI improvements but they should be non-disruptive for the users. I believe our current approach is too much non-disruptive 😅  In case anyone has any suggestion, feel free to discuss that in [the discussions section](https://github.com/flameshot-org/flameshot/discussions) and/or on [Slack](https://join.slack.com/t/flameshotworkspace/shared_invite/zt-kx50keyc-H2GHTjQmmC4X2oRgSeDIVg).

**Comment by FSund** [comment]
> as @FSund kindly pointed out, it is very common that our users skip reading the following message that appears every single time in the middle of the screen on which on the 3rd line explains the color picker  :

I must admit I've never read any further than "Select an area with the mouse", and usually just hastily select the area I want to capture when using Flameshot. 

The best tools are tools that don't need any explanation, and are intuitive to use. Flameshot is 99% of the way there for me, with the color picker being the only thing that is missing something.

**Comment by mmahmoudian** [comment]
@FSund Missing what? Suggest/contribute that 1% 😉

**Comment by FSund** [comment]
@mmahmoudian I was thinking about what we are discussing in this issue, that the color picker itself is easy to oversee/forget about, and doesn't have an immediately obvious way to bring up.

**Comment by mmahmoudian** [comment]
@FSund We are thinking about adding a welcome page and possibly a "tip of the day". I might also record some YouTube/Odysee tutorials if/when I have time. If you have any suggestion about non-disruptive non-destructive way to tell user about features, let us know

**Comment by skironDotNet** [comment]
Same here "Glad to have found this thread explanation the big purple box I literally had not read until now!"
I read the box, and wondering what is side bar. Pressed space, shock! I can use different colors. 
Thanks!!!

**Comment by mmahmoudian** [comment]
@skironDotNet also give right-clicking a try.

**Comment by wonghoi** [comment]
> Oh I see.
> 
> I do some UX work here and there, here are my thoughts:
> 
> From a UI perspective anything in between the user and where they want to be (taking the screenshot) will be ignored or passed by, especially if it's something that's in their face all the time (tuned out). To compound the problem it's unstructured text, which is something users will also pass by even if it's not in their way.
> 
> I would recommend having a help button that shows the dialog next to it, with structured text (bulleted, or with icons) to break up the items.

You totally got me as a user. I read the startup tip the very first time, but only looked at and remembered what I needed for my first use, then tuned out and forgot the ones that I didn't need (like changing size and color) ever existed, so I had to google for it. I think the startup tip box's contents could benefit from repeating the hint in the tooltips that's relevant or just put it next to the other side of the selected region box. Startup tips (anything that gets into people's way from point A to point B) gets ignored a lot. Flameshot is a great tool nonetheless, but it's a shame the nifty features didn't get used much because of the UX

**Comment by 29-ux** [comment]
Enviado desde mi Huawei de Telcel.-------- Mensaje original --------De: wonghoi ***@***.***>Fecha: dom., 31 de julio de 2022 2:27 a. m.Para: flameshot-org/flameshot ***@***.***>CC: Subscribed ***@***.***>Asunto: Re: [flameshot-org/flameshot] [Feature Request] Allow changing of paint tool colors during screenshot (#472)

Oh I see.
I do some UX work here and there, here are my thoughts:
From a UI perspective anything in between the user and where they want to be (taking the screenshot) will be ignored or passed by, especially if it's something that's in their face all the time (tuned out). To compound the problem it's unstructured text, which is something users will also pass by even if it's not in their way.
I would recommend having a help button that shows the dialog next to it, with structured text (bulleted, or with icons) to break up the items.

You totally got me as a user. I read the startup tip the very first time, but only looked at and remembered what I needed for my first use, then tuned out and forgot the ones that I didn't need (like changing size and color) ever existed, so I had to google for it. I think the startup tip box's contents could benefit from repeating the hint in the tooltips that's relevant or just put it next to the other side of the selected region box. Startup tips (anything that gets into people's way from point A to point B) gets ignored a lot. Flameshot is a great tool nonetheless, but it's a shame the nifty features didn't get used much because of the UX

**Comment by ElonVampire** [comment]
收到！
