### ISSUE TITLE
Add Gentoo-related documentation to install Flameshot

### ISSUE THREAD

**Issue by jorgicio** [flameshot-org/flameshot#504]
Hi!

I'm the maintainer of the Flameshot package for Gentoo Linux. I have an overlay (non-official repository) on my Github repo. (Instructions to add it are there). Also, it's upgraded to the most recent version (0.6.0)
The package can be installed as usual, with the `emerge` command:

`emerge flameshot`

I'm on KDE and it works as expected and using as the default screenshot applications.

I'm open to suggestions or anything.

Thanks!

**Comment by treystout** [comment]
Thanks @jorgicio, installed your overlay, built fine.
BTW: he didn't link his overlay repo, it's here https://github.com/jorgicio/jorgicio-gentoo-overlay

**Comment by borgmanJeremy** [comment]
I am not a gentoo user but if you submit a PR with the gentoo instructions I can get it merged.

**Comment by jorgicio** [comment]
> I am not a gentoo user but if you submit a PR with the gentoo instructions I can get it merged.

I'll do, but I'm not maintaining this package anymore because it was merged to the Official Portage tree, so instructions may change.

**Comment by mmahmoudian** [comment]
@jorgicio I'm not a gentoo user and most of the terminology sounds alien to me 😅 . I tried to add some instructions about installing Flameshot on gentoo and I thought it should be as easy as `emerge media-gfx/flameshot` because it is in https://packages.gentoo.org/packages/media-gfx/flameshot but it seems it is not that easy as some people [have pointed out](https://forums.gentoo.org/viewtopic-p-8547837.html). I also found in your overlay the same type of path:
https://github.com/jorgicio/jorgicio-gentoo-overlay/tree/main/media-gfx/flameshot

This has add even more to my confusion. Is your overlay still the one that is the package in gentoo based on? How can we help to have the v11.0.0 on gentoo as well?

P.s: I also see @pavel-the-best among the maintainers on the gentoo website, hence tagging him here

**Comment by pavel-the-best** [comment]
I will prepare v11.0.0 version soon. I'm still a maintainer of the package, and it's not based on any overlay.
I believe that this issue was created before the package was brought to the main gentoo repository.

**Comment by mmahmoudian** [comment]
@pavel-the-best would you please give me some general instruction on how the Flameshot should be installed on gentoo. I want to add it to our website as well (of course you are most welcome to create the PR yourself if you wish so)

**Comment by pavel-the-best** [comment]
As all other packages, flameshot can be installed via simple `emerge -a gentoo`. Of course, this may be not a preferrable way of installation.
I think that just providing package name is better than having a command, from which you need to decode the name of the package in order to make some changes to it. It would also be definitely more compact. 
We have such a list of package names in README, and it even updates automatically. Why doesn't it work for the website?

**Comment by mmahmoudian** [comment]
@pavel-the-best I basically wanted to add the command in this page along with other distros: https://flameshot.org/docs/installation/installation-linux/

**Comment by pavel-the-best** [comment]
Ooops I thought about `emerge -a flameshot` and typed `emerge -a gentoo`. I'm sorry, the first one is, of course, the correct one.
