### ISSUE TITLE
Config file directory

### ISSUE THREAD

**Issue by Trollwut** [flameshot-org/flameshot#507]
Hey there!

Very cool tool here, also very lightweight, love it.

Where is the config file stored? I can't find any. Is there a chance to get it to something like `~/.config/flameshot/...`?

If this is not the default location, some parameter for it would be nice, like `flameshot --config=~/fs.conf gui`.

**Comment by greno4ka** [comment]
Config file is living here: .config/Dharkael/flameshot.ini

**Comment by Trollwut** [comment]
Thanks, found it!

**Comment by yichangshengwu** [comment]
god...
that should be in readme.md file !
wasted times to find it

**Comment by Trollwut** [comment]
I made a quick PR, just adding the dotfile location:

https://github.com/lupoDharkael/flameshot/pull/538

**Comment by danielrosehilljlm** [comment]
This would be very useful!

I have hidden the Flameshot notification icon (intentionally). However, I used to have a 'Configure Flamshot' in my Graphics menu (I'm on LXDE / Ubuntu) that no longer exists. 

Because there is no command line parameter other than hand-editing the .ini file I have no means of editing the configuration other than reinstalling the package!

**Comment by ikbelkirasan** [comment]
@danielrosehilljlm Try calling it from the terminal:

```shell
$ flameshot config
```

**Comment by mmahmoudian** [comment]
Considering that Flameshot has migrated to [Github organization](https://github.com/flameshot-org/), the config path will be modified and the whole config part in the codebase [will be refactored](https://github.com/flameshot-org/flameshot/issues/832#issuecomment-687819491). Stay tuned 😉
