### ISSUE TITLE
Unable to launch Flameshot v0.6.0+git37.8887b4e

### ISSUE THREAD

**Issue by ankushdas9** [flameshot-org/flameshot#555]
Tried installing it from the software center - installed successfully. However, when I launch it directly (or through a keyboard shortcut which I want to) - it doesn't do anything. I can't even see any processes running.

I'm rocking Zorin OS 15. It was working fine on Ubuntu 19.04, maybe the recent update caused this issue?

I'm not sure, just a heads up. Using Shutter as an alternative till then.

**Comment by StaggerLeee** [comment]
Seems as I have the same problem. Kubuntu 19.04.

**Comment by JenteVH** [comment]
> Seems as I have the same problem. Kubuntu 19.04.
> It works if I call GUI from console. And it works if taking screenshot is called from menu directly.

If you change the .desktop entry to run `flameshot gui` instead of just `flameshot` it should work as a temp workaround.

**Comment by StaggerLeee** [comment]
As instructed, it works:

> If you change the .desktop entry to run flameshot gui instead of just flameshot it should work as a temp workaround.

**Comment by JenteVH** [comment]
> As instructed, it works. Thank you.
> 
> > If you change the .desktop entry to run flameshot gui instead of just flameshot it should work as a temp workaround.

Glad it worked

**Comment by nettum** [comment]
Probably same error as https://github.com/lupoDharkael/flameshot/issues/522? There are also several other github issues on this.
It's only an issue when installing the snap package (but of course we want this instead of the old version in the apt-repo). 
The snap is broken, the rating and reviews in the software center also verify this: 
![image](https://user-images.githubusercontent.com/798156/61181871-2faab800-a62c-11e9-9b75-ddd4f279d06e.png)
A broken pacakge in the software center is unfortunate.  
This seems like a pretty easy fix so hopefully there will be an updated snap release sometime in the future.

**Comment by borgmanJeremy** [comment]
I believe this is fixed with the new snap @ZetaoYang has worked on.
