### ISSUE TITLE
Add a button to quick change systems settings to use flameshot instead default capturer

### ISSUE THREAD

**Issue by Ri0n** [flameshot-org/flameshot#644]
I already changed shortcuts settings once in Kubuntu to use flameshot and it was quite annoying to find everything necessary. No I installed new ubuntu and have to do that again.
Instead it would be great to have a button in flameshot like "Use me as a default screenshoter".

I understand it's very platform dependent. So where it's required to link with additional libraries then it can be implemented as a plugin (probably even compiled as a separate project). Or just use dbus/whatever DE provides.

My concern is KDE first of all :)

**Comment by elcolie** [comment]
Me too. I am running GNU/Linux Debian with Cinnamon. I need to use mouse click every time

**Comment by borgmanJeremy** [comment]
I don't think we can really support this since it is so platform dependent and we need to maintain it every time the DE bumps the API.

**Comment by mmahmoudian** [comment]
@Ri0n you can export your custom keyboard shortcuts in KDE and later import it in another KDE. There is also a new kid in the block named "[konsave](https://github.com/Prayag2/konsave)" that is aiming to backup the KDE configs so that they can be shared with others. I wonder if they also include the keyboard shortcuts.

@elcolie try assigning a keyboard shortcut for `flameshot gui`. I'm not familiar with cinnamon, but perhaps this page can be helpful if you don't know how: https://www.addictivetips.com/ubuntu-linux-tips/customize-keyboard-shortcuts-on-cinnamon/
