### ISSUE TITLE
Crashes when you do anything other than save

### ISSUE THREAD

**Issue by dps910** [flameshot-org/flameshot#657]
**Flameshot version**

Latest

**Describe the bug**

When clicking on any option other than save, flameshot crashes. I can't copy, and have to kill process using htop. Running Arch Linux + i3wm

**To Reproduce**

run flameshot
select somewhere you want to take a screenshot of
click copy, or anything else I think
crash

**Expected behavior**

I expect it to copy to clipboard

**System Information**

See above

**Comment by chux0519** [comment]
Similar problem to me.
I can only save to disk, when I tried to copy to clipboard, it stuck for a really long time, or sometimes just crash.
Using latest flameshot too, also I'm a i3wm and arch user

**Comment by lihuelworks** [comment]
Using Flameshot 0.6.0 on KDE (Kubuntu). Copying with either the hotkey or the button freezes my machine, and I have to wait around 10 seconds before it crashes.

**Comment by chux0519** [comment]
I think I solved this problem **temporarily**.
It seems that when copy is executed, the entire system is blocked after the dbus related API is called, so I temporarily deleted it.
The PR **may not** be merged, because I deleted part of the logic of the notification part when copy is executed.
Anyway, If someone encounters the same problem, you can try the following modifications

```
--- a/src/utils/screenshotsaver.cpp
+++ b/src/utils/screenshotsaver.cpp
@@ -29,8 +29,6 @@ ScreenshotSaver::ScreenshotSaver() {
 }

 void ScreenshotSaver::saveToClipboard(const QPixmap &capture) {
-    SystemNotification().sendMessage(
-                QObject::tr("Capture saved to clipboard"));
     QApplication::clipboard()->setPixmap(capture);
 }
```

see https://github.com/chux0519/flameshot/tree/fix-copy-blocking

**Comment by lihuelworks** [comment]
Tried with KDE (Kubuntu). Copy doesn't crash, but it doesn't paste anything either. That may have to do with KDE, but copying and pasting images works as intended with other apps.

**Comment by chux0519** [comment]
I found that this may be related to the notification system of the operating system. When I use i3wm without any notification server, the code related to the notification will be stuck.

After installing dunst (a notification server), the notification is normal and the function will not be affected

In my case, after installing `libnotify`(notification client) and `dunst`(notification server)，and start dunst, the problem is solved, hope it helps.

**Comment by avindra** [comment]
This is probably a duplicate of #635

**Comment by mmahmoudian** [comment]
Since the 0.8 has squished many bugs, I suggest you test the [version 0.8](https://github.com/flameshot-org/flameshot/releases/latest) and comment here if the issue persists. Otherwise I will close this issue in 14 days in favor of 0.8

**Comment by jolars** [comment]
I just had this problem right now, running Fedora 35 + i3wm
