### ISSUE TITLE
[Feature] Invert Color

### ISSUE THREAD

**Issue by GetCurious** [flameshot-org/flameshot#689]
I'd like to invert colors with a click of a button.
it'll be super convenient for me not to switch to an editor every time.

**Comment by AndydeCleyre** [comment]
Since "inversion" would be handy for at least one uncolored tool (#165), maybe a unified way of triggering it would be nice, like invert if the user is holding down shift while using the tool.

Although I guess that wouldn't be any good for tablet/keyboardless users . . .

**Comment by void-m4110c** [comment]
Hi, is there any news about this feature? I really need it because my shells all have a dark background and in reports etc. it looks better if they are bright/white...
Something like "Invert Color" in Greenshot...

Thanks in advance

**Comment by mmahmoudian** [comment]
@void-m4110c how about using imagemagic for the time being?

```sh
flameshot gui -r | convert png:- -invert -channel RGB png:- | xclip -selection clipboard -t image/png
```

I'm typing this on the phone and haven't tested it, but technically it should work. Just make sure you have ImageMagic and xclip installed.

**Comment by void-m4110c** [comment]
Yep, this really is a viable solution, just need to map a key for that (don't want each and every screen shot to be inverted).

Thanks for the suggestion and fast reply!

**Comment by mmahmoudian** [comment]
I'm glad that it helped. I myself have a small shell script that runs a `dmenu` (i think you can do the same with `rofi` as well) that it asks what type of weird screenshot I want. Normal <kbd>prntscrn</kbd> is mapped to `flameshot gui` but <kbd>Shift</kbd>+<kbd>prntscrn</kbd> opens that dmenu and asks me what type of screenshot I want. You can do the same if this inversion of colour is not something that you would need every day. This way you can use one shortcut for all your non-regular screenshots.

**Comment by void-m4110c** [comment]
I'm using i3-wm and have mapped `Winkey`+`prntscrn` to `flameshot gui`, and now additionally `Winkey`+`Shift`+`prntscrn` to the given command above.

Your `dmenu` solution is also a great idea, as I use it already as a password-manager and program starter. Just need look into setting it up that way, but that shouldn't be a big deal.

**Comment by void-m4110c** [comment]
Would you mind sharing your dmenu script?

**Comment by mmahmoudian** [comment]
@void-m4110c I cleaned the code and put it in a repo:
https://codeberg.org/mehrad/dmenu_shot

Enjoy and feel free to make pull requests ;)

**Comment by void-m4110c** [comment]
Thanks mate, really nice!

Yeah, if the time permits it, I will!

**Comment by mmahmoudian** [comment]
@Cr4ckC4t considering that you have already went through the trouble of writing the code and get it working, I would be thankful if you create a pull-request and also mention this thread in the description.

Since you asked for suggestions, it would be interesting to have also some option to do other color modifications (sepia, black-and-white). For example after clicking this button, the sidebar opens with some options to choose from.


@borgmanJeremy do you think the concept of opening the sidebar for letting users to choose options is viable? For example the "upload to imgur" button can become "upload" and then the sidebar can open up and the user chooses whatever options we have there (e.g imgur, tumblr, 0x0, etc.)

**Comment by Cr4ckC4t** [comment]
@mmahmoudian I think this issue can be closed now. The inverter tool was added in the PR from above (#1849).
