### ISSUE TITLE
Double click on ubuntu: black overlay above my window

### ISSUE THREAD

**Issue by guettli** [flameshot-org/flameshot#691]
If I open the GUI of flameshot via double click on ubuntu, then there is a black overlay above my window

See screenshot.

I don't want to see "Configuration, Information, Quit"

**Flameshot version**

Flameshot 0.5.1-1(Debian)
Compiled with QT 5.9.4

![image](https://user-images.githubusercontent.com/414336/75611851-7ea35000-5b1e-11ea-8a48-cce3ddfe7afc.png)

**System Information**
VERSION="18.04.4 LTS (Bionic Beaver)"

**Comment by mmahmoudian** [comment]
@guettli This issue is old and as you might have realized, we have moved the project into an organization and have improved the code and fixed many bugs in the process. Please checkout the newest version and see if the issue still persists.

Fir now I'll close the issue, but feel free to reopen it if you still find the same bug in the latest version.
