### ISSUE TITLE
Flameshot doesn't work in Ubuntu 18.04 64 bit.

### ISSUE THREAD

**Issue by Julius-Nepos** [flameshot-org/flameshot#717]
**Flameshot version**

There is the Flameshot Icon in the system tray.   However left-clicking on it just opens a very basic panel of configuration options.

**Describe the bug**

**To Reproduce**

**Expected behavior**

I'd expect it to open somethin letting me select a screen region or save a whole screen screenshot.  But nothing seems to happen.
**System Information**

Laptop, i7-core, 12 GB ram, Unbuntu Linux v 18.04.

**Comment by shukerov** [comment]
I believe you are trying to open the configuration options instead of launching the application. I am running Ubuntu 18.04 64 bit, and everything is running just fine.

I suggest you change the Flameshot Icon in the system tray with the correct one. When I hit my  `Super` key and type Flameshot three separate flameshot icons show up. Click on the one that has `Take a Graphical screenshot` as a description.

Optionally open a terminal and run `flameshot gui`. This should bring up the screen you are expecting.

**Comment by cdcsit-maheshyadav** [comment]
I was using it in 18.04 before. Now, I am using it in 20.04. It works fine.

**Comment by Julius-Nepos** [comment]
Well, I've not going to change my OS simply to see if flameshot works.  The computer is used for engineering projects and there are many other apps involved.

Also I should clarify.  I'm using Xubuntu 18.04 64-bit.  This uses the XFCE desktop rather than Gnome.  I'll try the rocommendations posted above and reply.

**Comment by DouglasLapsley** [comment]
I'm having this issue too.  Worked fine on Ubuntu 16.04 and 20.04, but on 18.04.4 the tray icon that appears at the top right only gives options "Configuration", "Information" and "Quit".

If I go to "Show applications" menu at bottom left and search on "flam" I see that there are three icons there.  "Configure..", "Launch..." and "Take graph...".  The last of these does launch the screen grabbing view, but you can't use it because it's over the applications list.

This was installed using `sudo apt install flameshot`.

**Comment by faelsoto** [comment]
I'm on 16.04 and I'm observing the same. I have a PC on 20.04 and everything works fine, what is weirder is that if I launch it via console (`flameshot gui`) I can start taking screenshots right away, but if I configure it as a keyboard shortcut, nothing happens.

**Comment by DouglasLapsley** [comment]
I've found that if you launch the "Take Graphical Screenshot" app then you can "Add it to favourites" and then it will work as normal(ish).

**Comment by anuragjk** [comment]
I'm also have the same issue as @DouglasLapsley  
I figured if you double-click system tray icon "Take Graphical Screenshot" app will get launched.
---
Ubuntu 18.04
intstalled with command: `sudo apt install flameshot`

**Comment by DouglasLapsley** [comment]
Just tried that.  Thank you yes, that works!  Very handy to know.

**Comment by borgmanJeremy** [comment]
I read through this issue tonight and I'm not 100% sure what the issue is. Can you explain in more detail if there is still a problem? Perhaps try installing the latest version from snap?

Specifically as a KDE user I am confused by
```
The last of these does launch the screen grabbing view, but you can't use it because it's over the applications list.
```
