### ISSUE TITLE
Image name formatting prints an space when the number representation of a day is one-digit.

### ISSUE THREAD

**Issue by ghost** [flameshot-org/flameshot#733]
**Flameshot version**

```
$ flameshot --version
Flameshot v0.6.0
Compiled with Qt 5.14.1
```

**Describe the bug**

When using the following format for saving screenshots

```
$ flameshot config -f %Y_%m_%e__%H_%M_%S
```

Days are expected to be two digits, a space is used when a day is printed with one digit (see below)

```
$ ls -A1 ~/Pictures/ss
2020_04_30__12_16_26.png
2020_04_30__21_57_49.png
'2020_05_ 1__14_42_18.png'
'2020_05_ 1__14_51_15.png'
```

**To Reproduce**

1. Execute the following command (it's the same one that was presented above) to change the name with which screenshoots are saved.

```
$ flameshot config -f %Y_%m_%e__%H_%M_%S
```

2. Capture an screenshoot.

**Expected behavior**

One-digit days must be printed by using a single character or inserting an space before the digit character.

**System Information**

Arch Linux. `flameshot` was obtained by executing the following command

```
pacman -S flameshot
```

**Comment by borgmanJeremy** [comment]
Confirmed this is still an issue for the upcoming release.

**Comment by 0x4d6f6c666172** [comment]
@znm241 
Thank you for reporting this behavior. 

I decided to take a look at it and discovered that this is not quite an issue but rather an expected behavior of specified formatter. However, speaking of your concern, in order to get rid of it would be to use the following format specifier `flameshot config -f %Y_%m_%d__%H_%M_%S` instead of `flameshot config -f %Y_%m_%e__%H_%M_%S`. Could you please try this new format and let me know if it solves your issue? Thanks.

@borgmanJeremy 
I wouldn't consider this as a bug since this is an expected behavior of C++ standard library `strftime` function, which is used in source code for file name formatting, please see here https://github.com/flameshot-org/flameshot/blob/master/src/utils/filenamehandler.cpp#L48.

The section "Day of the year/month" from `strftime` documentation https://en.cppreference.com/w/cpp/chrono/c/strftime says 
that `e` specifier

>  'writes day of the month as a decimal number (range [1,31]). Single digit is preceded by a space.'

 whereas `d` specifier 

> 'writes day of the month as a decimal number (range [01,31])'

**Comment by borgmanJeremy** [comment]
@0x4d6f6c666172 Thanks for looking into this! Maybe we should update the "flameshot config --help" info to state which specification we are formatting to.

**Comment by 0x4d6f6c666172** [comment]
@borgmanJeremy, actually, the "documentation" is there, although I assume it is not so explicit as desired. Pease see screenshot below:
![image](https://user-images.githubusercontent.com/4803757/98596858-ba62fc00-22e0-11eb-9aa2-4970ecd957a8.png)



My apologies for a delayed response.
