### ISSUE TITLE
Save to configured folder with counter in filename

### ISSUE THREAD

**Issue by thepisu** [flameshot-org/flameshot#751]
Main feature request: adding an automatic counter in the filename, like Shutter does.

For example, with this naming: **screenshot_%NNN**
It generate sequence filenames like: screenshot_001.png, screenshot_002.png, and so on.

The counter is calculated from current files in save folder, for this reason I have opened a single issue for "save to configured folder" and "counter in filename", because with the current behaviour that ask for save folder every time, it's not possibile to calculate the counter (the proposed folder may not be the really selected folder).

**Comment by DavertMik** [comment]
This is awesome feature of Shutter and it would be nice to have autosaving in Flameshot as well

**Comment by davidfelipeb** [comment]
This could be a very good addition. Sequencial naming is useful in a lot of situations, I really hope this gets some attention!

**Comment by chockie** [comment]
Logged in to my Github account for the first time in 5-6 years just to try bringing extra attention to this. I've been using Flameshot for a year or so now on my Linux machine but I just switched to it from Lightshot on my Windows pc because Lightshot saved filenames with the counter hits a max cap of 9999 for some reason (I'm an image hoarder). I really like the sequential naming system and find it very handy and readable, and the auto saving (ctrl+s to directly save to the last file path with an automatically generated name without the prompt for the file path- ideally with the counter automatically incremented or with the current timestamp) would also be a fantastic feature.

**Comment by mmahmoudian** [comment]
@veracioux haven't you already implemented this in #1815? Because it was part of the `path_option.sh` if I recall correctly.

**Comment by veracioux** [comment]
It was already implemented before. But it was of the format `screenshot_1`, `screenshot_2`, etc. The numbers were not padded with zeros to a fixed width. I just left it as it was.

**Comment by mmahmoudian** [comment]
So to sum up, at the moment the counter will be appended to the end of the file name without any leading zeros.

@thepisu & @DavertMik & @davidfelipeb  & @chockie Would this be suffice or you would like to be able to have the leading zeros (e.g `_005` in case of `_%NNN`) and/or you want to be able to specify where on the name the counter appears (e.g `screenshot_%NN_%F_%H-%M`)?

**Comment by extr15** [comment]
Thanks for your work.
Just for clarify, this `counter in filename` feature works, you just need to set the prefix in `Configuration -- Filename Editor`, e.g. `test`(not `test_%N`), and the first screen capture is `test.png`, the second will be `test_1.png` automatically!
I write this because I thought it doesn't work when I saw the first image is `test.png` instead of `test_1.png`...
