### ISSUE TITLE
Unbundle qtsingleapplication

### ISSUE THREAD

**Issue by pavel-the-best** [flameshot-org/flameshot#754]
QtSingleApplication is now included in the Qt 5 standard.
There is no more need in bundled singleapplication.

**Comment by hosiet** [comment]
I do not believe one can find `QtSingleApplication` support in any community Qt 5 distribution.

If the `QtSingleApplication` you are referring to is this one (https://repology.org/project/qtsingleapplication/versions , or https://github.com/qtproject/qt-solutions/tree/master/qtsingleapplication), I have to point out that it is not packaged in any deb-based Linux distributions and Arch Linux-based distributions. This is an external implementation though somehow a _de facto_ official implementation since it's under qtproject's namespace on GitHub.

The current bundled qtsingleapplication implementation is from https://github.com/itay-grudev/SingleApplication . This library has been packaged in deb-based Linux distributions and can be found at https://tracker.debian.org/pkg/singleapplication .

I have no objections on unbundling the library. However, in order to support older Linux distributions and distributions that does not provide this library, we should keep the source code copy here and provide a CMake-based build-time option to let the user decide whether to use the bundled copy or external library. It is also current flameshot maintainers' decision on which singleapplication implementation should they be using (qtproject's or itay-gradev's).

**Comment by pavel-the-best** [comment]
@hosiet done in #1598.
Fixed in https://github.com/flameshot-org/flameshot/commit/6a2765f15e4fb8f98d7201f1ecac8602e186674c
