### ISSUE TITLE
Newest KDE does not allow you to map 'Print' key to FlameShot

### ISSUE THREAD

**Issue by jeffangelion** [flameshot-org/flameshot#796]
Hi, I'm writing it more like **caution** for others: now you cannot map 'Print' key to taking a screenshot via FlameShot. Tried in `KDE Plasma 5.19.3`
If anyone has a clue/hack to work it around  ‒‒ **please** leave it in comments
I hope @33kk and @DrunkenPoney will notice this issue

**Comment by borgmanJeremy** [comment]
How did you map it previously?

**Comment by 33kk** [comment]
Did you import [this file](https://github.com/lupoDharkael/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde) or added shortcut manually?

**Comment by jeffangelion** [comment]
> How did you map it previously?
Through global keymap settings
> Did you import [this file](https://github.com/lupoDharkael/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde) or added shortcut manually?
Import did not work for me nor manual adding

**Comment by LinuxOnTheDesktop** [comment]
Cf. #717, #773 and perhaps other reports on this tracker. Those others might include problems on Mint - which has its own problems with such basic things as keyboards shortcuts; see for instance [here](https://github.com/linuxmint/cinnamon/issues/3981).

**Comment by wazlecracker** [comment]
What I did to work around this since flameshot hasn't worked properly with hotkeys since Plasma 5.19 is I created a custom shortcut in System Settings > Shortcuts > Custom Shortcuts. Create a new global shortcut based on command/URL, set the trigger to Print and the action as the command `flameshot gui`.

**Comment by nyanpasu64** [comment]
KDE Plasma 5.19.4. Importing didn't work, before or after unbinding Spectacle. But setting Print manually worked after unbinding Spectacle.

**Comment by mmahmoudian** [comment]
@nyanpasu64 I have the same KDE and it works fine for me (I initially imported it from the [flameshot-shortcuts-kde](https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde) file.):

![image](https://user-images.githubusercontent.com/390889/92303057-28561480-ef7a-11ea-95c8-2662dcc5d972.png)

**Comment by marcozaccari** [comment]
Kubuntu 20.04, Plasma 5.18.5

In the KDE settings, Shortcuts section, the Remote application should be `org.dharkael.Flameshot` instead of `org.flameshot.Flameshot`.
Searching by D-Bus Browser confirms this settings.

**Comment by mmahmoudian** [comment]
@marcozaccari is correct for the current version if Flameshot (version 0.6), but as [it has been explained](https://github.com/flameshot-org/flameshot/issues/858#issuecomment-688501506), in the upcoming version, the dbus name is changed to `org.flameshot.Flameshot` for the upcoming release and also for the git builds. Stay tuned for the new release as it has quite a few bug fixes and new features as they are for now briefly listed in #844

**Comment by borgmanJeremy** [comment]
@mmahmoudian Can we close this issue or is there more work to do?

**Comment by mmahmoudian** [comment]
@borgmanJeremy there is one thing left to do which closes multiple issues. I discussed the bug with @ZetaoYang on Slack to make sure my understanding of it is correct.

At the moment many people are facing issues running Flameshot simply because `flameshot gui` fails if the Flameshot is not already open in the background (I personally tried it on 0.6 on Ubuntu 18.04, and on 0.8 Manjaro). For now the trick is to run a `flameshot &` and then run other subcommands of Flameshot such as `flameshot gui` or `flameshot config`. This is regardless of DE or WM, but because the shortcut if the thing that breaks, people think it is KDE or Xmonad's problem.

What needs to be done is that Flameshot always checks if a Flameshot instance is running in the background and if not, run one instance in the background first and the execute the subcommand.

**Comment by hosiet** [comment]
Just as I said in #879 , I somehow disagree with the analysis above.

The reason behind having to run a plain "flameshot" first before running subcommands is fundamentally because the activation of flameshot via D-Bus somehow failed. There could be multiple reasons:

1. An invocation of "flameshot gui" will send a message on D-Bus telling the user session to do a "flameshot gui" thing and **have itself immediately exits**. ← be aware of this behavior
2. If there is already a flameshot instance running in background, that flameshot instance will receive the message through D-Bus and execute it.
3. If there was no flameshot running in background, this D-Bus message will **bring up a background flameshot running instance and send the request to the new instance**. This is called D-Bus Activation ( https://specifications.freedesktop.org/desktop-entry-spec/1.1/ar01s07.html ).

* * *

As said in #879 , this marks an uncommon dependency on a working user D-Bus session. Things could go really wrong if that D-Bus environment is not properly working. For example:

* If the D-Bus activation could not find the proper binary to start. **This happens to the flameshot v0.6.0 .deb package for Ubuntu on current GitHub release page due to hard coding nonexistent /usr/local/bin/flameshot and was never fixed.**
* If there are no user D-bus sessions available. This applies to some bug reports of WM users.

I agree that the extensive use of D-Bus is problematic in some cases, but such design is agnostic to whether there are any flameshot instances running. If we fall back to manual detection, sending messages via D-Bus would be meaningless.

My point is that we need careful consideration about redesign of this part (detection, subcommand and D-Bus activation).

**Comment by Nisc3d** [comment]
After the Update to 0.8 yesterday my shortcut also stopped working. I removed the shortcut file and readded it. But still nothing.
Then I manually made a shortcut that starts flameshot gui and that worked. 
Flameshot was always running in the Background.
I have Plasma 5.19.5 on Arch Linux.

**Comment by mmahmoudian** [comment]
@Nisc3d can you post a screenshot here from your keyboard shortcut window to demo how you have manually set it.

**Comment by Nisc3d** [comment]
![grafik](https://user-images.githubusercontent.com/7361310/93903237-b3643800-fcf8-11ea-8e00-f50844436806.png)
![grafik](https://user-images.githubusercontent.com/7361310/93903276-be1ecd00-fcf8-11ea-92a9-872f8d91496e.png)
I hope this helps.

**Comment by mmahmoudian** [comment]
@Nisc3d yours does not run D-Bus but the [flameshot-shortcuts-kde](https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde) correctly sets the D-Bus:

![image](https://user-images.githubusercontent.com/390889/93904281-5c636080-fd02-11ea-9171-f10f8d2b4549.png)

**Comment by Nisc3d** [comment]
Yes and this doesn't work for me.

**Comment by maksymov** [comment]
any news with this?

**Comment by borgmanJeremy** [comment]
No, I am unable to replicate it on arch  / KDE.

**Comment by mmahmoudian** [comment]
@maksymov I have a hunch that this situation is related to #960. Please try the steps I mentioned [here](https://github.com/flameshot-org/flameshot/issues/960#issuecomment-697470409) and let us know if it fixes the issue.

**Comment by ManosGEM** [comment]
> Kubuntu 20.04, Plasma 5.18.5
> 
> In the KDE settings, Shortcuts section, the Remote application should be `org.dharkael.Flameshot` instead of `org.flameshot.Flameshot`.
> Searching by D-Bus Browser confirms this settings.

Using org.dharkael.Flameshot solved the issue for me. I'm using KDE Plasma 5 on Debian 10. 
Thanks.

**Comment by borgmanJeremy** [comment]
Are you on a pre 0.8.x release?

**Comment by dude1phoenix** [comment]
> Kubuntu 20.04, Plasma 5.18.5
> 
> In the KDE settings, Shortcuts section, the Remote application should be `org.dharkael.Flameshot` instead of `org.flameshot.Flameshot`.
> Searching by D-Bus Browser confirms this settings.

That stiil work for KDE Plasma 5.18.5 \ Flameshot 0.6.0

**Comment by mmahmoudian** [comment]
@dude1phoenix your Flameshot version is very old. Please consider updating to the latest version. You can use Snap, Flatpak or AppImage if your distribution doesn't have the latest Flameshot version in their repo. Alternatively you can build from source.

For further information please visit https://flameshot.org/guide/installation/installation-linux/

**Comment by sep2** [comment]
For anyone in Arch/KDE new to this, pleae import the [latest file (Feb 7, 2022)](https://github.com/flameshot-org/flameshot/blob/master/docs/shortcuts-config/flameshot-shortcuts-kde.khotkeys).

See [instruction](https://flameshot.org/docs/guide/key-bindings/) here.

**Comment by woodsleaf** [comment]
> ![grafik](https://user-images.githubusercontent.com/7361310/93903237-b3643800-fcf8-11ea-8e00-f50844436806.png) ![grafik](https://user-images.githubusercontent.com/7361310/93903276-be1ecd00-fcf8-11ea-92a9-872f8d91496e.png) I hope this helps.

Thanks for example.

**Comment by woodsleaf** [comment]
In Cyrillic localization it looks like this:
![dRVr374_038](https://user-images.githubusercontent.com/18559447/161396231-7ed5054c-5b1d-4235-85a1-f85d1a81a02c.jpg)
Console command version
![FTJZVDiBwRg](https://user-images.githubusercontent.com/18559447/161396230-b6f9f77e-5cb0-4286-be80-e2b94d6332b9.jpg)
D-Bus version
![0-qwL5vOWmU](https://user-images.githubusercontent.com/18559447/161396233-9497ab9b-5d52-456a-898e-edd07061ae4e.jpg)
 
P.S.: KDE Plasma 5.20.5.

**Comment by marufmax** [comment]
+1 not working for me also
