### ISSUE TITLE
Flameshot crashes on KDE Plasma when saving screenshot or trying to open "Configuration"

### ISSUE THREAD

**Issue by coyotefoxtrot** [flameshot-org/flameshot#805]
**Flameshot version**
v0.6.0

**Describe the bug**
When I try to save a screenshot, Flameshot crashes. It also crashes when I right-click the icon and select "Configuration". Selecting "Information" works fine, it opens the panel and doesn't crash.

**To Reproduce**
Open Flameshot through Application Launcher or the terminal, take a screenshot and select the save button or right-click the icon and select "Configuration".

**Expected behavior**
Saving a screenshot should save it to the directory, selecting "Configuration" should open the "Configuraton" panel.

**System Information**
Manjaro 20.1
KDE Plasma 5.19.4

**Comment by borgmanJeremy** [comment]
I am unable to replicate this on KDE/Arch using the latest flameshot version. Could you try the latest version built from source? Or since you are on Manjaro you can try flameshot-git from the AUR.

Otherwise we will shortly have an official release out you can test from the official Arch repo.

**Comment by borgmanJeremy** [comment]
Could you please test on version 0.8 that was just released?

**Comment by rtemiuz** [comment]
@coyotefoxtrot check yours locales:
```bash
locale
```
I had similar issue with `locale: Cannot set LC_ALL to default locale: No such file or directory`. After fix this, `flameshot` works well.

**Comment by VAggrippino** [comment]
I'm having the same problem on Kubuntu with flameshot 0.6.0+git20191001-2 from the Ubuntu repo.

My locales are all set properly.

Oddly, it doesn't crash if I run it from the terminal.

I wonder if there's something wrong with the configuration of the `.desktop` file. There are three `Exec=` lines.
- One under the `[Desktop]` section: `Exec=flameshot`
- One under the `[Desktop Action Configure]` section: `Exec=flameshot config`
- One under the `[Desktop Action Capture]` section: `Exec=flameshot gui --delay 500`

I don't know much about the syntax of the `.desktop` files.

If I run `flameshot config` from terminal, nothing happens and the exit status (`echo $?`) is still 0.

If I run `flameshot gui --delay 500` from terminal it will allow me to select an area of the screen, but crash when I try to save it. Exit status is still 0.

Since the exit status is 0, is it really crashing? Or is it just exiting normally at an unexpected time?

**Comment by borgmanJeremy** [comment]
Could you please retest with the latest release?

**Comment by VAggrippino** [comment]
Almost the same behavior from Flameshot v0.8.3 from `flameshot-0.8.3-1.ubuntu-20.04.amd64.deb` on the releases page. With this version I can open configuration, but I still can't save an image.

**Comment by borgmanJeremy** [comment]
@VAggrippino  Is this on X11 or Wayland?

**Comment by VAggrippino** [comment]
I'm using X11. As far as I know, all Ubuntu derivatives use X11.

**Comment by krivahtoo** [comment]
I had the same on my Manjaro KDE

`LC_ALL=C flameshot` Worked for me

**Comment by SamantazFox** [comment]
> Are you comfortable hooking up a debugger and poking around? If the locale is set correctly I am not sure what the issue is since I cannot replicate it.

```
Reading symbols from flameshot...
(No debugging symbols found in flameshot)
(gdb) ru gui
Starting program: /usr/bin/flameshot gui
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3959700 (LWP 773171)]
[Thread 0x7ffff3959700 (LWP 773171) exited]
[Inferior 1 (process 773167) exited normally]
(gdb) bt
No stack.
(gdb) 
```

**Comment by maguilara** [comment]
If I launch using "flameshot" via command, it works fine, but if launch via "flameshot gui" it crashes/closes when saving a file/uploading to imgur/clicking on configuration. Launching using "flameshot &" via cli, works okay, but if I modify the .desktop file adding the "&" thingy and launch the app using the menu application, it still crashes. ANyway I can help?

**Comment by borgmanJeremy** [comment]
@maguilara Can you post your config file?

**Comment by maguilara** [comment]
> @maguilara Can you post your config file?

I suppose you mean flameshot.ini
`[General]
disabledTrayIcon=false
drawColor=#ff0000
drawThickness=0
saveAfterCopyPath=/home/USER/Pictures
savePath=/home/USER/Downloads
savePathFixed=false
showStartupLaunchMessage=true
startupLaunch=true

[Shortcuts]
TYPE_ARROW=A
TYPE_CIRCLE=C
TYPE_CIRCLECOUNT=
TYPE_COPY=Ctrl+C
TYPE_DRAWER=D
TYPE_EXIT=Ctrl+Q
TYPE_IMAGEUPLOADER=Return
TYPE_MARKER=M
TYPE_MOVESELECTION=Ctrl+M
TYPE_MOVE_DOWN=Down
TYPE_MOVE_LEFT=Left
TYPE_MOVE_RIGHT=Right
TYPE_MOVE_UP=Up
TYPE_OPEN_APP=Ctrl+O
TYPE_PENCIL=P
TYPE_PIN=
TYPE_PIXELATE=B
TYPE_RECTANGLE=R
TYPE_REDO=Ctrl+Shift+Z
TYPE_RESIZE_DOWN=Shift+Down
TYPE_RESIZE_LEFT=Shift+Left
TYPE_RESIZE_RIGHT=Shift+Right
TYPE_RESIZE_UP=Shift+Up
TYPE_SAVE=Ctrl+S
TYPE_SELECTION=S
TYPE_SELECTIONINDICATOR=
TYPE_TEXT=T
TYPE_TOGGLE_PANEL=Space
TYPE_UNDO=Ctrl+Z`

**Comment by Brutus5000** [comment]
I can confirm the issue on Arch Linux on X11, KDE Plasma 5.20.4 with Flameshot v0.8.5 (Compiled with Qt 5.15.1)

If I call it from CLI with `LC_ALL=C flameshot` all works.
But if I call just via `flameshot` and go to configuration ti crashes with:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```

**Comment by unlocomqx** [comment]
This helped me https://askubuntu.com/a/745855/395192

**Comment by deimosian** [comment]
I had this issue on Arch/KDE. TL,DR: It was a locale problem.

Going into /etc/locale.gen, I found en_US.UTF-8 was commented out. Uncommenting it and running locale-gen resolved the issue. The odd thing is that this was on a relatively new install, about a week old, and I know I had set the locale per the official guide. 

I would still call this an issue because, in my opinion, Flameshot should be falling back to some default, not just crashing. 

Before:

`$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

After:

`$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

**Comment by borgmanJeremy** [comment]
@deimosian I don't think there is a good way to do that based on how QT handles locales: https://wiki.qt.io/Locales

It relies on the underlying OS to properly report the locale information.

**Comment by borgmanJeremy** [comment]
flameshot for sometime emits and error and falls back to a default if no locale is set.
