### ISSUE TITLE
Host Releases On Github

### ISSUE THREAD

**Issue by borgmanJeremy** [flameshot-org/flameshot#861]
When the 0.8 version is released I would like to host the binaries on github. This will especially help out the windows users.

**Comment by hosiet** [comment]
It seems that we need to provide binary packages on GitHub for the following systems:

* Windows
* Ubuntu 20.04 LTS
* Ubuntu 18.04 LTS
* Debian Testing/Sid (via Debian's official repository, not GitHub)
* Debian 10 (GitHub first, maybe Debian's official repository later)
* Debian 9
* Fedora 32
* Fedora 31

* * *

Actually the windows build is still at a very early beta stage and the whole toolchain need to be automated. Maybe we can release a windows build as a "beta" release and make some official Windows release in v0.9. It would even be better if we can release on Windows' package manager repos, like NuGet or chocolatey.

**Comment by borgmanJeremy** [comment]
Do you know if there is an issue with windows stability or just the toolchain to build it? I have it building in appveyor right now but I still need to tie it into github actions. 

I am fine labeling it as a "beta" release for 0.8.

Thanks for identifying all the packages.

**Comment by hosiet** [comment]
I don't see a stability issue; it's mostly about how to properly set up the toolchain and which toolchain should we be using (MSVC or MINGW).

The major part is that we will need to disable D-Bus part completely since Windows does not have D-Bus. I'm not sure how that will affect the stability of windows build. I believe #29 has discussion of last round's windows release of v0.6.0 and @ZetaoYang knows more than me.
