### ISSUE TITLE
Feature request: follow symlinks for configuration files

### ISSUE THREAD

**Issue by figsoda** [flameshot-org/flameshot#897]
Flameshot doesn't recognize `~/.config/Dharkael/flameshot.ini` if it is symlinked from another file. It would be helpful if flameshot can follow symlinks.

**Comment by borgmanJeremy** [comment]
Symlinks are working okay for me. Are you certain the symlink is created properly? Here is the process I followed (note my config location is different since i am working off the master branch).

```
cd ~/.config/flameshot
mv flameshot.ini ~/flameshot.ini
ln -s ~/flameshot.ini .
```

Then I checked the symlink was correct with:
```
file flameshot.ini
cat flameshot.ini
```

If that doesn't work you can try on master or wait about 1 week for the 0.8 version to be released.

**Comment by figsoda** [comment]
It's working now, I must have done something wrong. Thanks!
