### ISSUE TITLE
Circle counter tool does not show size indicator (Windows, Linux)

### ISSUE THREAD

**Issue by hosiet** [flameshot-org/flameshot#942]
**Flameshot version**
0.8.0

**Describe the bug**
With common drawing tools, there will be an indicator following the cursor to show the size of the drawing tool:

(See the black square below):

![图片](https://user-images.githubusercontent.com/8443926/93691876-8fff7a00-fab9-11ea-95a4-3a8cfd234e18.png)

However on Windows, such indicator is missing for the circle counter tool:

(No square or anything at the cursor location except cursor (not included in the screenshot))

![图片](https://user-images.githubusercontent.com/8443926/93691897-c9d08080-fab9-11ea-9f86-f146c0c9f5f7.png)

I believe we should show an approximate size outline following the cursor so that users may know the size of counter circle.

**System version**

Tested to be reproducible on both Windows 10 and Debian Sid/Unstable.

**Comment by borgmanJeremy** [comment]
The root cause of this bug is in the ```paintMousePreview``` method. Most function use a "SquareCap" in their preview but I wanted to use a round cap since this is previewing for circles. For some reason setting the cap shape to circle breaks it. I'm looking into it but I really would like for it to preview as a circle instead of square.
