### ISSUE TITLE
AppImage 0.8 not work in elementary os

### ISSUE THREAD

**Issue by kt1024** [flameshot-org/flameshot#948]
**Flameshot version**
0.8

**Describe the bug**
AppImage 0.8 not work in elementary os 5.1.7 , no UI shows up. just a cursor blicked under error log. (process not exited itself).
error log as:
<pre>
:~/.bin$ chmod +x Flameshot-0.8.0-x86_64.AppImage 
:~/.bin$ ./Flameshot-0.8.0-x86_64.AppImage 
Run experimental self-contained bundle
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected

---------
:~$ ps aux | grep flame
ken      16919  0.0  0.2 296056 29448 pts/1    Sl+  17:32   0:00 /tmp/.mount_FlamesofPtDZ/lib64/ld-linux-x86-64.so.2 /tmp/.mount_FlamesofPtDZ/usr/bin/flameshot
</pre>

**To Reproduce**
run Appimage 0.8 in terminal

**Expected behavior**
show UI at least

**System Information**
elementary os 5.1.7 (based on ubuntu 18.0.4 x64 hwe, latest upgrade applied)

**Comment by mmahmoudian** [comment]
@kt1024 I think it works (because you can see the process) but not as you expect it to work 😉 So here is the description:
when you run `./Flameshot-0.8.0-x86_64.AppImage ` it will run the Flameshot in the background and also create the tray icon (if you have tray area in your WM). Then to use the flameshot you should do either of the followings:
1. use the tray icon, right-click and then from the menu choose the "Take screenshot"
2. use terminal: `./Flameshot-0.8.0-x86_64.AppImage gui`

Please try this and let me know if it works.

**Comment by kt1024** [comment]
sadly the OS removed sys tray as a "feature".  tried press `control + c` or `printscr` key did not show ui. (while the process still running)

process terminated after show the error message.
<pre>
$./Flameshot-0.8.0-x86_64.AppImage gui
Run experimental self-contained bundle
</pre>

**Comment by mmahmoudian** [comment]
@kt1024 the <kbd>printscr</kbd> does not perhaps work because you have not bind it to Flameshot.

Do what is explained in the AppImage section in here: https://github.com/flameshot-org/flameshot-org.github.io/blob/master/data/appimage-snap-flatpak.md

and then tell me if it works. then we will discuss how to make the <kbd>printscr</kbd> to work for you.

**Comment by kt1024** [comment]
@mmahmoudian  just like before
<pre>
ken@element:~/Applications/Flameshot$ ./Flameshot-0.8.0-x86_64.AppImage gui
Run experimental self-contained bundle
ken@element:~/Applications/Flameshot$ ./Flameshot-0.8.0-x86_64.AppImage
Run experimental self-contained bundle
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override passed, ignoring it.
    Available styles: Windows, Fusion
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
</pre>

**Comment by mmahmoudian** [comment]
@kt1024 you are doing it in the wrong order. First you should run it and then use the `gui` command:
1. `./Flameshot-0.8.0-x86_64.AppImage`
2. `./Flameshot-0.8.0-x86_64.AppImage gui`

**Comment by mmahmoudian** [comment]
@kt1024 yes, you observed correctly. Now few points:

To use one single terminal for working with flameshot, you can send it to the background in that terminal (remember if you close that terminal the flameshot will also get closed):
```sh
./Flameshot-0.8.0-x86_64.AppImage &>/dev/null &
```
and then in the same terminal:
```sh
./Flameshot-0.8.0-x86_64.AppImage gui
```

If you want to run it from terminal and be able to close the terminal without closing the flameshot so that you can later use flameshot `gui` in another terminal, you can `disown` it after running it:
```sh
./Flameshot-0.8.0-x86_64.AppImage &>/dev/null & ; disown
```

-------

Now, to connect your <kbd>printscr</kbd> to flameshot, do as suggested [here](https://elementaryos.stackexchange.com/a/19273):
> Open System settings > keyboard and there you will find "Shortcuts" tab, contains all the shortcuts. You can freely assign any key or combination you want. you can add custom command and bind it to any key/combination as well

[![](https://i.stack.imgur.com/WCn1E.png)](https://elementaryos.stackexchange.com/a/19274)


-------

If you wanna get systray in elementry, I found this: https://www.reallinuxuser.com/how-to-show-app-indicators-on-the-system-tray-in-elementary-os/

-------

**Comment by kt1024** [comment]
worked. thanks. @mmahmoudian
