### ISSUE TITLE
Manjaro KDE - flameshot only captures desktop

### ISSUE THREAD

**Issue by sbhattacharyya0** [flameshot-org/flameshot#970]
Flameshot cannot seem to capture any active windows. When Flameshot is opened, it only shows the desktop. I am running Manjaro KDE on Linux 5.8.

**Comment by mmahmoudian** [comment]
@sbhattacharyya0 Please fill the bug report completely so that we can understand the situation. You failed to provide the following:

- **Flameshot version**
  `<!-- Version or commit. -->`

- **Describe the bug**
  `<!-- A clear and concise description of what the bug is. -->`

- **To Reproduce**
  `<!-- Steps to reproduce the behaviour. -->`

- **Expected behavior**
  `<!-- A clear and concise description of what you expected to happen. -->`

Additionally, would it be possible to show us a demo. for example you can record your screen with [peek](https://github.com/phw/peek) and post the Gif file here to help us better understand the misbehavior.

**Comment by borgmanJeremy** [comment]
Closing for lack of details and response.
